modules/Students/student_view_details.php

Consistent sort

---

modules/System Admin/module_manage_installProcess.php

Fixed not being able to have no moduleTable set.

Fixed a bug related to moduleTable

---

functions.php

Added order and fixed date sometimes not working.

Updated getLog function

---

config-sample.php
installer/install.php
modules/System Admin/systemSettings.php

Reverts GibbonEdu/core#28. This should have gone to v11.0.00 branch, not Master.

Revert "Add Saudi Riyal to list of selectable currencies"

---

functions.php

getLog can now search for ip and endDate now works properly.

Updated getLog

---

functions.php

getLog now supports searching of the serialised array.

Update getLog function.

---

likes.php

Fixed a bug where "Giver" and "Role" appeared on the same line.

Fixed visual bug in second column.

---

CHANGELOG.txt
installer/install.php
modules/System Admin/systemSettings.php

Added MOP$  https://en.wikipedia.org/wiki/Macanese_pataca

System: added Macanese Pataca as currency

---

modules/Markbook/markbook_edit_data.php

A tiny bug, but a bug nonetheless :)

Fixed a Chrome-specific jQuery bug

---

src/Gibbon/trans.php

Revert "Translation sql no longer called in construct."

---

modules/Finance/expenses_manage_approve.php

Unless every Finance department has someone called "Somone".

Fixed typo.

---

CHANGEDB.php
cli/behaviour_letters.php
cli/planner_parentWeeklyEmailSummary.php
functions.php
modules/Finance/invoices_manage_editProcess.php
modules/Finance/invoices_manage_issueProcess.php
modules/Finance/invoices_manage_processBulk.php
modules/Finance/invoices_payOnlineProcess.php
modules/Messenger/messenger_postProcess.php
modules/Staff/applicationFormProcess.php
modules/Staff/applicationForm_manage_accept.php
modules/Students/applicationFormProcess.php
modules/Students/applicationForm_manage_accept.php
modules/System Admin/thirdPartySettings.php
modules/System Admin/thirdPartySettingsProcess.php

Our school needed to define a custom SMTP connection (for Google Apps mail), which I discovered is easy enough through the PHPMailer class, so I added a wrapper function to pull in some new settings from the Third Party Settings page. Also if PHPMailer settings ever change it'll be easier to update with a common function.
This could also go in System Settings or config.php, but it didn't seem like something that would need configured at install time or necessary for too many schools, so I tucked it away in Third Party.
Happy to update or change anything, just let me know.

System: Added SMTP mail support and connection settings

---

CHANGELOG.txt
modules/System Admin/thirdPartySettings.php
modules/Timetable Admin/courseEnrolment_manage.php
modules/Timetable Admin/courseEnrolment_manage_class_edit.php
modules/Timetable Admin/courseEnrolment_manage_class_editProcessBulk.php
modules/Timetable Admin/course_manage.php

We have a lot of courses, so a search and filter for Course Management helps a lot. Also added a bulk action to copy students from one class to another to help with course management.
Snuck the quick Google URL fix onto this PR too.

Timetable Admin: Added search & bulk action tools

---

CHANGEDB.php
cli/attendance_dailyIncompleteEmail.php
modules/Attendance/attendance.php
modules/Attendance/attendance_future_byPerson.php
modules/Attendance/attendance_take_byCourseClass.php
modules/Attendance/attendance_take_byCourseClassProcess.php
modules/Attendance/css/module.css
modules/Attendance/moduleFunctions.php
modules/Attendance/report_summary_byDate.php
modules/Attendance/report_summary_byDate_print.php
modules/Planner/planner_view_full.php
modules/School Admin/attendanceSettings.php
modules/School Admin/attendanceSettingsProcess.php
modules/Timetable Admin/course_manage_class_add.php
modules/Timetable Admin/course_manage_class_edit.php

Some minor updates: (not really changelog-worthy)
- Updated the attendance CLI to better omit empty result sets, and tidied the script up a bit with some more commenting
- Attendance CLI script will also only email the Administrator the report if it encounters a database error (rather than emailing each user an error message)
- Removed the redundant attendanceEnableByClass setting: relies on permissions instead
- Added a small breakdown of Attendance Types & Reasons to the summary for Student History
- Made the headings in Attendance Summary clickable to further view the Reason breakdown for each type

Attendance: Updated CLI and added info to Attendance Summary / Student History

---

CHANGEDB.php
cli/attendance_dailyIncompleteEmail.php
modules/School Admin/attendanceSettings.php
modules/School Admin/attendanceSettingsProcess.php

Minor changes to School Admin and Attendance CLI:
- Added settings to control notifications to Roll Group and/or Class
- Also added a setting for sending to additional users (was on my to-do list)

School Admin: Added Attendance CLI settings 

---

modules/Students/firstAidRecord_add.php

Changed/Removed and Renamed some unneeded cells in the form.

First Aid Form

---

functions.php
modules/Attendance/moduleFunctions.php
modules/Attendance/src/attendanceView.php
modules/Messenger/messenger_post.php
src/Gibbon/locale.php
src/Gibbon/menuModule.php
src/Gibbon/session.php

System: Minor attendance and OO fixes

---

modules/Attendance/attendance_future_byPerson.php

Just needed to add a blur() to force the validation re-check. I had been testing by typing and deleting the date contents, which would have manually triggered the lost-focus event.

Attendance: Fixed date validation in Set Future Absence

---

CHANGELOG.txt
modules/Markbook/markbook_viewExportAllContents.php
modules/Markbook/src/markbookView.php
src/Gibbon/Excel.php

Updated the Export to Excel for the markbook to bring it inline with the markbook features added in v12. A fairly minor change, no new strings added. Already live & tested on our v13 production server.

Markbook: added cumulative averages to markbook Export (if enabled)

---

CHANGELOG.txt
functions.php
index_fastFinder_ajax.php

View Student Profile_myChildren - Can only search students in their direct Family
View Student Profile_my - Can only see themselves in search
Otherwise, see all students
Plus a few small fixes for the dot and FF translation.

System: Improved Fast Finder student search permissions

---

CHANGELOG.txt
modules/Attendance/attendance_take_byCourseClass.php
modules/Attendance/css/module.css
modules/Attendance/moduleFunctions.php
modules/Planner/planner_view_full.php
modules/School Admin/attendanceSettings.php

Attendance: Dynamic legend for Student History report

---

modules/Markbook/markbook_edit_addMultiProcess.php
modules/Markbook/markbook_edit_copy.php

Also added select/deselect all to Markbook Copy Columns tool

Markbook: Fixed new column sequenceNumber for Add Multiple Columns

---

modules/Staff/applicationFormProcess.php

Looks like applicationFormProcess.php was moving the temp uploaded files for each position in the loop, which caused any references to those files after the first loop to fail. This change moves the processing of uploads to before the loop for each position, and collects an array of files that are then attached to each position once inside the loop.

Staff: Fixed application uploads when applying to multiple posititions

---

modules/System Admin/systemSettings.php
src/Forms/DatabaseFormFactory.php
src/Forms/FormFactory.php
src/Forms/Input/CustomField.php
src/Forms/Input/Date.php
src/Forms/Input/Input.php
src/Forms/Input/Select.php
src/Forms/Traits/BasicAttributesTrait.php

Some minor fixes and additions to the Form class (see commits for full list).
The fix for the Date picker will only apply to the OOified fields. There's still a quick flash of validation text which I couldn't manage to remove, seems to be tied to the jQuery change events between the jQuery.UI.Datepicker and LiveValidation.

Form class: Minor updates

---

CHANGELOG.txt
modules/Finance/invoices_manage_print.php
modules/Finance/moduleFunctions.php

- Set the invoice print page to list receipts for the Refunded status
- Updated the receipt format to include a Refund Total for refunded receipts

Finance: View and Print Refund Receipts

---

functions.php
modules/Attendance/attendance_take_byCourseClass.php
modules/Attendance/attendance_take_byRollGroup.php

- On the teacher dashboard, link My Classes > People column directly to the Attendance by Class page if the action is accessible and attendance is enabled for that class
- Removed alert bar from Attendance by Class/Roll Group pages

Attendance: Usability tweaks

---

CHANGELOG.txt
modules/Attendance/attendance_take_byCourseClass.php

Uses a left join with exclusion to remove students that have a timetable exception for the class & date.
Forum post: https://ask.gibbonedu.org/discussion/1491/attendance-by-class-exceptions-in-class-lists-not-working

Attendance: Updated Take Attendance by Class to honour TT exceptions

---

CHANGEDB.php
modules/Data Updater/data_personal_manage_editProcess.php
modules/Individual Needs/in_editProcess.php
modules/Students/student_view_details_notes_addProcess.php
modules/User Admin/user_manage_editProcess.php

A few more notification events to help round-out the feature for v14:
- Updated Individual Needs (new)
- New Student Note (existing)
- Updated Privacy Settings (existing)

System: Added more notification events

---

src/Forms/Form.php
src/Forms/FormFactory.php
src/Forms/FormRenderer.php
src/Forms/Input/CustomField.php
src/Forms/Input/FileUpload.php
src/Forms/Input/Radio.php
src/Forms/Layout/Table.php
src/Forms/Layout/Trigger.php
src/Forms/Traits/InputAttributesTrait.php

Some form class updates, made for the Application Form OOification (split into a separate PR to keep things manageable).
The changes can be seen in the commit log, with some notable ones:
- Added a loadFrom() method for all Input types, to assist with loading values from an array and not having to check array keys exist for each item
- Fixed the native HTML accept attribute in the File type to match the LiveValidation list
- CustomField class for handling user-defined field data

Form Class: Minor improvements for Application Form

---

modules/Students/applicationForm_manage_accept.php

A minor change to the query that fixes houses not being assignable if there were no student's already in them.

Students: Updated auto house assign in Application Form accept process

---

modules/Students/applicationForm_manage_edit.php
src/Forms/DatabaseFormFactory.php
src/Forms/Form.php
src/Forms/Input/Date.php
src/Forms/Input/PhoneNumber.php
src/Forms/Layout/Row.php
src/Forms/Layout/Table.php
src/Forms/Traits/InputAttributesTrait.php
tests/acceptance/User Admin/ApplicationFormSettingsCept.php

OOifies the edit page under Manage Applications similar to the application form. Helps fix some untranslated strings that were kicking around in the original edit application page (without adding any new strings).
Also some form class updates along the way:
- Added a loadAllValuesFrom() method to the Form class that can take an array from the database and populate all the fields in the form. Handy for add/edit forms.
- Added loadFrom() methods to Row and Table classes to facilitate loadAllValuesFrom()
- Tidied up the PhoneNumber class

Students: Manage Application Form OOification

---

modules/Markbook/markbook_edit_add.php

One line!!! :woman_facepalming:

Markbook: Fixed missing select tag causing chained script recursion

---

tests/acceptance/School Admin/ExternalAssessmentsManageCept.php
tests/acceptance/School Admin/FacilitiesManageCept.php
tests/acceptance/School Admin/GradeScalesManageCept.php
tests/acceptance/School Admin/RollGroupsManageCept.php

Some tests for pages that didn't get OOified yet, but its probably good to get them into dev branch anyway (I assume we'll likely strip the all tests out for the release?)
This brings the test count up to 50 for v14, all tests passing with the old and new demo data.

Tests: Added more acceptance tests in School Admin

---

functions.php
modules/Activities/activities_manage_enrolment.php
modules/Data Updater/report_student_dataUpdaterHistory.php
modules/Messenger/messenger_postProcess.php
modules/Students/medicalForm_manage_add.php
modules/Students/student_view_details.php

PHP notice cleanup during release prep, a couple notable ones:
- Found and removed an odd form element from Activities Manage Enrolment (likely a copy-paste artifact, there's no input or submit button for that section).
- Re-connected a link to Add Medical Form from Student Profile (looks like medical forms may have been managed in User Admin at some point and then moved?)

System: Fixes for PHP notices

---

CHANGELOG.txt
modules/Timetable/moduleFunctions.php

Another PHP notice fix, maybe related to the forum thread? https://ask.gibbonedu.org/discussion/comment/3143#Comment_3143

Timetable: Fixed PHP notice in renderTTDay module function

---

tests/acceptance/Students/ApplicationFormAccessCept.php
tests/acceptance/Students/ApplicationFormAlternateCept.php

Improved the test coverage for the application form by adjusting the application/user settings before each test: two tests now, one with all optional settings enabled, one with them disabled. Also added a quick test to check & confirm the public access setting.

Tests: Updated and added tests to cover Student Application Form

---

modules/Attendance/src/attendanceView.php
modules/User Admin/user_manage_add.php
modules/User Admin/user_manage_edit.php
modules/User Admin/user_manage_editProcess.php

Based on commit [ab4c686](https://github.com/GibbonEdu/core/commit/ab4c686edd2b558d15edc4917d40e2fe98fa7434). These haven't been an issue but best to be on the safe side.

User Admin, Attendance: Removed strict parameter from in_array

---

.gitignore

Hi,
Update the .gitignore file to ignore Netbeans IDE project files

Ignore Netbeans IDE project files

---

CHANGELOG.txt
modules/Timetable Admin/course_rollover.php

From forum post: https://ask.gibbonedu.org/discussion/1970/course-and-class-rollover
Adds a table join for gibbonPerson to check the users status=Full, and a left exclusion join on the gibbonCourseClassPerson for the next year, to prevent duplicate enrolments.

Timetable Admin: updated Course Enrolment Rollover query

---

src/Forms/Input/Radio.php

Form Class: updated required Radio elements to select first option by default

---

lib/google/index.php

Addition to https://github.com/GibbonEdu/core/commit/7ffb4667257c5b5867ddaa0316a07361f3c93dd5

System: re-auth during Google login if refresh token is not saved

---

CHANGELOG.txt
modules/User Admin/user_manage_add.php
modules/User Admin/user_manage_addProcess.php
modules/User Admin/user_manage_edit.php
modules/User Admin/user_manage_editProcess.php

A feature our office requested: updates the Birth Certificate, Passport Scan and ID Card Scan fields to allow PDF uploads. Useful for the core, or no?

User Admin: updated Add/Edit User to allow PDF files for ID documents

---

src/Forms/Input/Select.php

Minor fix to prevent re-selecting an Option if there's duplicates with the same value

Form Class: added check to only select first option found in Select class

---

src/Forms/Input/Select.php

Form Class: fixed the fix for selecting only one option in Select class

---

src/Forms/Input/Number.php

Two quick fixes:
- setting decimalPlaces(0) enforces integer-only numbers
- fixed decimalPlaces(n) allowing >n decimal places

Form Class: updated decimal handling in Number class

---

functions.php
themes/Default/css/main.css

OOified the login form, part of an upcoming PR to add the same login options to the Google login button.

System: login form OOification

---

CHANGELOG.txt
functions.php
lib/google/index.php

Adds the options link to the Google login button, letting users select a school year and language on login. Uses the same past/future school year access logic from login.php

System: added login options to Login with Google button

---

lib/google/index.php

Small fix for the options link ending up inside a table after opening & closing.

System: visual fix for Google login options show/hide

---

modules/School Admin/house_manage_assign.php
modules/Students/report_students_byHouse.php

School Admin: fixed file headers for recent assign houses tool

---

cli/attendance_dailyIncompleteEmail.php

**Bug Fix**
A very small fix for everyone's favourite CLI 😄

System: added gibbonPerson status check to attendance CLI

---

src/Data/UsernameGenerator.php

User Admin: fixed illegal chars in username generation

---

src/Forms/DatabaseFormFactory.php
src/Forms/FormFactory.php
src/Forms/Input/Checkbox.php
src/Forms/Input/Finder.php
src/Forms/Traits/BasicAttributesTrait.php
src/Forms/Traits/MultipleOptionsTrait.php
themes/Default/js/common.js

**New Features & Updates**
Some additions and changes for a handful of upcoming OOification PRs.
- Finder input works on tokenized inputs, which can be provided a set of tokens using the standard fromArray/fromQuery/fromResults methods, and an additional fromAjax method
- SearchSubmit button includes the Clear Form link and Go button-text
- addCheckAllNone() method to easily add an All/None option to the top of a checkbox list

Form Class: added Finder input, SearchSubmit button, minor changes

---

modules/School Admin/department_manage.php
modules/School Admin/department_manage_add.php
modules/School Admin/department_manage_edit.php
modules/School Admin/space_manage_add.php
modules/School Admin/space_manage_edit.php
tests/acceptance/School Admin/DepartmentsManageCept.php

**Refactoring**
Includes an automated test for Departments (facilities already has one)

School Admin: Manage Departments and Manage Facilities OOification

---

modules/School Admin/externalAssessments_manage_add.php
modules/School Admin/externalAssessments_manage_edit.php
modules/School Admin/externalAssessments_manage_edit_field_add.php
modules/School Admin/externalAssessments_manage_edit_field_addProcess.php
modules/School Admin/externalAssessments_manage_edit_field_edit.php
modules/School Admin/externalAssessments_manage_edit_field_editProcess.php

School Admin: Manage External Assessments OOification

---

src/Forms/Input/FileUpload.php
themes/Default/css/main.css

**Visual Fix**
A darker background didn't look much better either so got rid of the border.

Form Class: removed border from FileUpload max file size text

---

modules/School Admin/schoolYearSpecialDay_manage_add.php
modules/School Admin/schoolYearSpecialDay_manage_addProcess.php
modules/School Admin/schoolYearSpecialDay_manage_edit.php
modules/School Admin/schoolYearSpecialDay_manage_editProcess.php

School Admin: Manage Special Days OOification

---

modules/School Admin/externalAssessments_manage_edit_field_add.php
modules/School Admin/externalAssessments_manage_edit_field_edit.php
src/Forms/Traits/InputAttributesTrait.php

**Bug Fix**
Also made a small fix to the loadFrom method in the InputAttributesTrait to not turn 0 values into blank fields.

School Admin: fixed external assessment name field in Add/Edit Grade

---

modules/School Admin/gradeScales_manage_add.php
modules/School Admin/gradeScales_manage_edit.php
modules/School Admin/gradeScales_manage_edit_grade_add.php
modules/School Admin/gradeScales_manage_edit_grade_edit.php

School Admin: Manage Grade Scales OOification

---

modules/School Admin/rollGroup_manage_add.php
modules/School Admin/rollGroup_manage_edit.php
themes/Default/css/main.css

School Admin: Manage Roll Groups OOification

---

modules/Resources/resources_manage.php
modules/Resources/resources_manage_add.php
modules/Resources/resources_manage_addProcess.php
modules/Resources/resources_manage_edit.php
modules/Resources/resources_manage_editProcess.php
modules/Resources/resources_view.php
src/Forms/Input/Checkbox.php
tests/acceptance/Resources/ResourcesManageCept.php

**Refactoring**
Implements the new Finder class for searching & adding tags. Adds automated tests for Resources.

Resources: OOified View and Manage Resources

---

modules/Timetable/report_viewAvailableSpaces.php
modules/Timetable/report_viewAvailableTeachers.php
modules/Timetable/spaceBooking_manage_add.php
modules/Timetable/spaceChange_manage_add.php
modules/Timetable/tt.php
modules/Timetable/tt_master.php
modules/Timetable/tt_space.php

Timetable: OOified Manage Facility Changes, Bookings, search forms

---

modules/Staff/applicationForm_manage_accept.php

Staff: fixed SQL lock issue in staff application accept

---

CHANGEDB.php
modules/Students/applicationForm.php
modules/User Admin/applicationFormSettings.php
modules/User Admin/applicationFormSettingsProcess.php

An addition to PR #346, adds a Yes/No toggle to the Available Years of Entry selection to ensure it's not enabled by default.

User Admin: added Enable Limited Years of Entry setting

---

tests/acceptance/Planner/AddResourceInvalidFileCept.php
tests/acceptance/Planner/AddResourceValidFileCept.php
tests/acceptance/Planner/ResourcesManageCept.php

**Tests**
Moved and updated resource tests to correspond with their move into the Planner module.

Tests: moved Resources tests into the Planner folder

---

CHANGELOG.txt
modules/System Admin/js/module.js
modules/System Admin/moduleFunctions.php

**Bug Fix**
Adds a versionCompare function to module.js to handle comparing semantic version strings.

System Admin: updated version check to handle semantic version numbers

---

.travis.yml

Tests: add email notifications to Travis CI config

---

.travis.yml

Tests: fix notifications in Travis CI config file

---

src/Forms/Input/CustomBlocks.php
src/Forms/Input/Editor.php
src/Forms/Input/Input.php
src/Forms/Input/MultiSelect.php

**Bug Fix**
Allows the outputable interface template to fill up the space its provided.
Fixes a bug which causes errors when using MultiSelect.
This allows for better/more customisation of the Blocks. Also allows for the usage of MultiSelect.
All the same tests that the original elements was subjected to.

Form Class fixes and adjustments

---

modules/Behaviour/behaviour_letters.php
modules/Behaviour/behaviour_manage.php
modules/Behaviour/behaviour_manage_add.php
modules/Behaviour/behaviour_pattern.php
modules/Behaviour/behaviour_view.php

Form OOification from the Gibbon Hackathon (21 Oct 2017). 
The modules 'Find Behaviour Patterns', 'View Behaviour Letters', and 'View Behaviour Records' modules were OOified (though they might need to be tested). 
Another module, 'Manage Behaviour Records' was also partially completed - the filter (in behaviour_manage.php) was OOified, but the creation of behaviour records (in behaviour_manage_add.php and behaviour_manage_addMulti.php) have yet to be done. Some work was started on the former.

Form OOification - Behaviour Modules

---

modules/Behaviour/behaviour_manage_add.php
src/Forms/Input/Select.php

Minor fix for the Select class, helps prevent duplicate blank options as seen in Find Behaviour Patterns.
Edit: snuck the chainedTo for Add Behaviour Record onto this PR 😄

Form Class: prevent duplicate placeholders if the first option is already blank

---

modules/Formal Assessment/internalAssessment_view.php
modules/Individual Needs/in_summary.php

Post OOification testing & tweaks

---

modules/Timetable Admin/course_manage_add.php
modules/Timetable Admin/course_manage_addProcess.php
modules/Timetable Admin/course_manage_class_add.php
modules/Timetable Admin/course_manage_class_addProcess.php
modules/Timetable Admin/course_manage_class_edit.php
modules/Timetable Admin/course_manage_class_editProcess.php
modules/Timetable Admin/course_manage_edit.php
modules/Timetable Admin/course_manage_editProcess.php
tests/acceptance/Timetable Admin/CoursesManageCept.php

Also adds test coverage for courses & classes.
_Edit: Found the root of the failed Travis tests - the demo data has some orphaned classes that coincide with the next auto-increment for a new course, so it was mysteriously pre-populating the classes list and failing the tests (only on a fresh install)_ :thinking:

Timetable Admin: OOified Manage Courses & Classes

---

modules/Activities/activities_attendance.php
modules/Activities/activities_manage.php
modules/Attendance/attendance_studentSelfRegister.php
modules/Attendance/attendance_take_byCourseClass.php
modules/Attendance/attendance_take_byRollGroup.php
modules/Departments/department_course_class.php
modules/Markbook/markbook_view_allClassesAllData.php
modules/Planner/units.php
modules/Students/report_emergencySMS_byTransport.php
modules/Students/report_emergencySMS_byYearGroup.php
modules/Timetable Admin/courseEnrolment_manage_class_edit.php
modules/Timetable/spaceBooking_manage_delete.php

System: fix instances of old translation function in various files

---

src/Forms/DatabaseFormFactory.php
src/Forms/FormFactory.php
src/Forms/Input/Input.php
src/Forms/Layout/Column.php
src/Forms/Layout/Element.php
src/Forms/Layout/Label.php
themes/Default/css/main.css

* Updated the behaviour of the wrap() method to allow chained/nested wraps
* Columns with the same ID as required child-elements will inherit the required status (for labeling with a *)
* Update input validation so multiple validations of the same type can be added (required for password validation)
* Fix an alignment issue with inline column divs
* Adds SelectStatus to the DatabaseFormFactory
* Adds SelectEmergencyRelationship to the FormFactory

Form Class: general usability and visual improvments

---

modules/User Admin/userFields_add.php
modules/User Admin/userFields_addProcess.php
modules/User Admin/userFields_edit.php
modules/User Admin/userFields_editProcess.php
src/Forms/Layout/Trigger.php

Updates the Form class visibility toggles to accept an array of values for the `when()` and `whenNot()` methods. Also updates some array handling.

User Admin: post-ooficiation for Custom Fields

---

modules/User Admin/permission_manage.php
modules/User Admin/permission_manageProcess.php
modules/User Admin/user_manage.php

Also fixed a missing translation from my last PR 😄

User Admin: Manage Permissions OOification

---

modules/Students/student_view_details.php
modules/User Admin/permission_manage.php
modules/User Admin/permission_manageProcess.php
src/Forms/Traits/MultipleOptionsTrait.php

Students, User Admin: Post-OOification tweaks

---

modules/Data Updater/data_family.php
modules/Data Updater/data_family_manage.php
modules/Data Updater/data_family_manage_delete.php
modules/Data Updater/data_family_manage_edit.php
tests/acceptance/Data Updater/UpdateFamilyDataCept.php
themes/Default/css/main.css

 Data Updater: Update Family Data OOfification 

---

modules/Data Updater/data_personal.php
modules/Data Updater/data_personalProcess.php
modules/Data Updater/data_personal_manage.php
modules/Data Updater/data_personal_manage_delete.php
modules/Data Updater/data_personal_manage_edit.php
src/Forms/Form.php
src/Forms/Layout/Row.php
tests/acceptance/Data Updater/UpdatePersonalDataCept.php

Test coverage + OOification. There's an automated test but this one could use some extra manual testing.
❤️ deleting all that code!

Data Updater: Update Personal Data OOification 

---

themes/Default/css/main.css

A couple small aesthetic fixes from the recent ooification. Hopefully the last css changes for a bit, I hope to get the recent stuff merged back into my sass files and PR those soon. They'll clean things up a lot and sort out the cascade, which should help eliminate the need for all the `!important` everywhere 😄

Theme: tweaks to headings inside forms and row stripes

---

assets/js/core.js
modules/User Admin/permission_manage.php
themes/Default/css/main.css

Adds the columnHighlight class as a reusable behaviour and implements in Manage Permissions.

User Admin: add columnHighlight to Manage Permissions 

---

modules/Students/student_view_details.php

A small adjustment to add the IN assistants (as listed in the Overview) to the IN subpage as well. Also fixes a permissions check in the IN subpage.
As always, really appreciate the time it takes to review and merge these. Many thanks! 😄

Students: add educational assistants to IN subpage on Student Profile 

---

modules/Attendance/attendance_take_byCourseClass.php
modules/Attendance/attendance_take_byRollGroup.php
modules/Attendance/src/attendanceView.php

**Bug Fix**
Fixes the count at the bottom of the take attendance screen to properly account for Present - Offsite. Also adds a visual highlight to offsite, distinct from the absent highlight.
Just a quick fix for this one, will catch all the inline styles with a future OOification.

Attendance: fix attendance mis-counting Present - Offsite as present 

---

modules/Rubrics/rubrics.php
modules/Rubrics/rubrics_add.php
modules/Rubrics/rubrics_addProcess.php
modules/Rubrics/rubrics_delete.php
modules/Rubrics/rubrics_duplicate.php
modules/Rubrics/rubrics_edit.php
modules/Rubrics/rubrics_editProcess.php
modules/Rubrics/rubrics_edit_editRowsColumns.php
modules/Rubrics/rubrics_edit_editRowsColumnsProcess.php
modules/Rubrics/rubrics_view.php
src/Forms/Layout/Column.php

The only thing not tackled yet is the AJAX-ified view and edit forms in moduleFunctions, made a note in the progress tracker. Will catch that one soon & hopefully improve the load times (from the roadmap issues)

Rubrics: OOification

---

modules/Activities/activities_view_register.php
modules/Crowd Assessment/crowdAssess_view_discuss_post.php
modules/Individual Needs/iep_view_myChildren.php
modules/Individual Needs/in_archive.php
modules/Individual Needs/in_view.php
modules/Students/applicationForm_manage.php

OOified a few misc forms to finish up some modules in the progress tracker.

Individual Needs, Activities, Students, Crowd Assessment: OOification

---

modules/Formal Assessment/externalAssessment.php
modules/Formal Assessment/externalAssessment_manage_details_add.php
modules/Formal Assessment/externalAssessment_manage_details_delete.php
modules/Formal Assessment/externalAssessment_manage_details_edit.php
modules/Formal Assessment/externalAssessment_manage_details_editProcess.php
modules/Formal Assessment/externalAssessment_view.php
modules/Formal Assessment/import_internal_results.php
modules/Formal Assessment/import_results.php
modules/Formal Assessment/internalAssessment_manage_delete.php
modules/Formal Assessment/internalAssessment_view.php
modules/Formal Assessment/moduleFunctions.php

The only thing still pending in the module is the internal assessment manage/write, going to grab that with the markbook (which will be fun 😄) as they share a lot of layout elements.

Formal Assessment: OOification

---

modules/Timetable/moduleFunctions.php
modules/Timetable/report_viewAvailableSpaces.php
modules/Timetable/report_viewAvailableTeachers.php

Timetable: fix substring length in row heading for timetable hours

---

modules/School Admin/space_manage.php

We got up to four pages on the Manage Facilities list, needed to add a search 😄 
_Edit: the fix for the build is in PR #417_

School Admin: add search to Manage Facilities page

---

modules/Staff/staff_manage_edit_contract_add.php
modules/Staff/staff_manage_edit_contract_edit.php
modules/Staff/staff_manage_edit_contract_editProcess.php
src/Forms/Input/Currency.php
src/Forms/Input/Date.php
src/Forms/Input/Input.php
src/Forms/Input/Select.php
src/Forms/Layout/Column.php
src/Forms/Layout/Label.php

**Bug Fix**
- Updates the `getLabelContext()` method to pass in the Label object being rendered. Helps handle labels linked to fields in nested columns.
- Applies the change to the Add & Edit Contract forms in Manage Staff
- Fixes the file attachment in Edit Contract to allow file deletion

Form Class: update getLabelContext method

---

modules/Activities/activities_manage.php
modules/Activities/activities_manageProcessBulk.php
modules/Activities/activities_manage_add.php
modules/Activities/activities_manage_addProcess.php
modules/Activities/activities_manage_edit.php
modules/Activities/activities_manage_editProcess.php
modules/Activities/activities_manage_enrolment.php
modules/Activities/activities_manage_enrolment_add.php
modules/Activities/activities_manage_enrolment_edit.php
modules/Activities/activities_payment.php
modules/Activities/activities_paymentProcessBulk.php
modules/Activities/activities_view.php
modules/Activities/activities_view_register.php
modules/Activities/moduleFunctions.php
modules/Activities/report_activityEnrollmentSummary.php
src/Forms/Input/Time.php
themes/Default/css/main.css

_Edit: removed a stray reference to gibbonActivityType, that's a different feature set_ 😅

Activities: Manage Activities OOification

---

modules/Attendance/attendance_take_byCourseClass.php
modules/Attendance/attendance_take_byPerson.php
modules/Attendance/attendance_take_byPerson_edit.php
modules/Attendance/attendance_take_byRollGroup.php
modules/Attendance/css/module.css
modules/Attendance/moduleFunctions.php
modules/Attendance/src/attendanceView.php
src/Forms/DatabaseFormFactory.php
src/Forms/FormFactory.php
src/Forms/Layout/Grid.php

Included with the PR:
- Adds a Grid layout class for easily displaying elements in a flexible grid. It's rendering as a table right now for consistency but once we have some responsive classes in the theme it'll be easy to make the grids responsive as well.
- Updates the renderMiniHistory method to reduce the number of separate queries (was impacting page load times, n+1 issue)
- Some improvements to the css layout and border-collapse for attendance and student history
Still sussing-out how to tackle some of the complexities of the attendance system, at least getting the ooification out of the way should help.

 Attendance: OOified Take Attendance by Person/Class/Roll Group

---

modules/Rubrics/css/module.css
modules/Rubrics/moduleFunctions.php

Finished up the last piece of the rubric ooification. Bumps up the tracker to 80% 😃

Rubrics: OOification of View & Edit Rubric forms

---

modules/Rubrics/rubrics_add.php
modules/Rubrics/rubrics_edit.php

A couple post-ooification fixes.

Rubrics: fix learning area in Add Rubric and validation in Edit Rubric

---

modules/Activities/activities_attendance.php
modules/Activities/activities_attendanceProcess.php
modules/Activities/css/module.css
modules/Activities/js/module.js
src/Forms/FormRenderer.php

Merged in Andy's work from the hackathon and added the ooified attendance form.

Activities: OOified Activity Attendance

---

modules/Messenger/cannedResponse_manage_add.php
modules/Messenger/cannedResponse_manage_edit.php
modules/Messenger/messageWall_view.php
modules/Messenger/messenger_manage.php
modules/Messenger/messenger_postQuickWall.php
themes/Default/css/main.css

All but the New Message/Edit Message forms, which will be tonnes of fun for whoever tackles that one 😄

Messenger: OOification

---

modules/Markbook/markbook_view_myMarks.php
modules/Markbook/markbook_view_viewMyChildrensClasses.php
modules/Markbook/moduleFunctions.php
modules/Markbook/weighting_manage.php
modules/Markbook/weighting_manage_add.php
modules/Markbook/weighting_manage_edit.php
src/Forms/Input/Number.php

Some progress on markbook ooification. There's another seven forms to go so split this one into two PRs.

Markbook: OOified Manage Weightings, sidebar and filters

---

modules/Timetable Admin/courseEnrolment_manage.php
modules/Timetable Admin/courseEnrolment_manage_byPerson.php
modules/Timetable Admin/courseEnrolment_manage_byPerson_edit.php
modules/Timetable Admin/courseEnrolment_manage_byPerson_editProcessBulk.php
modules/Timetable Admin/courseEnrolment_manage_byPerson_edit_edit.php
modules/Timetable Admin/courseEnrolment_manage_class_edit.php
modules/Timetable Admin/courseEnrolment_manage_class_editProcessBulk.php
modules/Timetable Admin/courseEnrolment_manage_class_edit_edit.php
modules/Timetable Admin/course_manage.php
modules/Timetable Admin/course_rollover.php
modules/Timetable/studentEnrolment_manage_edit.php
modules/Timetable/studentEnrolment_manage_editProcessBulk.php
modules/Timetable/studentEnrolment_manage_edit_edit.php

Uses the recently added BulkActionForm to finish up the Timetable Admin module. Also includes the one similar Manage Student Enrolment page from the Timetable module.
_Edit: Also includes the Course Enrolment Rollover, tested a bunch but could always use extra testing._

Timetable Admin: OOified Bulk Actions and Course Enrolment

---

functions.php
indexFindRedirect.php
modules/Markbook/markbook_view_myMarks.php
modules/Markbook/markbook_view_viewMyChildrensClasses.php
modules/Students/student_view_details.php

Caught a couple more forms that weren't in the spreadsheet. Also tacked on one small change to the Show/Hide filters from earlier.

System: OOified the Fast Finder and Parent Photo Upload

---

modules/School Admin/attendanceSettings_manage_add.php
modules/School Admin/attendanceSettings_manage_edit.php
modules/School Admin/inSettings_add.php
modules/School Admin/inSettings_edit.php
modules/School Admin/schoolYearSpecialDay_manage.php
modules/School Admin/studentsSettings_noteCategory_add.php
modules/School Admin/studentsSettings_noteCategory_edit.php
src/Forms/DatabaseFormFactory.php

Caught a few missing ooifications.

School Admin: OOified Attendance Codes, IN Descriptors, Note Categories

---

modules/System Admin/module_manage_edit.php
modules/System Admin/module_manage_uninstall.php
modules/System Admin/module_manage_update.php
modules/System Admin/stringReplacement_manage.php
modules/System Admin/theme_manage.php
modules/System Admin/update.php

Caught a few missing ooifications.

System Admin: OOified System Update, Manage Modules, Themes

---

modules/Planner/resources_addQuick_ajax.php
modules/Planner/resources_add_ajax.php
modules/Planner/resources_add_ajaxProcess.php
modules/Planner/resources_insert_ajax.php
modules/Planner/resources_manage_add.php
src/Forms/Input/Finder.php
src/Forms/Layout/WebLink.php

These must have slipped by unnoticed when I did the other resource forms. I think these are the last of the forms not tracked in the spreadsheet 😃

Planner: OOified Ajax Add & Insert Resources

---

modules/Activities/activities_my.php

Finished OOification for My Activities page. I did spot some issues with the 3 options on the page but they refer to other pages on Gibbon. Happy to investigate if that's something caused by the commit.

My Activities

---

modules/Planner/resources_insert_ajax.php
modules/System Admin/moduleFunctions.php
modules/System Admin/module_manage_edit.php
modules/System Admin/theme_manage.php
themes/Default/css/main.css

- Adds the version increment back into the Manage themes page
- Fixes the tags field width in the Insert Resource ajax script
- Adjusts the layout of module descriptions in Edit Module

System Admin & Planner: post-ooification tweaks

---

modules/Activities/activities_attendance.php
modules/Activities/css/module.css
modules/Formal Assessment/internalAssessment_manage_add.php
modules/Formal Assessment/internalAssessment_manage_edit.php
modules/Formal Assessment/internalAssessment_manage_editProcess.php
modules/Formal Assessment/internalAssessment_write_data.php
modules/Formal Assessment/internalAssessment_write_dataProcess.php
src/Forms/DatabaseFormFactory.php
src/Forms/FormFactory.php
src/Forms/Input/Select.php
src/Forms/Layout/Table.php
src/Forms/Layout/TableCell.php
src/Forms/Traits/BasicAttributesTrait.php
src/Forms/Traits/MultipleOptionsTrait.php
themes/Default/css/main.css

Finishes out the formal assessment module and sets up some classes/css to also use with the markbook ooification. 
A couple notable changes:
- In the Form classes, adds an optional groupBy parameter to the fromQuery and fromResults methods to simplify creating nested optgroups in form selects
- Adds TableCell class and re-works the Table class to handle the rowspan and colspan attributes (used for the markbook-edit-style form layouts).
- The addSelectScaleGrade is an ooified replacement for the global renderGradeScaleSelect function
- Adds css utility classes (to help with embedded form tables, but useful for various layout purposes)
Last PR of the year from me 😄

Formal Assessment: OOified Internal Assessment

---

modules/Timetable Admin/ttDates.php

Fixes the SQL at the end of ttDate.php, just a casing issue.

ttDate.php Fix

---

modules/Attendance/attendance_future_byPerson.php
modules/Formal Assessment/css/module.css
modules/Formal Assessment/internalAssessment_write_data.php
modules/Individual Needs/in_edit.php
modules/Timetable Admin/courseEnrolment_sync_edit.php
modules/Timetable Admin/report_classEnrolment_byRollGroup.php
src/Forms/Layout/Table.php
themes/Default/css/main.css

OOifications:
- Formal Assessment: Individual Needs View & Edit page
- Timetable Admin: Class Enrolment by Roll Group 
- Post-ooification tweaks to Attendance: Set Future Absence page
Fixes:
- Sets the width of grade selects on the Write Internal Assessment page (previously bundled in with the markbook ooification which is bumped to v16)
- Aligns the checkall checkbox in Course Enrolment Sync
- Adjusts the standardWidth field to `width: auto` when inside a nested form table (to prevent tables overflowing the form)

Final v15 OOification and minor fixes

---

CHANGELOG.txt
src/Forms/FormFactory.php

System: add Fijian Dollar as a currency

---

CHANGELOG.txt
modules/User Admin/user_manage_add.php
src/Gibbon/FileUploader.php

Related to forum issue: https://ask.gibbonedu.org/discussion/comment/4038
Also adds a validation pattern to usernames to prevent characters that aren't filename-friendly (particularly slashes, brackets, etc).

System: fix FileUploader handling of filenames with dots it them 

---

assets/js/core.js
modules/Staff/applicationForm.php
modules/Staff/applicationForm_manage_edit.php
modules/Students/applicationForm.php
modules/Students/applicationForm_manage_edit.php
modules/User Admin/user_manage_emailAjax.php
src/Forms/Traits/InputAttributesTrait.php

- Fixes the flash of validation error on-submit (due to how the uniqueness check hooks into the LV onValid function). I think it was happening in all the forms, the Library Duplicate was the only one short enough to notice the effect.
- Adds isUnique to email fields on Student Application and Staff Application

Form Class: update isUnique JS and add to application form emails

---

tests/acceptance/Markbook/AddAndEditMarkbookColumnCept.php

Adds a test to help cover the various settings and data entry options for the markbook column.

Tests: add Markbook Add/Edit Column and Enter Data test

---

modules/Finance/css/module.css
modules/Finance/expenseRequest_manage_view.php
modules/Finance/expenses_manage.php
modules/Finance/expenses_manage_add.php
modules/Finance/expenses_manage_approve.php
modules/Finance/expenses_manage_edit.php
modules/Finance/expenses_manage_print.php
modules/Finance/expenses_manage_print_print.php
modules/Finance/expenses_manage_view.php
modules/Finance/moduleFunctions.php

I've endeavored to test this in as many ways as I can think of but it likely needs a good once-over by someone more familiar with Finance features.

Finance: OOification of Manage Expenses

---

modules/Timetable/moduleFunctions.php

This change adds a "This Week" button to the top of the timetable along with the Last and Next Week buttons. Useful if you navigate far from the current date and you would like to get back quickly.

"This Week" button

---

CHANGELOG.txt
modules/Attendance/attendance.php

From forum issue: https://ask.gibbonedu.org/discussion/comment/4211#Comment_4211

Attendance: fix date format for links in View Daily Attendance

---

CHANGELOG.txt
modules/Timetable/moduleFunctions.php
themes/Default/css/main.css

Also see next pull request with updates to main.css

New "today" highlight

---

modules/Activities/report_attendanceExport.php

I'm going to guess you were debugging this script at some point 😄

Activities: remove debug output from activity attendance export

---

CHANGELOG.txt
modules/Planner/planner_add.php
modules/Planner/planner_addProcess.php
modules/Planner/planner_edit.php
modules/Planner/planner_editProcess.php

I decided it was best to leave the notification off by default so the teacher could turn it on only when he thought it necessary.

Added notify class code for Planner Add and Edit pages

---

modules/System Admin/moduleFunctions.php
modules/System Admin/module_manage.php
modules/System Admin/module_manage_uninstall.php
modules/System Admin/notificationSettings.php
modules/System Admin/stringReplacement_manage.php
modules/System Admin/theme_manage.php
src/Domain/DataSet.php
src/Domain/System/ModuleGateway.php
src/Domain/System/StringGateway.php
src/Forms/Layout/Element.php
src/Services/Format.php
src/Tables/Action.php
src/Tables/Renderer/SimpleRenderer.php

OOified:
- Manage Modules: splits the installed and uninstalled modules, and adds a row-highlight for modules with available updates.
- String Replacements
- Notification Settings
- Tweaks a few things here and there for usability and fixes a couple small issues found in testing (eg: getAppended returning $prepended 😄 ).

System Admin: table ooification

---

modules/Staff/applicationForm_manage.php
modules/Staff/jobOpenings_manage.php
modules/Staff/staff_manage.php
modules/Staff/staff_view.php
src/Domain/Staff/StaffApplicationFormGateway.php
src/Domain/Staff/StaffGateway.php
src/Domain/Staff/StaffJobOpeningGateway.php
src/Tables/Renderer/SimpleRenderer.php

Ooifies:
- View Staff
- Manage Staff
- Job Openings
- Manage Applications

Staff: table ooification

---

modules/Data Updater/data_familyProcess.php
modules/Data Updater/data_financeProcess.php
modules/Data Updater/data_medicalProcess.php
modules/Data Updater/data_personalProcess.php
modules/Data Updater/data_updates.php
tests/acceptance/Data Updater/UpdateFamilyDataCept.php
tests/acceptance/Data Updater/UpdateFinanceDataCept.php
tests/acceptance/Data Updater/UpdateMedicalDataCept.php
tests/acceptance/Data Updater/UpdatePersonalDataCept.php

Removes the check for required updates, instead redirecting all successful data updates back to the My Data Updater page.

Data Updater: update to always redirect to My Data Updates on success

---

modules/System Admin/moduleFunctions.php
modules/User Admin/district_manage.php
modules/User Admin/family_manage.php
modules/User Admin/role_manage.php
modules/User Admin/userFields.php
modules/User Admin/userSettings.php
src/Domain/User/DistrictGateway.php
src/Domain/User/FamilyGateway.php
src/Domain/User/RoleGateway.php
src/Domain/User/UserFieldGateway.php
src/Domain/User/UsernameFormatGateway.php

OOified:
- Manage Districts
- Manage Families
- Manage Roles
- Manage User Custom Fields
- User Settings, username format table

User Admin: table ooification

---

src/Forms/Input/MultiSelect.php

Applies and implements the ValidatableInterface in the MultiSelect class and adds an isRequired() method.

Forms: add isRequired option to MultiSelect

---

modules/Attendance/attendance_take_byPerson.php
modules/Attendance/attendance_take_byPerson_deleteProcess.php
modules/Attendance/attendance_take_byPerson_edit.php
modules/Attendance/attendance_take_byPerson_editProcess.php

Some dates were being passed in URL params as Y-m-d and not converting correctly.

Attendance: fix date values when editing Attendance by Person

---

modules/Timetable Admin/courseEnrolment_manage_byPerson_edit.php
modules/Timetable Admin/courseEnrolment_manage_class_edit.php
modules/Timetable Admin/report_classEnrolment_byRollGroup.php
src/Domain/Timetable/CourseEnrolmentGateway.php
src/Domain/Timetable/CourseGateway.php
src/Domain/User/UserGateway.php
src/Services/Format.php
src/Services/FormatResolver.php
src/Tables/Columns/CheckboxColumn.php

- OOifies the bulk-action forms in Course Enrolment by Class and Course Enrolment by Person. 
- Moves the Class Enrolment by Rollgroup query to the CourseEnrolmentGateway. 
- Adds comments to the FormatResolver trait & adds a keyValue method.

Timetable Admin: Course Enrolment bulk-action ooification

---

src/Domain/Finance/InvoiceGateway.php

Finance: fix students appearing multiple times in Manage Invoices

---

CHANGELOG.txt
modules/Timetable/moduleFunctions.php

Timetable: add special day name to the timetable for school closures

---

modules/Data Updater/data_family_manage.php
modules/Data Updater/data_finance_manage.php
modules/Data Updater/data_medical_manage.php
modules/Data Updater/data_personal_manage.php
src/Domain/DataUpdater/FamilyUpdateGateway.php
src/Domain/DataUpdater/FinanceUpdateGateway.php
src/Domain/DataUpdater/MedicalUpdateGateway.php
src/Domain/DataUpdater/PersonUpdateGateway.php

Data Updater: fix manage update pages to list current year only

---

src/Forms/Input/PhoneNumber.php
tests/acceptance.suite.yml
themes/Default/css/main.css

Tested in Firefox, Chrome & Safari.
_Edit: snuck in a tiny tweak to the acceptance config, which should help with Travis who keeps timing out during the installer test._

Forms: fixes visual alignment of phone number validation message

---

modules/Markbook/css/module.css
modules/Markbook/markbook_edit_data.php
modules/Markbook/markbook_view_allClassesAllData.php

A couple fixes found by our lovely "beta testers" in production.

Markbook: fix markbook column alignment and student target highlight

---

modules/Markbook/markbook_viewExportAllContents.php
modules/Markbook/markbook_viewExportContents.php
modules/Markbook/moduleFunctions.php

Adds a check for highest action and markbook access level based on that action. Adjusts the else-case for the getClass() function.

Markbook: add a check for markbook access to Export and Export All

---

modules/System Admin/notificationSettings.php

System Admin: add highlight for inactive rows to Notification Settings

---

modules/User Admin/user_manage_edit.php

User Admin: fix checkboxes for multiple Privacy or Student Agreement options

---

CHANGELOG.txt
modules/Messenger/groups_manage.php
src/Domain/Messenger/GroupGateway.php

**Bug Fix**
Brings consistency between Manage Groups and New Message
Locally for now, production test will follow merge.

Messenger: restricted Manage Groups view to display groups from the current school year only

---

CHANGELOG.txt
modules/Planner/units_edit.php

Planner: fix school year name on Edit Unit page

---

modules/Data Updater/data_medical.php
src/Domain/DataUpdater/MedicalUpdateGateway.php

Applies the bug-fix from #543 to the Medical Data Updater process.

Data Updater: fix medical conditions not pre-selecting existing data

---

CHANGELOG.txt
modules/Data Updater/data_family_manage.php
modules/Data Updater/data_family_manage_deleteProcess.php
modules/Data Updater/data_family_manage_edit.php
modules/Data Updater/data_finance_manage.php
modules/Data Updater/data_finance_manage_deleteProcess.php
modules/Data Updater/data_finance_manage_edit.php
modules/Data Updater/data_medical_manage.php
modules/Data Updater/data_medical_manage_deleteProcess.php
modules/Data Updater/data_medical_manage_edit.php
modules/Data Updater/data_personal_manage.php
modules/Data Updater/data_personal_manage_deleteProcess.php
modules/Data Updater/data_personal_manage_edit.php
src/Domain/School/SchoolYearGateway.php

School year navigation allows the users managing Data Updates to go back and access or approve updates in any year.

Data Updater: add school year navigation to Manage Updates

---

modules/Students/applicationForm_manage.php
src/Domain/Students/ApplicationFormGateway.php
src/Domain/User/FamilyGateway.php
src/Services/Format.php

The ooified table includes some extra filters to make managing application forms a bit easier, including a search filter for year group.
Also adds a truncate() method to the Format class for handling long strings in tables.

Students: Manage Applications table ooification

---

fullscreen.php
report.php

System: fix variable name typo with theme javascript files

---

likes.php

Refactor likes.php to separate business logic and display logic.
As part of the effort in addressing #608.
1. Unit test pass.
2. Open test site with the proper address to show likes.php content. It works normally.

System: update code style of likes.php

---

modules/Behaviour/behaviour_letters.php
modules/Behaviour/behaviour_manage.php
modules/Behaviour/behaviour_pattern.php
modules/Behaviour/behaviour_view.php
src/Domain/Behaviour/BehaviourGateway.php
src/Domain/Students/StudentGateway.php
src/Tables/Action.php

Four more tables ooified.
A couple other minor tweaks:
- Removed a small section of duplicate code from StudentGateway
- Added a setExternalURL method to the Action class (used in View Policy link)
- Set a default filter & sort order for Find Behaviour Patterns

Tables: Behaviour module table ooification 

---

modules/Behaviour/behaviour_view_details.php
modules/Behaviour/moduleFunctions.php
modules/Students/student_view_details.php
src/Domain/Behaviour/BehaviourGateway.php
src/Domain/DataSet.php
src/Domain/Students/StudentGateway.php
src/Tables/Renderer/PaginatedRenderer.php
src/Tables/Renderer/SimpleRenderer.php

OOified the table in the getBehaviourRecord() function, used in Behaviour > View Student Record and Students > View Student Profiles.
Also tweaked the PaginatedRenderer so that the hidePagination setting doesn't also hide the table's header actions.

Behaviour: View Student Record table ooification 

---

.gitignore
assets/css/core.css
assets/css/scss/bootstrap.scss
assets/css/scss/core.scss
composer.json
composer.lock
vendor/composer/installed.json

- Adds Bootstrap v4.1.3 as a dev dependency (included in `.gitignore`)
- Adds some comments to `.gitignore` to keep things tidy & readable
- Adds initial scss and css files to `assets/css`

System: add Bootstrap v4.1.3 via Composer (require-dev only)

---

fullscreen.php
functions.php
src/HtmlHelpers/Scripts.php
src/HtmlHelpers/StyleSheets.php

Refactor fullscreen.php to separate business logic and display logic.
As part of the effort in addressing #608.
1. Unit test pass.
2. Open a test site fullscreen.php address.

WIP: Refactor fullscreen.php

---

.travis.yml
fullscreen.php
index.php
resources/assets/js/common.js
src/View/AssetBundle.php
src/View/Page.php

* Improve Gibbon\View\AssetBundle and Gibbon\View\Page class.
* Refactor index.php with AssetBundle and Page.
* The target is to, in long term, rewrite the index page with Twig template.
* The intermediate target is to narrow down the variables to use in template.
* Test with local testing server setup.
* No error on my test. Please check if you find any problem with it.

WP: Further refactor index

---

modules/System Admin/moduleFunctions.php
modules/System Admin/updateProcess.php

System: clear the Twig template cache folder on update

---

modules/Attendance/attendance.php
modules/Attendance/css/module.css

**Refactor**
OOification of the 2 daily attendance table (by roll group, by course class) in attendance.php. Also refactor the breadcrumb and code style.
* Follow PSR-2 standard.
* OOification of table render code.
* Refactor of breadcrumb after #661.
* Tested on local development environment.
* Tested with Codeception acceptance tests.
**Before refactor**
**After refactor**

Attendance: OOification of Daily Attendance table

---

modules/Behaviour/behaviour_manage_editProcess.php
modules/Roll Groups/rollGroups.php
modules/School Admin/inSettings.php
modules/School Admin/rollGroup_manage.php
modules/Students/report_students_byRollGroup.php
src/Domain/RollGroups/RollGroupGateway.php
src/Domain/Students/MedicalGateway.php
src/Domain/Students/StudentGateway.php
src/Tables/DataTable.php
src/Tables/Renderer/SimpleRenderer.php

**Refactoring**
The script refactoring is 80% complete, but I am not sure on the Extended view, how to best to get the House and Medical information in. Also, the export to Excel is not working as some data is being output too early. Waiting for input from Sandra. I've left the old medical code as a comment block under the new table, for reference.
Ongoing refactoring work
Locally

Students: ooification of Students by Roll Group report

---

modules/Attendance/attendance.php
modules/Attendance/attendance_future_byPerson.php
modules/Attendance/attendance_studentSelfRegister.php
modules/Attendance/attendance_take_byCourseClass.php
modules/Attendance/attendance_take_byPerson.php
modules/Attendance/attendance_take_byPerson_delete.php
modules/Attendance/attendance_take_byPerson_edit.php
modules/Attendance/attendance_take_byRollGroup.php
modules/Attendance/report_courseClassesNotRegistered_byDate.php
modules/Attendance/report_graph_byType.php
modules/Attendance/report_rollGroupsNotRegistered_byDate.php
modules/Attendance/report_studentHistory.php
modules/Attendance/report_studentsNotOnsite_byDate.php
modules/Attendance/report_studentsNotPresent_byDate.php
modules/Attendance/report_summary_byDate.php

**Refactor**
See #696
* Locally
* Travis

Attendance: refactor breadcrumb

---

modules/Messenger/cannedResponse_manage.php
modules/Messenger/cannedResponse_manage_add.php
modules/Messenger/cannedResponse_manage_delete.php
modules/Messenger/cannedResponse_manage_edit.php
modules/Messenger/groups_manage.php
modules/Messenger/groups_manage_add.php
modules/Messenger/groups_manage_edit.php
modules/Messenger/messageWall_view.php
modules/Messenger/messenger_manage.php
modules/Messenger/messenger_manage_delete.php
modules/Messenger/messenger_manage_edit.php
modules/Messenger/messenger_manage_report.php
modules/Messenger/messenger_post.php
modules/Messenger/messenger_postQuickWall.php

**Refactor**
See #696
* Locally
* Travis

Messenger: refactor breadcrumbs

---

modules/Markbook/markbook_edit.php
modules/Markbook/markbook_edit_add.php
modules/Markbook/markbook_edit_addMulti.php
modules/Markbook/markbook_edit_copy.php
modules/Markbook/markbook_edit_data.php
modules/Markbook/markbook_edit_delete.php
modules/Markbook/markbook_edit_edit.php
modules/Markbook/markbook_edit_targets.php
modules/Markbook/markbook_view_allClassesAllData.php
modules/Markbook/markbook_view_myMarks.php
modules/Markbook/markbook_view_viewMyChildrensClasses.php
modules/Markbook/weighting_manage.php
modules/Markbook/weighting_manage_add.php
modules/Markbook/weighting_manage_delete.php
modules/Markbook/weighting_manage_edit.php

**Refactor**
* adapt the new `$page` global for breadcrumb.
* add missing copyright declaration to files that missed it.
* See #696
* Some files has missing copyright declaration.
* Locally
* Travis

Markbook: refactor breadcrumbs

---

modules/Behaviour/behaviour_letters.php
modules/Behaviour/behaviour_manage.php
modules/Behaviour/behaviour_manage_add.php
modules/Behaviour/behaviour_manage_addMulti.php
modules/Behaviour/behaviour_manage_delete.php
modules/Behaviour/behaviour_manage_edit.php
modules/Behaviour/behaviour_pattern.php
modules/Behaviour/behaviour_view.php
modules/Behaviour/behaviour_view_details.php

I finished this module, and started the module Crowd Assessment.
Description
refactored all breadcrumbs from Behaviour
Motivation and Context
See #696
How Has This Been Tested?
Locally
Travis

Behaviour - refactored all breadcrumbs

---

modules/Roll Groups/rollGroups.php
modules/Roll Groups/rollGroups_details.php

**Refactor**
See #696
* Locally
* Travis

Roll Group: refactor breadcrumbs

---

modules/Data Updater/data_family.php
modules/Data Updater/data_family_manage.php
modules/Data Updater/data_family_manage_delete.php
modules/Data Updater/data_family_manage_edit.php
modules/Data Updater/data_finance.php
modules/Data Updater/data_finance_manage.php
modules/Data Updater/data_finance_manage_delete.php
modules/Data Updater/data_finance_manage_edit.php
modules/Data Updater/data_medical.php
modules/Data Updater/data_medical_manage.php
modules/Data Updater/data_medical_manage_delete.php
modules/Data Updater/data_medical_manage_edit.php
modules/Data Updater/data_personal.php
modules/Data Updater/data_personal_manage.php
modules/Data Updater/data_personal_manage_delete.php
modules/Data Updater/data_personal_manage_edit.php
modules/Data Updater/data_updates.php
modules/Data Updater/report_family_dataUpdaterHistory.php
modules/Data Updater/report_student_dataUpdaterHistory.php

finished this module, and started the module Departments
Description
refactored all breadcrumbs from Data Updater
Motivation and Context
See #696
How Has This Been Tested?
Locally
Travis

Data Updater - refactored all breadcrumbs

---

modules/Rubrics/rubrics.php
modules/Rubrics/rubrics_add.php
modules/Rubrics/rubrics_delete.php
modules/Rubrics/rubrics_duplicate.php
modules/Rubrics/rubrics_edit.php
modules/Rubrics/rubrics_edit_editRowsColumns.php
modules/Rubrics/rubrics_view.php

**Refactor**
See #696
* Locally
* Travis

Rubrics: refactor breadcrumbs

---

modules/Attendance/report_summary_byDate.php

Add support to translation in filter options "Group by" 
**Context**
Attendancce: in file report_summary_byDate.php
Locally
Travis

Add support to translation

---

modules/Departments/department.php
modules/Departments/department_course.php
modules/Departments/department_course_class.php
modules/Departments/department_course_edit.php
modules/Departments/department_edit.php
modules/Departments/departments.php

Description
refactored all breadcrumbs from Departments
Motivation and Context
See #696
How Has This Been Tested?
Locally
Travis

Departments - refactored all breadcrumbs

---

modules/System Admin/alarm.php
modules/System Admin/displaySettings.php
modules/System Admin/i18n_manage.php
modules/System Admin/module_manage.php
modules/System Admin/module_manage_edit.php
modules/System Admin/module_manage_uninstall.php
modules/System Admin/module_manage_update.php
modules/System Admin/notificationSettings.php
modules/System Admin/notificationSettings_manage_edit.php
modules/System Admin/stringReplacement_manage.php
modules/System Admin/stringReplacement_manage_add.php
modules/System Admin/stringReplacement_manage_delete.php
modules/System Admin/stringReplacement_manage_edit.php
modules/System Admin/systemCheck.php
modules/System Admin/systemSettings.php
modules/System Admin/systemSettingsProcess.php
modules/System Admin/theme_manage.php
modules/System Admin/theme_manage_uninstall.php
modules/System Admin/thirdPartySettings.php
modules/System Admin/update.php

**Refactor**
See #696
* Locally
* Travis

System Admin: refactor breadcrumbs

---

modules/Staff/applicationForm.php
modules/Staff/applicationFormProcess.php
modules/Staff/applicationForm_jobOpenings_view.php
modules/Staff/applicationForm_manage.php
modules/Staff/applicationForm_manage_accept.php
modules/Staff/applicationForm_manage_delete.php
modules/Staff/applicationForm_manage_edit.php
modules/Staff/applicationForm_manage_reject.php
modules/Staff/jobOpenings_manage.php
modules/Staff/jobOpenings_manage_add.php
modules/Staff/jobOpenings_manage_delete.php
modules/Staff/jobOpenings_manage_edit.php
modules/Staff/staff_manage.php
modules/Staff/staff_manage_add.php
modules/Staff/staff_manage_delete.php
modules/Staff/staff_manage_edit.php
modules/Staff/staff_manage_edit_contract_add.php
modules/Staff/staff_manage_edit_contract_edit.php
modules/Staff/staff_manage_edit_facility_add.php
modules/Staff/staff_manage_edit_facility_delete.php
modules/Staff/staff_view.php
modules/Staff/staff_view_details.php

**Refactor**
See #696
* Locally
* Travis

Staff: refactor breadcrumbs

---

modules/Timetable/moduleFunctions.php
modules/Timetable/report_viewAvailableSpaces.php
modules/Timetable/report_viewAvailableTeachers.php
modules/Timetable/spaceBooking_manage.php
modules/Timetable/spaceBooking_manage_add.php
modules/Timetable/spaceBooking_manage_delete.php
modules/Timetable/spaceChange_manage.php
modules/Timetable/spaceChange_manage_add.php
modules/Timetable/spaceChange_manage_delete.php
modules/Timetable/studentEnrolment_manage.php
modules/Timetable/studentEnrolment_manage_edit.php
modules/Timetable/studentEnrolment_manage_edit_edit.php
modules/Timetable/tt.php
modules/Timetable/tt_master.php
modules/Timetable/tt_space.php
modules/Timetable/tt_space_view.php
modules/Timetable/tt_view.php

**Refactor**
See #696
* Locally
* Travis

Timetable: refactor breadcrumbs

---

modules/Activities/report_participants.php
modules/Students/report_privacy_student.php
modules/Students/report_rollGroupSummary.php
modules/Students/report_students_byHouse.php
modules/Students/report_transport_student.php
resources/templates/formats/familyAddresses.twig.html
resources/templates/formats/familyContacts.twig.html
src/Domain/School/HouseGateway.php
src/Domain/Students/StudentReportGateway.php
src/Domain/User/FamilyGateway.php
src/Services/CoreServiceProvider.php

Four more tables ooified:
- Students by House
- Student Transport
- Roll Group Summary
- Privacy Choices by Student
In working on these tables, the amount of inline copy-pasted html was getting clunky. I've created some simple templates for these sections where we need to include a block of contact details or addresses. This can give us a reusable, consistent format for these types of data.

Students: Ooification of student report tables

---

modules/Students/report_students_left.php
modules/Students/report_students_new.php
resources/templates/formats/familyAddresses.twig.html
resources/templates/formats/familyContacts.twig.html
src/Domain/Students/StudentReportGateway.php
src/Domain/User/FamilyGateway.php
src/Tables/Prefab/ReportTable.php

Another two tables done, making use of the added templates for family details.

Students: ooification of New Students and Left Students reports 

---

modules/Individual Needs/iep_view_myChildren.php
modules/Individual Needs/in_archive.php
modules/Individual Needs/in_edit.php
modules/Individual Needs/in_editProcess.php
modules/Individual Needs/in_summary.php
modules/Individual Needs/in_view.php

**Refactor**
See #696
* Locally
* Travis

Individual Needs: refactor breadcrumbs

---

modules/Formal Assessment/externalAssessment.php
modules/Formal Assessment/externalAssessment_details.php
modules/Formal Assessment/externalAssessment_manage_details_add.php
modules/Formal Assessment/externalAssessment_manage_details_delete.php
modules/Formal Assessment/externalAssessment_manage_details_edit.php
modules/Formal Assessment/externalAssessment_view.php
modules/Formal Assessment/import_internal_results.php
modules/Formal Assessment/import_results.php
modules/Formal Assessment/internalAssessment_manage.php
modules/Formal Assessment/internalAssessment_manage_add.php
modules/Formal Assessment/internalAssessment_manage_delete.php
modules/Formal Assessment/internalAssessment_manage_edit.php
modules/Formal Assessment/internalAssessment_view.php
modules/Formal Assessment/internalAssessment_write.php
modules/Formal Assessment/internalAssessment_write_data.php

**Refactor**
See #696
* Locally
* Travis

Formal Assessment: refactor breadcrumbs

---

index.php
likes.php
notifications.php
passwordReset.php
preferences.php
publicRegistration.php
src/View/Page.php

Updates the page to only automatically add the module entry point if the user is logged in, fixing an issue where the entry point was visible in student & staff application forms but not usable.
Also ooifies the last couple breadcrumbs in the system.

System: update breadcrumb module entry point & misc ooificiation

---

modules/Attendance/report_summary_byDate.php
modules/Attendance/report_summary_byDate_print.php
modules/System Admin/systemSettings.php

Add support for internationalization

Support for internationalization - Part I

---

modules/School Admin/activitySettings.php
modules/School Admin/dashboardSettings.php

Add support for internationalization

Fix internationalization

---

composer.json
composer.lock
vendor/composer/autoload_psr4.php
vendor/composer/autoload_static.php
vendor/composer/installed.json
vendor/symfony/yaml/.gitignore
vendor/symfony/yaml/CHANGELOG.md
vendor/symfony/yaml/Command/LintCommand.php
vendor/symfony/yaml/Dumper.php
vendor/symfony/yaml/Escaper.php
vendor/symfony/yaml/Exception/DumpException.php
vendor/symfony/yaml/Exception/ExceptionInterface.php
vendor/symfony/yaml/Exception/ParseException.php
vendor/symfony/yaml/Exception/RuntimeException.php
vendor/symfony/yaml/Inline.php
vendor/symfony/yaml/LICENSE
vendor/symfony/yaml/Parser.php
vendor/symfony/yaml/README.md
vendor/symfony/yaml/Tag/TaggedValue.php
vendor/symfony/yaml/Unescaper.php
vendor/symfony/yaml/Yaml.php
vendor/symfony/yaml/composer.json
vendor/symfony/yaml/phpunit.xml.dist

Adds `symfony/yaml ^3.2`, to be used with the importer classes for the core.

System: add Symfony/Yaml library via Composer

---

modules/Formal Assessment/moduleFunctions.php
modules/Markbook/markbook_view_viewMyChildrensClasses.php

Add support for internationalization and added new term "More info" in file moduleFunction.php - line 119

Add support translation in Markbook and Formal Assessment

---

CHANGELOG.txt
modules/Messenger/moduleFunctions.php

A fix, but nothing elegant, I've just copied your SQL and added the appropriate targets 😬 It tests out though.

Messenger: fixed missing Message Wall targets for Transport and Group

---

modules/Messenger/moduleFunctions.php

Added support for terms (Posted By) and (Shared via) in the module Messenger

Add terms (Posted By) and (Shared via) in the module Messenger

---

modules/Activities/activities_manage_edit.php

Fix - When I edit an activity: Warning in function sprintf on line 22 
Local
Travis

ActivitiesFix warning in function sprintf

---

.gitlab-ci.yml

* update composer installer's SHA hash check.

gitlab-ci: fix composer installation

---

modules/School Admin/rollGroup_manage_add.php
modules/School Admin/rollGroup_manage_edit.php
modules/User Admin/user_manage_userPhotoAjax.php
src/Forms/DatabaseFormFactory.php
src/Forms/FormFactory.php
src/Forms/Input/Person.php
themes/Default/css/main.css

- Adds a new Input/Person class
- Adds an ajax script for grabbing user photos
- Updates the DatabaseFormFactory to use the Person input
- Tweaks the Roll Group manage page to disable the photo (multiple selects in a row)

Forms: add a Person input type to display user photos on select 

---

modules/Markbook/markbook_view_allClassesAllData.php
modules/Markbook/src/MarkbookView.php
src/Domain/Markbook/MarkbookColumnGateway.php

- Fix ordering issues when there's multiple page
- Provide option to reset ordering
Please refer to issue #790 
Used in v17.0.00 production run
Please refer to issue #790

Markbook Column Ordering is not working properly #790

---

passwordReset.php
passwordResetProcess.php

Following up on #817 to add the template to other non-notification emails sent by Gibbon.

System: apply mail template to Password Reset email

---

modules/Planner/planner.php
modules/Planner/planner_add.php
modules/Planner/planner_bump.php
modules/Planner/planner_deadlines.php
modules/Planner/planner_duplicate.php
modules/Planner/planner_edit.php
modules/Planner/planner_view_full.php
modules/Planner/planner_view_full_post.php
modules/Planner/planner_view_full_submit_edit.php

Lesson Planner OOification, 40% Complete (outstanding: planner_bump.php, planner_add.php, planner_edit.php, planner_view_full.php)
At long last, one of the final two pieces of the form OOification work
Locally

Planner: Lesson Planner OOification, 40% complete

---

modules/Crowd Assessment/crowdAssess.php
modules/Students/applicationForm_manage_accept.php
modules/Students/applicationForm_manage_edit_print.php
modules/Timetable Admin/tt_import.php
modules/User Admin/user_manage_edit.php

Typo fixes in POEditor and v18

---

modules/Crowd Assessment/moduleFunctions.php
modules/Planner/moduleFunctions.php

Make the strings more readable for the translators and provide more flexibilities.

Applying the strings replacement syntax

---

modules/Planner/planner_edit.php
modules/Planner/planner_editProcess.php

OOification of Edit Lesson view, complete and working, except for Outcomes (almost there) and Smart Blocks (not yet started!)
Locally

Planner: Edit Lesson OOification 80% complete

---

functions.php
modules/Planner/src/Forms/PlannerFormFactory.php
modules/Planner/units_add.php
modules/Planner/units_addProcess.php

Final tweaks to OOification of the Unit Planner Add interface. Edit to follow shortly
The last action to be OOified in the forms thread. Yay!
Locally

Unit Planner Add OOification

---

cli/system_backgroundProcess.php
gibbon.php
src/Domain/System/LogGateway.php
src/Services/BackgroundProcess.php
src/Services/BackgroundProcessor.php

Occasionally we need to start long-running processes; for messenger, notifications, report generation, etc. This PR adds a `BackgroundProcessor` service and abstract `BackgroundProcess` base-class.
I have been using a similar set of classes in my own modules to start and monitor separate php processes, and since it's used for all the notifications in my staff absence and coverage feature, I've tidied up the classes for use in the core. It isn't intended to be a full-on queue manager or general-purpose task runner: it's specifically geared for speeding up page loads by executing long-running code in a separate php process.
How it works:
One could create a class called `MessageSenderProcess` which extends `BackgroundProcess` and call a method `startSendingMessages($arg1, $arg2, ...)` on it. …

System: add a BackgroundProcessor service

---

lib/jquery-tokeninput/styles/token-input-facebook.css
src/Forms/DatabaseFormFactory.php
src/Forms/Input/Time.php

A couple tweaks to the form classes. Primarily adds minimum and maximum methods to the Time input class, used to limit the available times client-side.

Forms: update Time input class, update DatabaseFormFactory

---

modules/Planner/units_add.php
modules/Planner/units_edit.php
modules/Planner/units_editProcess.php

Almost complete OOification of the Unit Planner Edit interface. Only one issue remains, which is the layout of the action icons (can we do it better than webLink?):
One of the final steps in the form OOification. Once this is cleaned up and merged, we can search for final forms that have been forgotten. There are definitely one or two more in the Unit Planner, and they might be complex.
Locally

Planner: Unit Planner Edit OOification

---

modules/Data Updater/data_updates.php

Ooified and more mobile friendly. Still a little squishy to get all links visible on mobile screens, but better than before.

Data Updater: ooified the My Data Updates page

---

modules/Finance/invoices_manage_add.php

Provide a brief summary of your changes in the Pull Request title.
Be sure to check out our contributor docs for more info about pull requests.
https://github.com/GibbonEdu/core/blob/master/docs/CONTRIBUTING.md#how-to-submit-a-pull-request
Please describe your changes in detail.
Why is this change suggested? Is there a problem it helps to solve?
If this PR fixes an open issue, please link to the issue here.
Please describe how you've tested your changes. Include details of 
your testing environment, and any tests you've run to see how your 
change affects other areas of the code.
If applicable, add screenshots to help illustrate your changes.

another typo pull

---

modules/Planner/units_duplicate.php
modules/Planner/units_duplicateProcess.php

- OOified form step2 in Module Planner file units_duplicate.php
- Removed (*) from fields readonly

Planner: OOified planner duplicate unit

---

cli/attendance_weeklySummaryEmail.php
modules/Attendance/report_graph_byType.php
modules/Attendance/report_summary_byDate.php
modules/Attendance/report_summary_byDate_print.php
src/Domain/Attendance/AttendanceLogPersonGateway.php

Building on the changes in #863, #867 and #884
- Refactors the Attendance Trends page to use the `Chart` class.
- Applies the `countClassAsSchool` setting in additional locations.

Attendance: apply countClassAsSchool setting to reports and CLI script

---

modules/Planner/units_edit_smartBlockify.php

Fix the term "Smark" to "Smart" in file "modules/Planner/units_edit_smartBlockify.php" and translation space
Local

Fix term smark to smart

---

CHANGELOG.txt
modules/Messenger/messenger_postProcess.php

Tweaks recipients for Applicants target in Messenger
Locally

Messenger: messages targeted to Applicants no longer to Waiting List

---

functions.php
modules/Activities/activities_manage.php
modules/Activities/activities_manage_add.php
modules/Activities/activities_manage_edit.php
modules/Activities/activities_manage_enrolment.php
modules/Activities/activities_view.php
modules/Activities/report_attendance.php
modules/School Admin/activitySettings.php
modules/System Admin/notificationSettings_manage_edit.php
modules/System Admin/stringReplacement_manage.php
modules/System Admin/stringReplacement_manage_edit.php

Improvements in support to translation, fixed the column name(activies_manage_add) and small optimizations (isset method)

Improvements in support to translation

---

modules/Activities/activities_view.php
modules/Activities/report_attendanceExport.php
modules/Activities/report_participants.php
modules/Attendance/report_summary_byDate.php
modules/Attendance/report_summary_byDate_print.php
modules/Library/library_manage_catalog.php
modules/Library/library_manage_catalog_fields_ajax.php
modules/Staff/staff_view_details.php
modules/System Admin/import_run.php
modules/User Admin/family_manage.php
modules/User Admin/role_manage.php

Support to translation some strings and applying pattern Gibbon in code (methods translatable, dateRangeReadable)

V18 support translation review01

---

modules/Activities/report_activityChoices_byRollGroup.php
modules/Activities/report_activityChoices_byStudent.php
modules/Activities/report_activitySpread_rollGroup.php
modules/School Admin/activitySettings.php
modules/School Admin/formalAssessmentSettings.php
modules/Students/student_view_details.php
modules/System Admin/module_manage_edit.php
modules/User Admin/userSettings.php

Support to translation some strings

Review strings translations v19

---

notifications.php
notificationsActionProcess.php
notificationsDeleteAllProcess.php
notificationsDeleteProcess.php

Working with Sandra to refactor session variables

System: Refactored session variables in notification scripts

---

passwordReset.php
passwordResetProcess.php
preferences.php
preferencesPasswordProcess.php
preferencesProcess.php

System: Refactored session variables in preferences and password reset

---

notifications.php

System: Refactored Notification Tables

---

publicRegistration.php
publicRegistrationProcess.php

System: Refactored session variables in public registration scripts

---

modules/Individual Needs/investigations_manage.php
modules/Individual Needs/investigations_manage_add.php
modules/Individual Needs/investigations_manage_addProcess.php
modules/Individual Needs/investigations_manage_delete.php
modules/Individual Needs/investigations_manage_edit.php
modules/Individual Needs/investigations_manage_editProcess.php
modules/Individual Needs/investigations_submit.php
modules/Individual Needs/investigations_submit_detail.php
modules/Individual Needs/investigations_submit_detailProcess.php
src/Domain/IndividualNeeds/INInvestigationContributionGateway.php
src/Domain/IndividualNeeds/INInvestigationGateway.php
src/Forms/Input/Checkbox.php
src/Forms/Input/Radio.php

Overall this functionality is looking great! 😃 I've made a few small tweaks:
- Applied the progress bar template to the Manage Investigations page
- Added instructional information to the Add Investigation page
- Tweaked the checkbox/radio layouts in Submit Contributions
- Updated some Gateway class methods, along with other code style tweaks and changes.

IN: minor visual and code tweaks for IN Investigations feature

---

CHANGEDB.php
CHANGELOG.txt
modules/Messenger/messenger_manage_edit.php
modules/Messenger/messenger_manage_editProcess.php
modules/Messenger/messenger_post.php
modules/Messenger/messenger_postProcess.php
modules/Messenger/messenger_postQuickWall.php
modules/Messenger/messenger_postQuickWallProcess.php
modules/Messenger/moduleFunctions.php

Allows users with Manage Messages_all to pin messages to the top of the message wall. These messages are highlighted in purple.
All messages are equal, but some are more equal than others.
Locally

Message Wall Pin

---

modules/Timetable/moduleFunctions.php

Make the timetable responsive
Local and travis

Simple adjustments to make the timetable responsive

---

CHANGELOG.txt
index_notification_ajax.php
index_notification_ajax_alarm.php
index_notification_ajax_alarm_tickUpdate.php
resources/templates/ui/alarmOverlay.twig.html
src/Domain/System/AlarmGateway.php

- Updated the Sound Alarm system to scale to mobile screens, and applied css rules to help it scroll better, and not randomly skip the scrollbar to the top of the page (a known ajax+repaint issue).
- Refactored the index_notification_ajax_alarm.php script to use a template.
- Refactored the index_notification_ajax_alarm_tickUpdate.php script to use json data, and only refresh once per list (not once per row). This part needed optimized for large schools.
- Added an AlarmGateway class
The mobile view needed improved, and applying the boy-scout-rule, I've tidied up the code along the way.
Locally and in production at TIS.
Mobile view:

System: refactored Sound Alarm system

---

modules/Formal Assessment/externalAssessment.php

Applying core defaults (DataTable and Gateway) to the externalAssessment file
Local and travis

Applying pattern in file externalAssessment

---

modules/Activities/activities_manage_edit.php
modules/Behaviour/behaviour_manage.php
modules/Behaviour/behaviour_pattern.php
modules/Departments/department_edit.php
modules/Finance/budgetCycles_manage.php
modules/Finance/budgets_manage.php
modules/Finance/expenseApprovers_manage.php
modules/Finance/feeCategories_manage.php
modules/Formal Assessment/externalAssessment_details.php
modules/Formal Assessment/externalAssessment_manage_details_edit.php
modules/Formal Assessment/internalAssessment_manage.php
modules/Formal Assessment/internalAssessment_write.php
modules/Formal Assessment/internalAssessment_write_data.php
modules/Individual Needs/in_archive.php
modules/Individual Needs/in_edit.php
modules/Individual Needs/in_summary.php
modules/Library/library_browse.php
modules/Library/library_lending.php
modules/Library/library_lending_item.php
modules/Library/library_lending_item_edit.php
modules/Library/library_lending_item_renew.php
modules/Library/library_manage_catalog.php
modules/Planner/resources_add_ajaxProcess.php
modules/School Admin/attendanceSettings.php
modules/School Admin/department_manage_edit.php
modules/System Admin/import_run.php
modules/System Admin/notificationSettings_manage_edit.php
modules/Timetable Admin/ttColumn_edit.php
modules/User Admin/role_manage_edit.php
modules/User Admin/user_manage_edit.php

Some terms to start working on version 20

Some terms to start working on version 20

---

modules/Messenger/messenger_post.php
modules/Planner/planner.php
modules/Planner/planner_add.php
modules/Planner/planner_edit.php
modules/Planner/planner_view_full.php
modules/Planner/units_add.php
modules/Planner/units_edit.php

translation support - some more terms
Local anda Travis

V20 multilanguage terms 2

---

modules/Activities/activities_manage_enrolment.php
modules/Finance/invoicees_manage.php
modules/Formal Assessment/internalAssessment_view.php
modules/Reports/templates_assets.php
modules/Staff/applicationForm.php
modules/Staff/applicationForm_manage_edit.php
modules/Students/applicationForm.php
modules/Students/applicationForm_manage_edit.php
modules/User Admin/user_manage_add.php
modules/User Admin/user_manage_password.php
notifications.php

- activies: add suport to column 'Timestamp' - Note: the term '{date} at {time}' was added at poeditor
- notifications, invoicees, templates: added support to column Source
- user_manage_password: applying pattern to check empty strings

Support translation v20

---

CHANGELOG.txt
modules/Reports/reporting_write.php
modules/Reports/reporting_write_byStudent.php
modules/Reports/src/Forms/CommentEditor.php
modules/Reports/templates/ui/reportingStudentHeader.twig.html
src/Domain/Students/StudentGateway.php

Some recently requested tweaks 😄 
- Add alerts to student details in Write Reports
- Add auto resize to comment text boxes in Write Reports
- Highlight student name as a clickable link

Reports: usability tweaks for Write Reports page

---

modules/Library/report_catalogSummary.php
modules/Library/report_viewOverdueItems.php
src/Domain/Library/LibraryReportGateway.php

Edit: added the Catalogue Summary report

Library: ooified View Overdue Items report

---

modules/Individual Needs/in_edit.php
modules/Planner/units_edit_copyForward.php

Motivation and Context
Hackathon
How Has This Been Tested?
Locally

Individual Needs Edit Student Details table OOification

---

modules/Planner/units_edit_copyForward.php

Planner: units_edit_copyForward.php Form OOification

---

modules/Behaviour/behaviour_view_details.php
modules/Finance/invoicees_manage_edit.php
modules/Formal Assessment/externalAssessment_details.php
modules/Formal Assessment/externalAssessment_manage_details_add.php
modules/Timetable Admin/tt_edit_day_edit_class.php
modules/Timetable/tt_view.php

The following files contain refactored tables using the createDetails DataTable object
**Behaviour:**
behaviour_view_details.php
**Finance:**
invoiceees_manage_edit.php
**Formal Assessment:**
externalAssessment_details.php
externalAssessment_manage_details_add.php
**Timetable Admin:**
tt_edit_day_edit_class.php
**Timetable:**
tt_view.php
Post-Hackathon
Locally

DataTable::createDetails refactoring.

---

modules/Library/library_manage_catalog.php
modules/Library/library_manage_catalog_delete.php
modules/Library/library_manage_catalog_deleteProcess.php
src/Domain/Library/LibraryGateway.php

- Using DataTable object instead on the Library module's Manage Catalog page.
- Added a new query to the LibraryGateway
- Null-coalesce added to the delete process for the Library Catalog. There's already an if there to check what that value is supposed to do.
- Delete process for the Library Catalog now no longer passes you back
to the same search filter. I think that's right for this? I could be wrong though.
I'm going to work on getting some PSR-2 formatter going on my environment but if you guys beat me, can you format this for me?

Library Manage Catalog

---

modules/Finance/budgets_manage_add.php
modules/Finance/invoicees_manage_edit.php
modules/Finance/invoices_manage.php
modules/Finance/invoices_manage_issue.php
modules/Finance/invoices_manage_print_print.php
modules/Finance/moduleFunctions.php
modules/Students/applicationForm_manage.php
modules/Timetable Admin/tt_edit_day_edit.php

- all files - translation support
- invoices_manage - added 'description' for student column
- invoices_manage_issue - fixed label for personName
add elements input hidden for keep the values and show with translation support

Review translation support

---

CHANGELOG.txt
modules/Messenger/messenger_manage.php
modules/Messenger/messenger_post.php
modules/Messenger/messenger_postPreProcess.php
modules/Messenger/messenger_postProcess.php
modules/Messenger/src/MessageProcess.php
src/Domain/Messenger/MessengerGateway.php

I had an idea for how to add background processing without refactoring the beast that is "messenger_postProcess.php" 😁 We will still want to refactor it someday, but... one change at a time.
This PR:
- Shortcuts the postProcess by adding an intermediate postPreProcess step.
- The new postPreProcess creates the gibbonMessenger record and starts a background process for sending the message.
- The MessageProcess class handles the sending of the message in the background by setting up an environment of variables exactly like a $_POST process, and then including the original postProcess script.
- Once complete, the MessageProcess sends a notification with the result of the message delivery.
This results in:
- Pressing submit on New Message is nearly instant.
- The Manage Messages page has a …

Messenger: add a background process for sending messages

---

modules/System Admin/moduleFunctions.php
modules/System Admin/theme_manage.php
modules/System Admin/theme_manageProcess.php
modules/System Admin/theme_manage_installProcess.php
modules/System Admin/theme_manage_uninstall.php
modules/System Admin/theme_manage_uninstallProcess.php
src/Domain/System/ThemeGateway.php

- ThemeGateway was created and the files associated with the themes were refactored
- function getThemeVersion is set deprecated, because it is not used
Local and travis

Theme OOification

---

modules/Staff/staff_manage_edit.php
src/Domain/Staff/StaffContractGateway.php
src/Domain/Staff/StaffGateway.php

All tables have been OOified and queries (all but one small one) have been moved to gateways in staff_manage_edit.php.
Hackathon
Locally

Staff: OOified tables and queries in staff_manage_edit

---

index_notification_ajax_alarm.php
index_notification_ajax_alarmConfirmProcess.php
index_notification_ajax_alarmProcess.php
index_notification_ajax_alarm_tickUpdate.php
modules/System Admin/alarm.php
modules/System Admin/alarmProcess.php
modules/System Admin/alarm_cancelProcess.php
resources/templates/ui/alarmOverlay.twig.html
src/Domain/System/AlarmGateway.php

OOification and refactoring using helper methods of the Gateway classes.
Local

Alarm - Refactoring and OOification

---

modules/Finance/feeCategories_manage.php
src/Domain/Finance/InvoiceGateway.php

OOifying feeCategories_manage using the InvoiceGateway and DataTables.
Notable changes:
- The category will display using the warning class if it is not an active one.
- The "This category cannot be edited/deleted" text will now be formatted based on the Format service's small formatting.
- A criteria filter has been added for "active" however this is supplemental and remains unused on this page.

OO: feeCategories_manage.php

---

modules/Attendance/attendance_future_byPerson.php
modules/Behaviour/behaviour_view.php
modules/Library/library_browse.php
modules/Library/library_lending.php
modules/Library/library_lending_item.php
modules/Library/library_lending_item_edit.php
modules/Library/library_lending_item_renew.php
modules/Library/library_lending_item_return.php
modules/Library/library_lending_item_signout.php
modules/Library/library_manage_catalog.php
modules/Library/library_manage_catalog_edit.php
modules/Library/report_catalogSummary.php
modules/Library/report_studentBorrowingRecord.php
modules/Messenger/messenger_manage_edit.php
modules/Staff/staff_manage_add.php
modules/Staff/staff_manage_edit.php
modules/System Admin/logs_view.php
modules/Timetable Admin/courseEnrolment_manage_class_edit.php
src/Domain/User/RoleGateway.php
src/Services/Format.php

- Final revision about translation support in v20
- This PR not contais the fixed bugs in (https://github.com/GibbonEdu/core/pull/1046/files)

Translation - Final revision

---

modules/Finance/expenseApprovers_manage.php
src/Domain/Finance/FinanceGateway.php

Removed flat HTML data tables and replaced them with DateTable objects instead, utilising Gateways to query.
- Now using name formatting per the name formatting service. There are two commits, the first one using formal names and the second using informal and reversed names per the old style.
Two things I would suggest we look into here:
- The description text. It is dependant on a couple of variables though I'm not sure it's really at the stage of needing a Twig template. It could be worthwhile looking to see if there's a way these strings could work better. I'm not sure there is one though.
- Potentially colouring the rows based on if that user has "Full budget access" if that is applicable or vice versa. Some extra instructional text could alert the user to that.

OO: expenseApprover_manage.php

---

src/Services/Format.php

In this PR, I've added a bold formatting service which allows changes to be made to "bold" text formatting without a codebase overhaul or a search/replace on `<b>` tags.
Also, Format.php is now PSR2 compliant.
On modules/Library/library_browse.php I added a piece of bold text using the old and proposed methods:
```
echo "<b>Testing</b>";
echo Format::bold('Testing');
```
This resulted in the below output due to placement:
I appreciate there may also be worries over PSR2 modifications in Format.php so I've included phpcs output below. I just ran the automatic fix script (phpcbf) to fix the ones which are checked. There's a few lines over the 120 character limit but I generally don't touch those.
```
imspeir@jimbo8098:/var/www/gibbon.local/src/Services$ …
```

Bold Formatting Service

---

modules/Timetable Admin/courseEnrolment_manage.php
modules/Timetable Admin/courseEnrolment_manage_class_edit.php
modules/Timetable Admin/courseEnrolment_manage_class_editProcessBulk.php
modules/Timetable Admin/courseEnrolment_manage_class_edit_addProcess.php
modules/Timetable Admin/courseEnrolment_manage_class_edit_delete.php
modules/Timetable Admin/courseEnrolment_manage_class_edit_deleteProcess.php

Missing Back to Search link in sub screens
Local

 Back to Search link

---

modules/Library/library_lending_item.php

Added Sign Out in library_lending_item.php header action
Local

Sign Out text is missing

---

src/Tables/Prefab/RollGroupTable.php

fixed link to print leads
Local

fixed link to print leads

---

modules/School Admin/fileExtensions_manage_add.php
modules/School Admin/fileExtensions_manage_edit.php

File extension

---

modules/Staff/applicationForm_manage.php
modules/Staff/applicationForm_manage_edit.php
modules/Staff/jobOpenings_manage.php
modules/Staff/jobOpenings_manage_add.php
modules/Staff/jobOpenings_manage_edit.php
modules/Staff/report_absences_summary.php
modules/Staff/src/Tables/AbsenceCalendar.php
modules/Staff/src/Tables/AbsenceFormats.php
modules/Staff/src/Tables/CoverageCalendar.php
modules/Staff/src/Tables/CoverageMiniCalendar.php
modules/Staff/staff_view_details.php

Staff translation support
Local

Staff translation support

---

modules/Activities/activities_attendance_sheet.php
modules/Activities/activities_attendance_sheetPrint.php
modules/Activities/activities_manage.php
modules/Activities/activities_my.php
modules/Activities/activities_my_full.php
modules/Activities/activities_paymentProcessBulk.php
modules/Activities/activities_view.php
modules/Activities/activities_view_full.php

Translation support and fixed parameter value of the return 

review - module activities

---

modules/Attendance/attendance_future_byPerson.php
modules/Attendance/report_studentsNotOnsite_byDate.php
modules/Attendance/report_studentsNotOnsite_byDate_print.php
modules/Attendance/report_studentsNotPresent_byDate.php
modules/Attendance/report_studentsNotPresent_byDate_print.php
modules/Attendance/report_summary_byDate.php
modules/Behaviour/behaviour_manage_add.php
modules/Data Updater/data_medical.php
modules/Data Updater/data_medical_manage.php
modules/Data Updater/data_personal.php
modules/Data Updater/data_personal_manage.php
modules/Finance/expenseRequest_manage_add.php
modules/Individual Needs/investigations_manage.php
modules/Individual Needs/investigations_manage_edit.php
modules/Markbook/markbook_view_myMarks.php
modules/Rubrics/moduleFunctions.php
modules/Rubrics/rubrics_add.php
modules/Students/medicalForm_manage_condition_add.php
modules/Students/medicalForm_manage_condition_edit.php
modules/Students/medicalForm_manage_edit.php
resources/templates/components/studentHistory.twig.html

Translation support for some strings and the htmlPrep function removed from names
Local

Translation support - review final v20

---

modules/Individual Needs/investigations_manage_edit.php
modules/Individual Needs/investigations_submit.php
modules/Individual Needs/investigations_submit_detail.php
src/Domain/IndividualNeeds/INInvestigationContributionGateway.php

- Fixed link to student profile (Added gibbonINInvestigation.gibbonPersonIDStudent in function queryContributionsByPerson)
-  translation support
In file investigations_submit.php the link Student uses teacher ID instead of student ID
Local

Fixed link to student profile and translation support

---

modules/Planner/outcomes.php
modules/Planner/outcomes_add.php
modules/Planner/planner_deadlines.php
modules/Students/student_view_details.php
modules/System Admin/update.php

Translation support in Planner module and remove comment in update.php
Review in Planner module
Local

Last adjusts - v20

---

CHANGEDB.php
CHANGELOG.txt
modules/Roll Groups/rollGroups.php
modules/Roll Groups/rollGroups_details.php
src/Domain/RollGroups/RollGroupGateway.php

Some schools wish to restrict parental roll group viewing to the groups in which parents have children. This PR implements this as a new grouped action.
Enhanced privacy in larger schools.
Locally

Roll Groups My Children

---

modules/Finance/invoicees_manage_edit.php

I spotted an issue where, if the GET params for search and allUsers was not set when hitting this form, the form would show a couple of error messages. This fix simply null-coalesces the GET parameters so that if they are not provided, it is assumed they are empty strings. 
Fixes #1058

Edit Invoicee Fix

---

modules/Finance/expenses_manage_view.php
src/Domain/Finance/ExpenseGateway.php

Adding DataTable in place of inline HTML table for the expense log. This particular page does have the possibility to be refactored with an inline table template but I don't want to change too much in one PR. Nevertheless, some small changes here:
- Complying with PSR2
- Formatting date using the Format service
- Actions column is no longer shown as it is not possible to have any actions showing.

OO: expense_manage_view.php Log Table

---

CHANGELOG.txt
modules/Students/applicationForm_manage_edit.php
modules/Students/applicationForm_manage_editProcess.php
modules/Students/applicationForm_manage_studentIDAjax.php
modules/User Admin/user_manage_add.php
modules/User Admin/user_manage_edit.php
modules/User Admin/user_manage_studentIDAjax.php
src/Forms/Input/TextField.php

- Adds front-end and back-end uniqueness checks to the Student ID field in the application form. Also adds the front-end check to the Manage Users page (back-end check was already in place).
- The application form uniqueness check compares existing students as well as other application forms.
- Tweaks the text on unique fields based on whether they're required or not.
Locally

Students: add uniqueness checks for Student ID field

---

modules/School Admin/department_manage_addProcess.php

Fixing an undefined variable in the query that broke the page.
Tested it using acceptance tests, was broken, so fixed it.
Acceptance testing as well as manual test
Fixes #1109

School Admin: Fixes undefined variable when creating department

---

functions.php
indexFindRedirect.php
index_tt_ajax.php
modules/Attendance/attendance_take_byCourseClassProcess.php
modules/Attendance/attendance_take_byRollGroupProcess.php
modules/Attendance/report_courseClassesNotRegistered_byDate.php
modules/Attendance/report_rollGroupsNotRegistered_byDate.php
modules/Attendance/report_studentsNotOnsite_byDate.php
modules/Attendance/report_studentsNotPresent_byDate.php
modules/Crowd Assessment/crowdAssess_view.php
modules/Messenger/messenger_manage_editProcess.php
modules/Messenger/messenger_manage_report.php
modules/Planner/planner_addProcess.php
modules/Planner/planner_editProcess.php
modules/Planner/planner_unitOverview.php
modules/Planner/planner_view_full.php
modules/Planner/planner_view_full_submitProcess.php
modules/Planner/resources_addQuick_ajax.php
modules/Roll Groups/rollGroups_details.php
modules/Students/applicationFormProcess.php
modules/Students/student_view_details_notes_add.php
modules/Students/student_view_details_notes_addProcess.php
modules/User Admin/user_manage_edit.php
preferencesPasswordProcess.php

This PR fixes a number of warnings, which helps to clean up the error log so the actual errors are more visible. Most warnings were fixes by a null coalesce or an empty() check.

System: fix various PHP Notices and Warnings

---

src/UI/Components/Header.php

Replacing session variables and adding null coalesce operators.
I am not sure about the isset() replacements but I did my best! :)

Replacing session variables and adding null coalesce operators

---

modules/Finance/billingSchedule_manage.php

There was a ```?>``` at the end of the file. I am assuming that can be deleted...

billingSchedule_manage.php: Replacing session variables

---

modules/Messenger/messenger_manage.php

messenger_manage.php: Replace session variables

---

modules/Timetable/studentEnrolment_manage.php
modules/Timetable/studentEnrolment_manage_edit.php
src/Domain/Timetable/CourseGateway.php

Ooification to match the Course Enrolment by Class page in Timetable Admin.
Hackathon
Locally

Timetable: ooify the Manage Student Enrolment action

---

modules/System Admin/templates/systemOverview.twig.html

Exchanged chars in System Overview template
Local

Exchanged chars in System Overview template

---

modules/Messenger/moduleFunctions.php

OOified table in getMessage function in moduleFunctions.php in Messenger module
Hackathon
Locally with Demo Data

Messenger: OOified module functions getMessage Table

---

modules/Planner/resources_manage.php

This PR OOifies the table in the resources_manage.php page of the planner module, however it does not yet use a gateway
Hacktoberfest
Locally

Planner: resources_manage.php OO table

---

modules/Messenger/cannedResponse_manage.php

OOified Table in cannedResponse_manage.php in Messenger module.
Hackathon
Locally with Demo Data.

Messenger: OOified cannedResponse manage Table

---

modules/Roll Groups/rollGroups_details.php

OOified Basic Information Table in rollGroups_details.php in Roll Groups
Hackathon
Locally with Demo Data.

Roll Groups: OOified roll groups details Basic Information Table

---

modules/User Admin/family_manage_edit.php

OOified tables in family_manage_edit.php in the User Admin module.
Gibbon Hackathon 
Locally with demo data

User Admin: OOified family manage edit

---

modules/Attendance/attendance_take_byCourseClassProcess.php
modules/Planner/moduleFunctions.php
modules/Planner/planner_view_full.php
modules/Planner/planner_view_full_myHomeworkProcess.php
resources/templates/ui/unitBlock.twig.html
src/Domain/Attendance/AttendanceLogCourseClassGateway.php
src/Domain/Attendance/AttendanceLogPersonGateway.php
src/Domain/Planner/PlannerEntryGateway.php
src/Domain/Timetable/CourseEnrolmentGateway.php
src/Forms/Layout/Grid.php
src/Forms/Layout/Heading.php
src/Tables/Action.php

This is the last piece of form ooification in the core 🎉  (ignoring a couple small forms in the timetable, which will be templatified).
This PR makes a couple visual tweaks to the lesson content section, so that the padding is not as squished. It ooifies the attendance sidebar, guest list, and homework submission forms. It also removed the previous front-end editing of smart blocks in favour of adding a link to the smart block section of the Edit Planner form.
Locally
Attendance:

Planner: final form ooification

---

CHANGELOG.txt
modules/System Admin/logs_view.php
modules/System Admin/logs_view_purge.php
modules/System Admin/logs_view_purgeProcess.php
src/Domain/System/LogGateway.php

Adds the ability to delete logs by type and before a specified cutoff date.
The logs can fill up in large schools.
Locally

System Admin: add a Purge Logs action to the View Logs page

---

CHANGEDB.php
CHANGELOG.txt
modules/Staff/staff_manage_add.php
modules/Staff/staff_manage_addProcess.php
modules/Staff/staff_manage_edit.php
modules/Staff/staff_manage_editProcess.php
modules/Staff/staff_view_details.php
resources/imports/staff.yml

Adds a First Aid Qualification field to the staff profile allow the title of the awarded qualification to be recorded.
Given the range of different first aid awards, it is useful to know which qualification an individual holds.
Locally.

Staff: added First Aid Qualification field

---

CHANGEDB.php
CHANGELOG.txt
functions.php
modules/School Admin/alertLevelSettings.php
modules/School Admin/alertLevelSettingsProcess.php
modules/Timetable Admin/tt_edit_day_add.php
modules/Timetable Admin/tt_edit_day_edit.php
modules/Timetable/moduleFunctions.php

Edited CHANGEDB to standardize database storage of colours and prepend leading hash sign to existing colours
Added colour picker functionality to Edit Timetable Day and Manage Alert Levels
Noticed an inconsistency with how colors were being stored in the database as a whole, wanted to fix it.
Many, many tests to ensure correct SQL syntax and database interactions, as well as correct appearance on screen in the interface.

Color updates

---

modules/Students/report_myStudentHistory.php

- Added Criteria instance and id to element dataTable in GridView
- Element dataTable needs a Criteria instance

Element dataTable needs a Criteria instance

---

modules/User Admin/user_manage_add.php

Translation support for the Primary Role field
Translation support 

addUser: translation support

---

src/Domain/Departments/DepartmentGateway.php

Adds a function to select the deparments that a given user is in, optionally allowing the role of the user to be specified.
The Trip Planner uses this to determine what departments a use is the Head/Coordinator of.
Locally in the Trip Planner.

Added selectDepartmentsByPerson method

---

modules/User Admin/family_manage_delete.php

Fixed a minor warning message in the familiy manage delete script.
Prevent "Undefined index" with null coalesce.
Simply stumble upon this minor issue in testing logs and wanted to fix it.
Locally and in CI environment.

User Admin: fix family manage delete

---

modules/Individual Needs/in_archiveProcess.php
modules/Individual Needs/in_editProcess.php
modules/Individual Needs/in_edit_assistant_deleteProcess.php

Refactoring Individual Needs module - adding null coalesce

Individual Needs: null coalesce refactoring

---

CHANGEDB.php
CHANGELOG.txt

Added South Sudan as a country option.

Adding South Sudan as country option

---

modules/Messenger/cannedResponse_manage_addProcess.php
modules/Messenger/cannedResponse_manage_deleteProcess.php
modules/Messenger/cannedResponse_manage_editProcess.php
modules/Messenger/groups_manage_addProcess.php
modules/Messenger/groups_manage_deleteProcess.php
modules/Messenger/groups_manage_editProcess.php
modules/Messenger/groups_manage_edit_deleteProcess.php
modules/Messenger/messenger_manage_deleteProcess.php
modules/Messenger/messenger_manage_editProcess.php
modules/Messenger/messenger_manage_report_processBulk.php
modules/Messenger/messenger_postQuickWallProcess.php

Adding null coalesce to Messenger module

Messenger - null coalesce

---

modules/System Admin/systemSettings.php
modules/System Admin/systemSettingsProcess.php
tests/config/support/Helper/Acceptance.php

Work-in-progress code for adding a file uploader to the logo section of System Settings

System Settings - adding file uploader for logo (WIP)

---

CHANGELOG.txt
modules/System Admin/systemSettings.php
modules/System Admin/systemSettingsProcess.php

WIP changes for adding file uploader for backgrounds

System Settings - background file uploader (WIP)

---

modules/Departments/departments.php

* Added Criteria instance and id to element dataTable in GridView
* Element dataTable needs a Criteria instance
 Local and Travis

fix GridView

---

modules/Library/library_lending_item_editProcess.php
modules/Library/library_lending_item_renewProcess.php
modules/Library/library_lending_item_returnProcess.php
modules/Library/library_lending_item_signoutProcess.php
modules/Library/library_manage_catalog_addProcess.php
modules/Library/library_manage_catalog_duplicateProcess.php
modules/Library/library_manage_catalog_editProcess.php

Refactoring Library module - adding null coalesce

Library: null coalesce refactoring

---

functions.php
login.php
modules/Activities/activities_manage_enrolment_addProcess.php
modules/Activities/activities_manage_enrolment_deleteProcess.php
modules/Activities/activities_manage_enrolment_editProcess.php
modules/Activities/activities_view_registerProcess.php
modules/Data Updater/data_personal_manage_editProcess.php
modules/Finance/invoices_manage_editProcess.php
modules/Finance/invoices_manage_processBulk.php
modules/Markbook/markbook_edit_dataProcess.php
modules/Messenger/messenger_postProcess.php
modules/Students/applicationForm_manage_deleteProcess.php
modules/Students/student_view_details_notes_editProcess.php
modules/System Admin/dataRetentionProcess.php
modules/User Admin/user_manage_editProcess.php

Rewrite all setLog calls to LogGateway::addLog
* Adapt the change from #1248 and 37185b3.
CI platform.

Rewrite all setLog calls to LogGateway::addLog

---

CHANGEDB.php
modules/Data Updater/data_personal.php
modules/Data Updater/data_personalProcess.php
modules/Data Updater/data_personal_manage_edit.php
modules/Data Updater/data_personal_manage_editProcess.php
modules/Reports/src/Sources/CustomFields.php
modules/Staff/applicationForm.php
modules/Staff/applicationFormProcess.php
modules/Staff/applicationForm_manage_edit.php
modules/Staff/applicationForm_manage_editProcess.php
modules/Staff/staff_view_details.php
modules/Students/applicationForm.php
modules/Students/applicationFormProcess.php
modules/Students/applicationForm_manage_edit.php
modules/Students/applicationForm_manage_editProcess.php
modules/Students/student_view_details.php
modules/User Admin/moduleFunctions.php
modules/User Admin/user_manage_edit.php
modules/User Admin/user_manage_editProcess.php
publicRegistration.php
publicRegistrationProcess.php
src/Domain/System/CustomFieldGateway.php
src/Forms/CustomFieldHandler.php
src/Tables/DataTable.php

Second piece of the custom fields changes (and another one to come). This step refactors and removes the getCustomFields function from User Admin and creates a CustomFieldHandler class. The handler class contains methods for adding custom fields to forms, updating/uploading custom field data in process pages, and displaying custom field data in details tables. This refactors several sections of copy-pasted code into reusable methods.
Locally
There are not too many visual changes in this PR, that comes next.

System: refactor the getCustomFields function into CustomFieldHandler class

---

CHANGEDB.php
CHANGELOG.txt

System - added Somali as language option in dropdown menus

System - added Somali as language option in dropdown menus

---

src/Domain/System/LogGateway.php

Added filter rules for filters previously provided by getLog function.
Locally with the Help Desk.

Added Filter Rules to LogGateway

---

modules/Rubrics/rubrics_addProcess.php
modules/Rubrics/rubrics_deleteProcess.php
modules/Rubrics/rubrics_duplicateProcess.php
modules/Rubrics/rubrics_editProcess.php
modules/Rubrics/rubrics_edit_deleteColumnProcess.php
modules/Rubrics/rubrics_edit_deleteRowProcess.php
modules/Rubrics/rubrics_edit_editCellProcess.php
modules/Rubrics/rubrics_edit_editRowsColumnsProcess.php

Refactoring - adding null coalesce to Rubrics module

Rubrics - refactoring, adding null coalesce

---

modules/Staff/applicationFormProcess.php
modules/Staff/applicationForm_manage_deleteProcess.php
modules/Staff/applicationForm_manage_editProcess.php
modules/Staff/applicationForm_manage_rejectProcess.php
modules/Staff/coverage_availability_addProcess.php
modules/Staff/coverage_view_acceptProcess.php
modules/Staff/jobOpenings_manage_addProcess.php
modules/Staff/jobOpenings_manage_deleteProcess.php
modules/Staff/jobOpenings_manage_editProcess.php
modules/Staff/staff_manageProcessBulk.php
modules/Staff/staff_manage_addProcess.php
modules/Staff/staff_manage_deleteProcess.php
modules/Staff/staff_manage_editProcess.php
modules/Staff/staff_manage_edit_contract_addProcess.php
modules/Staff/staff_manage_edit_contract_editProcess.php
modules/Staff/staff_manage_edit_facility_addProcess.php
modules/Staff/staff_manage_edit_facility_deleteProcess.php

Refactoring the Staff module, adding null coalesce where necessary

Staff - refactoring, adding null coalesce

---

modules/Staff/staff_view_details.php
modules/Students/report_rollGroupSummary.php
modules/Students/report_students_byRollGroup.php
modules/Students/student_view_details.php
src/Domain/Students/StudentReportGateway.php
src/Services/Format.php

- Created new function to return the full gender name with translation support
- Using the new function in student/staff view details and adjusting the reports to genders (others and unspecified)
Code Review

New function genderName and adjusting reports

---

themes/2021/css/main.css

Stop a blue border appearing around the tab when clicked. (It was driving me crazy!) :~{

Stop the blue border!

---

modules/Attendance/report_consecutiveAbsences.php
modules/Finance/invoicees_manage.php
modules/Finance/moduleFunctions.php
modules/Markbook/markbook_edit.php
modules/Staff/staff_view_details.php
modules/Students/student_view.php
modules/Students/student_view_details.php
modules/User Admin/role_manage_edit.php
modules/User Admin/user_manage_editProcess.php
src/Forms/Input/FileUpload.php

Review of translation support and some improvements
In user_manage_editProcess.php I applyed the same logic as the user_manage_addProcess.php for the gibbonSchoolYearIDClassOf field, because if It's empty, the record receives 000 and this generates an error.

Review of translation support and some improvements

---

modules/System Admin/alarmProcess.php
modules/System Admin/notificationSettings_manage_editProcess.php
modules/System Admin/notificationSettings_manage_listener_addProcess.php
modules/System Admin/notificationSettings_manage_listener_deleteProcess.php
modules/System Admin/stringReplacement_manage_addProcess.php
modules/System Admin/stringReplacement_manage_deleteProcess.php
modules/System Admin/stringReplacement_manage_editProcess.php
modules/System Admin/thirdPartySettingsProcess.php

System Admin - null coalesce refactoring

System Admin - null coalesce refactoring

---

modules/Timetable/spaceBooking_manage_addProcess.php
modules/Timetable/spaceBooking_manage_deleteProcess.php
modules/Timetable/spaceChange_manage_addProcess.php
modules/Timetable/spaceChange_manage_deleteProcess.php
modules/Timetable/studentEnrolment_manage_editProcessBulk.php
modules/Timetable/studentEnrolment_manage_edit_addProcess.php
modules/Timetable/studentEnrolment_manage_edit_editProcess.php

Timetable - null coalesce refactoring

Timetable - null coalesce refactoring

---

modules/User Admin/district_manage_addProcess.php
modules/User Admin/district_manage_deleteProcess.php
modules/User Admin/district_manage_editProcess.php
modules/User Admin/family_manage_addProcess.php
modules/User Admin/family_manage_deleteProcess.php
modules/User Admin/family_manage_editProcess.php
modules/User Admin/family_manage_edit_addAdultProcess.php
modules/User Admin/family_manage_edit_addChildProcess.php
modules/User Admin/family_manage_edit_deleteAdultProcess.php
modules/User Admin/family_manage_edit_deleteChildProcess.php
modules/User Admin/family_manage_edit_editAdultProcess.php
modules/User Admin/family_manage_edit_editChildProcess.php
modules/User Admin/family_manage_edit_relationshipsProcess.php
modules/User Admin/permission_manageProcess.php
modules/User Admin/role_manage_addProcess.php
modules/User Admin/role_manage_deleteProcess.php
modules/User Admin/role_manage_duplicateProcess.php
modules/User Admin/role_manage_editProcess.php
modules/User Admin/staffApplicationFormSettingsProcess.php
modules/User Admin/studentsSettings_noteCategory_addProcess.php
modules/User Admin/studentsSettings_noteCategory_deleteProcess.php
modules/User Admin/studentsSettings_noteCategory_editProcess.php
modules/User Admin/userSettingsProcess.php
modules/User Admin/userSettings_usernameFormat_addProcess.php
modules/User Admin/userSettings_usernameFormat_editProcess.php
modules/User Admin/user_manage_addProcess.php
modules/User Admin/user_manage_deleteProcess.php
modules/User Admin/user_manage_editProcess.php
modules/User Admin/user_manage_edit_photoDeleteProcess.php
modules/User Admin/user_manage_passwordProcess.php

User Admin - refactoring code to add null coalesce

User Admin - null coalesce refactoring

---

modules/Crowd Assessment/crowdAssess_view_discuss_post.php
modules/Crowd Assessment/crowdAssess_view_discuss_postProcess.php
modules/Crowd Assessment/moduleFunctions.php

Refactoring Crowd Assessment variable - fixing and updating session variables

Crowd Assessment - refactoring session variables

---

modules/Attendance/attendance.php
modules/Attendance/attendance_future_byPerson.php
modules/Attendance/attendance_future_byPersonDeleteProcess.php
modules/Attendance/attendance_future_byPersonProcess.php
modules/Attendance/attendance_studentSelfRegister.php
modules/Attendance/attendance_studentSelfRegisterProcess.php
modules/Attendance/attendance_take_byCourseClass.php
modules/Attendance/attendance_take_byCourseClassProcess.php
modules/Attendance/attendance_take_byFormGroup.php
modules/Attendance/attendance_take_byFormGroupProcess.php
modules/Attendance/attendance_take_byPerson.php
modules/Attendance/attendance_take_byPersonProcess.php
modules/Attendance/attendance_take_byPerson_delete.php
modules/Attendance/attendance_take_byPerson_deleteProcess.php
modules/Attendance/attendance_take_byPerson_edit.php
modules/Attendance/attendance_take_byPerson_editProcess.php
modules/Attendance/report_consecutiveAbsences.php
modules/Attendance/report_courseClassesNotRegistered_byDate.php
modules/Attendance/report_courseClassesNotRegistered_byDate_print.php
modules/Attendance/report_formGroupsNotRegistered_byDate.php
modules/Attendance/report_formGroupsNotRegistered_byDate_print.php
modules/Attendance/report_graph_byType.php
modules/Attendance/report_studentHistory.php
modules/Attendance/report_studentsNotInClass_byDate.php
modules/Attendance/report_studentsNotOnsite_byDate.php
modules/Attendance/report_studentsNotPresent_byDate.php
modules/Attendance/report_summary_byDate.php
modules/Attendance/report_summary_byDate_print.php

Attendance, refactoring to fix/update session variables - WIP

Attendance - session variable refactoring (WIP)

---

modules/Behaviour/behaviour_letters.php
modules/Behaviour/behaviour_manage.php
modules/Behaviour/behaviour_manage_add.php
modules/Behaviour/behaviour_manage_addMulti.php
modules/Behaviour/behaviour_manage_addMultiProcess.php
modules/Behaviour/behaviour_manage_addProcess.php
modules/Behaviour/behaviour_manage_delete.php
modules/Behaviour/behaviour_manage_deleteProcess.php
modules/Behaviour/behaviour_manage_edit.php
modules/Behaviour/behaviour_manage_editProcess.php
modules/Behaviour/behaviour_pattern.php
modules/Behaviour/behaviour_view.php
modules/Behaviour/behaviour_view_details.php
modules/Behaviour/moduleFunctions.php

Refactoring the Behaviour module to fix/update session variables

Behaviour - refactoring, fixing session variables

---

modules/Departments/department.php
modules/Departments/department_course.php
modules/Departments/department_course_class.php
modules/Departments/department_course_classExport.php
modules/Departments/department_course_edit.php
modules/Departments/department_course_editProcess.php
modules/Departments/department_edit.php
modules/Departments/department_editProcess.php
modules/Departments/department_edit_resource_deleteProcess.php
modules/Departments/departments.php

Refactoring Departments module to update session variables

Departments - session variable refactoring

---

modules/Individual Needs/iep_view_myChildren.php
modules/Individual Needs/in_archive.php
modules/Individual Needs/in_archiveProcess.php
modules/Individual Needs/in_edit.php
modules/Individual Needs/in_editProcess.php
modules/Individual Needs/in_edit_assistant_deleteProcess.php
modules/Individual Needs/in_summary.php
modules/Individual Needs/in_view.php
modules/Individual Needs/investigations_manage.php
modules/Individual Needs/investigations_manage_add.php
modules/Individual Needs/investigations_manage_addProcess.php
modules/Individual Needs/investigations_manage_deleteProcess.php
modules/Individual Needs/investigations_manage_edit.php
modules/Individual Needs/investigations_manage_editProcess.php
modules/Individual Needs/investigations_submit.php
modules/Individual Needs/investigations_submit_detail.php
modules/Individual Needs/investigations_submit_detailProcess.php
modules/Individual Needs/report_graph_overview.php

Refactoring session variables in Individual Needs module

Individual Needs - refactoring session variables

---

modules/Formal Assessment/externalAssessment.php
modules/Formal Assessment/externalAssessment_details.php
modules/Formal Assessment/externalAssessment_manage_details_add.php
modules/Formal Assessment/externalAssessment_manage_details_addProcess.php
modules/Formal Assessment/externalAssessment_manage_details_deleteProcess.php
modules/Formal Assessment/externalAssessment_manage_details_edit.php
modules/Formal Assessment/externalAssessment_manage_details_editProcess.php
modules/Formal Assessment/externalAssessment_manage_processBulk.php
modules/Formal Assessment/externalAssessment_view.php
modules/Formal Assessment/internalAssessment_manage_add.php
modules/Formal Assessment/internalAssessment_manage_addProcess.php
modules/Formal Assessment/internalAssessment_manage_deleteProcess.php
modules/Formal Assessment/internalAssessment_manage_edit.php
modules/Formal Assessment/internalAssessment_manage_editProcess.php
modules/Formal Assessment/internalAssessment_view.php
modules/Formal Assessment/internalAssessment_write.php
modules/Formal Assessment/internalAssessment_write_data.php
modules/Formal Assessment/internalAssessment_write_dataProcess.php
modules/Formal Assessment/internalAssessment_write_data_responseDeleteProcess.php

Refactoring session variables in Formal Assessment module

Formal Assessment - refactoring session variables

---

modules/Markbook/markbook_edit_add.php
modules/Markbook/markbook_edit_addMulti.php
modules/Markbook/markbook_edit_addMultiProcess.php
modules/Markbook/markbook_edit_addProcess.php
modules/Markbook/markbook_edit_copy.php
modules/Markbook/markbook_edit_copyProcess.php
modules/Markbook/markbook_edit_data.php
modules/Markbook/markbook_edit_dataProcess.php
modules/Markbook/markbook_edit_data_responseDeleteProcess.php
modules/Markbook/markbook_edit_delete.php
modules/Markbook/markbook_edit_deleteProcess.php
modules/Markbook/markbook_edit_edit.php
modules/Markbook/markbook_edit_editProcess.php
modules/Markbook/markbook_edit_targets.php
modules/Markbook/markbook_edit_targetsProcess.php
modules/Markbook/markbook_view.php
modules/Markbook/markbook_viewExport.php
modules/Markbook/markbook_viewExportAll.php
modules/Markbook/markbook_viewExportAllContents.php
modules/Markbook/markbook_viewExportContents.php
modules/Markbook/markbook_view_myMarks.php
modules/Markbook/markbook_view_rubric.php
modules/Markbook/markbook_view_viewMyChildrensClasses.php
modules/Markbook/weighting_manage_add.php
modules/Markbook/weighting_manage_addProcess.php
modules/Markbook/weighting_manage_copyProcess.php
modules/Markbook/weighting_manage_delete.php
modules/Markbook/weighting_manage_deleteProcess.php
modules/Markbook/weighting_manage_edit.php
modules/Markbook/weighting_manage_editProcess.php

Markbook: session variable refactoring

Markbook: session variable refactoring

---

modules/Form Groups/formGroups.php
modules/Form Groups/formGroups_details.php

Form Groups: session variable refactoring

Form Groups: session variable refactoring

---

modules/Rubrics/rubrics.php
modules/Rubrics/rubrics_add.php
modules/Rubrics/rubrics_addProcess.php
modules/Rubrics/rubrics_delete.php
modules/Rubrics/rubrics_deleteProcess.php
modules/Rubrics/rubrics_duplicate.php
modules/Rubrics/rubrics_duplicateProcess.php
modules/Rubrics/rubrics_edit.php
modules/Rubrics/rubrics_editProcess.php
modules/Rubrics/rubrics_edit_deleteColumnProcess.php
modules/Rubrics/rubrics_edit_deleteRowProcess.php
modules/Rubrics/rubrics_edit_editCellProcess.php
modules/Rubrics/rubrics_edit_editRowsColumns.php
modules/Rubrics/rubrics_edit_editRowsColumnsProcess.php
modules/Rubrics/rubrics_view.php

Session variable refactoring in the Rubrics module

Rubrics: session variable refactoring

---

modules/Staff/applicationForm.php
modules/Staff/applicationFormProcess.php
modules/Staff/applicationForm_manage_accept.php
modules/Staff/applicationForm_manage_edit.php
modules/Staff/applicationForm_manage_editProcess.php

Continues implementing the personal documents feature by adding them to the staff application form, so that any information entered automatically becomes a document and is attached to any user accounts when accepted.
Locally

Staff: implement personal documents in the Staff Application Form

---

CHANGEDB.php
CHANGELOG.txt
modules/Behaviour/behaviour_manage_add.php
modules/Behaviour/behaviour_manage_addMulti.php
modules/Behaviour/behaviour_manage_addMultiProcess.php
modules/Behaviour/behaviour_manage_addProcess.php
modules/Behaviour/behaviour_manage_edit.php
modules/Behaviour/behaviour_manage_editProcess.php
src/Forms/CustomFieldHandler.php

Finalizing the implementation of the custom fields feature.
Locally

Behaviour: implement custom fields

---

CHANGEDB.php
CHANGELOG.txt
modules/Crowd Assessment/crowdAssess_view_discuss_postProcess.php
modules/Finance/invoices_manage_addProcess.php
modules/Finance/invoices_manage_edit.php
modules/Finance/invoices_manage_editProcess.php
modules/Finance/moduleFunctions.php
modules/Library/library_lending_item_editProcess.php
modules/Library/library_lending_item_returnProcess.php
modules/Library/library_lending_item_signoutProcess.php
modules/Library/library_manage_catalog_addProcess.php
modules/Library/library_manage_catalog_editProcess.php
modules/Library/library_manage_catalog_fields_ajax.php
modules/Messenger/messenger_postProcess.php
modules/Planner/planner_duplicateProcess.php
modules/Planner/planner_editProcess.php
modules/Timetable Admin/course_manage_addProcess.php
modules/Timetable Admin/course_manage_editProcess.php
modules/Timetable Admin/tt_edit_day_edit_class_editProcess.php
preferencesProcess.php

This PR is part of the code cleanup we've been working on in v22. It attempts to find and fix any instances of blank ID fields (00000s) and blank dates (0000-00-00) that may have preexisted in the database or have been inadvertently introduced through the null coalesce changes. It includes both code changes to fix the underlying issues as well as database changes to cleanup existing records.
Code and database consistency.
Locally and on sanitized production data.

System: fixed blank IDs and blank date fields in the database

---

modules/Reports/src/Sources/ClassTeachers.php

Code cleanup - Removing the function name (last reference)

Removing the function name

---

modules/Students/student_view_details.php

Fixed two PHP notices that were appearing in the medical menu in the student profile

Student details fix

---

modules/Activities/moduleFunctions.php
modules/Activities/report_activityChoices_byFormGroup.php

Date range translation support and code cleanup

Activities - Translation support and code cleanup

---

modules/Departments/departments.php
modules/School Admin/department_manage_add.php

Pagination does not work - fixed
Translation support
styling the grid component

Departments - review simple

---

.github/workflows/release.yml

Remove i18n folder content from release bundle.
* That was the way release was done previously.
* Reduce the file size. Allow people to choose the language pack they needed.
Created a test build here with this in my fork:
https://github.com/yookoala/GibbonEduCore/releases/tag/v23.0.00-testbuild3

GitHub actions release update

---

src/Gibbon/Core.php

* Correctly describe with phpdocs of the variable Core::session.
* Improve developer experience.
* Tested with Intellephant + VSCode

Fix phpdoc for attribute $session.

---

src/UI/Dashboard/ParentDashboard.php
src/UI/Dashboard/StaffDashboard.php
src/UI/Dashboard/StudentDashboard.php

* Need to add backslash to the front of root classname in
namespace.
* Found some `PDOException` call without proper escaping. Could result in unhandled error.
* Locally.

Fix PDOException catches in module

---

modules/Departments/departments.php

Adding a link to the department logo

Link in department logo

---

src/Forms/FormFactory.php
src/Forms/FormFactoryInterface.php

* Improved phpdocs and typehint to froms
* Improve developer experience in working with forms.
* Locally in VSCode.
* In CI environment.

Improved phpdocs and typehint to froms

---

composer.json
composer.lock

* Remove "phpoffice/phpexcel" dependency.
* Upgrade "slim/slim" to "^4.0"
* Fix #1392.
* Locally

Fix Composer PSR-4 library warnings

---

modules/Activities/activities_attendanceProcess.php
modules/Activities/activities_manageProcessBulk.php
modules/Activities/activities_manage_addProcess.php
modules/Activities/activities_manage_deleteProcess.php
modules/Activities/activities_manage_enrolment_addProcess.php
modules/Activities/activities_manage_enrolment_editProcess.php

Further null coalesce work in Activities module

Activities - further null coalesce

---

src/Data/ImportType.php

* Class name is case sensitive but mistyped with small letter.
* Fix issue found by PHPStan
* Locally with PHPStan

System: fix typo in ImportType class

---

modules/Data Updater/data_familyProcess.php
modules/Data Updater/data_family_manage_deleteProcess.php
modules/Data Updater/data_family_manage_editProcess.php
modules/Data Updater/data_financeProcess.php
modules/Data Updater/data_finance_manage_deleteProcess.php
modules/Data Updater/data_finance_manage_editProcess.php
modules/Data Updater/data_medicalProcess.php
modules/Data Updater/data_medical_manage_deleteProcess.php
modules/Data Updater/data_medical_manage_editProcess.php
modules/Data Updater/data_personalProcess.php
modules/Data Updater/data_personal_manage_deleteProcess.php
modules/Data Updater/data_personal_manage_editProcess.php
modules/Data Updater/data_staffProcess.php
modules/Data Updater/data_staff_manage_deleteProcess.php
modules/Data Updater/data_staff_manage_editProcess.php
modules/Departments/department_course_editProcess.php
modules/Departments/department_editProcess.php
modules/Timetable/moduleFunctions.php

Second pass of null coalesce for Data Updater and Departments

Data Updater, Departments: null coalesce refactoring

---

modules/Formal Assessment/internalAssessment_manage_addProcess.php
modules/Formal Assessment/internalAssessment_manage_deleteProcess.php
modules/Individual Needs/in_archiveProcess.php
modules/Individual Needs/in_editProcess.php
modules/Library/library_lending_item_editProcess.php
modules/Library/library_lending_item_renewProcess.php
modules/Library/library_lending_item_returnProcess.php
modules/Library/library_lending_item_signoutProcess.php
modules/Library/library_manage_catalog_addProcess.php
modules/Library/library_manage_catalog_duplicateProcess.php
modules/Library/library_manage_catalog_editProcess.php
modules/Timetable/moduleFunctions.php

A few null coalesce tweaks for the Formal Assessment, Individual Needs and Library modules

Formal Assessment, Individual Needs, Library: null coalesce refactoring

---

CHANGELOG.txt
modules/School Admin/space_manage.php

School Admin: fixed phone numbers not formatting in Manage Facilities

School Admin: fixed phone numbers not formatting in Manage Facilities

---

src/Comms/EmailTemplateLoader.php

* fix Gibbon\Comms\EmailTemplateLoader compatibility with Twig\Loader\LoaderInterface.
* An issue found by PHPStan.

System: fix EmailTemplateLoader compatibility with LoaderInterface

---

src/Forms/CustomFieldHandler.php

* Add protected property $fileUploader.
* Properly do phpdocs for all the properties of CustomFieldHandler.
* Fix issue found by PHPStan
* Locally with PHPStan

System: improve phpdocs for CustomFieldHandler

---

modules/Planner/resources_view.php
src/Domain/Planner/ResourceGateway.php

Bog standard table refactor
Ongoing refactoring process
Locally

Resources View Table Refactor

---

src/Services/LoggerFactory.php

* Remove private property $settingGateway from LoggerFactory.
* It is not used anywhere in the class.

System: remove LoggerFactory::settingGateway

---

src/Domain/System/SettingGateway.php

* improve phpdocs of the methods and properties in SettingGateway.
* improve developer experience in IDE.

System: improve phpdocs for SettingGateway

---

src/Contracts/Database/Connection.php
src/Database/Connection.php

* Improve documentation to Gibbon\Contracts\Database\Connection
and Gibbon\Database\Connection.
* Improve developer experience on IDE.

System: improve documentation to Connection

---

src/Forms/Layout/WebLink.php
src/Tables/Action.php

* Add missing documentation to properties.
* Add missing property with phpdocs.
* Fix documentation error to existing method.
* Improve developer experience with IDE.
* Fix issue found by PHPStan.

Improve documentation of Action and WebLink

---

src/Domain/QueryableGateway.php
src/Domain/Traits/TableAware.php
src/Forms/Layout/Grid.php
src/Forms/Layout/Row.php
src/Forms/Layout/Table.php
src/Services/BackgroundProcessor.php
src/Services/Payment/Payment.php
src/Tables/Prefab/EnrolmentTable.php
src/UI/Dashboard/StaffDashboard.php

* Property document the properties in the classes.
* Add some undeclared (but used) properties as protected properties.
* Remove unused properties.
* Add abstract method to TableAware trait.
* Improve developer experience with IDE.

Improve phpdocs and declare missing property to classes

---

src/Services/Payment/Payment.php

* requestPayment is documented to return string. It should return
a string in any and all cases.
* improve phpdocs for IDE support.
* fixed a potential bug with the IDE type support.
* Fix issue found by PHPStan.
* Fix bug.
* Improve developer experience on IDE.

System: fix Payment::requestPayment

---

gibbon.sql
src/Database/Updater.php

* ~~Update `CHANGEDB.php` for session table changes. Replaced several older create table / add column lines to replace with a simple drop-table / create-table operation.~~
* Add several `error_log` to Updater class for improved debug.
* Revert previously `gibbonSession` table declaration in `gibbon.sql`.
* Fix current issue with session table updates in installation process.
CI Environment.

Debug installer issue with database update

---

CHANGELOG.txt
functions.php
modules/Attendance/attendance_take_byFormGroup.php
modules/Finance/expenseRequest_manage_reimburse.php
modules/Finance/expenseRequest_manage_view.php
modules/Finance/expenses_manage_approve.php
modules/Finance/expenses_manage_print.php
modules/Finance/expenses_manage_print_print.php
modules/Finance/expenses_manage_view.php
modules/Form Groups/formGroups_details.php
modules/Formal Assessment/externalAssessment_details.php
modules/Individual Needs/in_edit.php
modules/Markbook/markbook_view_myMarks.php
modules/Markbook/markbook_view_viewMyChildrensClasses.php
modules/Planner/outcomes.php
modules/Rubrics/src/Visualise.php
modules/Staff/applicationForm_manage_edit_print.php
modules/Students/applicationForm_manage_edit_print.php
modules/Students/student_view_details.php
modules/System Admin/moduleFunctions.php
modules/System Admin/systemSettings.php
modules/Timetable/tt_view.php
src/UI/Dashboard/ParentDashboard.php

Since v17 quite a few functions.php functions have been deprecated, and often entirely removed from the code base. This PR removes roughly 50% of these functions, including refactoring those final usages that do exist.
Ongoing refactoring, and a desire to reduce the size of functions.php
Locally

System: removed deprecated functions no longer used in core and additional modules

---

modules/Formal Assessment/externalAssessment_manage_details_add.php
modules/Individual Needs/in_edit.php
modules/Individual Needs/in_view.php
modules/Individual Needs/report_graph_overview.php

Adding null coalesce to interface files in Formal Assessment and Individual Needs modules

Formal Assessment, Individual Needs - null coalesce in interface

---

modules/Finance/expenseRequest_manage_view.php
modules/Finance/expenses_manage_approve.php
modules/Finance/expenses_manage_edit.php
modules/Finance/expenses_manage_print.php
modules/Finance/expenses_manage_print_print.php
modules/Finance/expenses_manage_view.php
modules/Finance/fees_manage.php
modules/Finance/invoices_manage.php
modules/Finance/invoices_manage_add.php
modules/Finance/invoices_manage_edit.php
modules/Finance/invoices_manage_issue.php

Refactoring interface files in Finance module to add null coalesce

Finance - null coalesce refactoring in interface files

---

modules/Data Updater/data_family.php
modules/Data Updater/data_family_manage.php
modules/Data Updater/data_family_manage_edit.php
modules/Data Updater/data_finance.php
modules/Data Updater/data_finance_manage.php
modules/Data Updater/data_finance_manage_edit.php
modules/Data Updater/data_medical.php
modules/Data Updater/data_medical_manage.php
modules/Data Updater/data_medical_manage_edit.php
modules/Data Updater/data_personal.php
modules/Data Updater/data_personal_manage.php
modules/Data Updater/data_personal_manage_edit.php
modules/Data Updater/data_staff_manage.php
modules/Data Updater/report_family_dataUpdaterHistory.php
modules/Data Updater/report_student_dataUpdaterHistory.php

Refactoring Data Updater interface pages to add null coalesce

Data Updater - null coalesce refactoring in interface pages

---

modules/Behaviour/behaviour_letters.php
modules/Behaviour/behaviour_manage.php
modules/Behaviour/behaviour_manage_add.php
modules/Behaviour/behaviour_pattern.php
modules/Behaviour/behaviour_view.php

Refactoring interface pages in Behaviour module to add null coalesce

Behaviour - null coalesce refactoring in interface pages

---

modules/Attendance/attendance_take_byCourseClass.php
modules/Attendance/attendance_take_byPerson.php
modules/Attendance/attendance_take_byPerson_delete.php
modules/Attendance/attendance_take_byPerson_edit.php

Refactoring interface files in Attendance module to add null coalesce

Attendance - null coalesce refactoring in interface files

---

modules/Activities/activities_paymentProcessBulk.php
modules/Activities/activities_view_register.php
modules/Activities/report_activityEnrollmentSummary.php
modules/Activities/report_activityType_formGroup.php
modules/Activities/report_attendance_byDate.php
modules/Activities/report_participants.php

Activities - null coalesce refactoring

---

modules/.gitignore

Module name updated from Roll Groups to Form Groups in .gitignore
Local ado Travis

Updated module name

---

src/Services/Format.php

Fixed parameter (student_view_details instead of staff_view_details)
Wrong parameter causes broken link 

Fixed parameter (student_view_details instead of staff_view_details)

---

modules/System Admin/activeSessions.php
src/Forms/Input/MultiSelect.php

Added translation support for sortable attributes to the multi-select and column Role Category
Before
After fixed

Added translation support for sortable attributes to the multi-select

---

resources/templates/components/listOptions.twig.html
src/Tables/View/PaginatedView.php

In template the variable "absoluteURL"  generates a broken link and in the PaginatedView the "view" parameter is not necessary
OptionsList component doesn't work (e.g Staff/staff_view.php and Students/student_view_details.php)

Component listOptions fixed

---

src/Forms/FormFactory.php

'LYD د.ل' => 'Libyan Dinar (د.ل)', 
added under currency list

Added Libyan Currency

---

modules/Timetable/moduleFunctions.php

Fixed calendars not persisting when timetable is changed.
Was requested by teacher because it can get annoying.
Locally

Timetable: Fixed calenders not persisting when timetable is changed

---

CHANGEDB.php
CHANGELOG.txt
gibbon.sql
modules/Reports/criteriaTypes_manage_add.php
modules/Reports/criteriaTypes_manage_addProcess.php
modules/Reports/criteriaTypes_manage_edit.php
modules/Reports/criteriaTypes_manage_editProcess.php
modules/Reports/reporting_write_byStudent.php
modules/Reports/src/Domain/ReportingAccessGateway.php

Added a default value option when creating Yes/No reporting criteria.
Was requested by teachers to help streamline report writing process for certain criteria. 
Locally.

Reports: Added default value for Yes/No criteria type

---

modules/Markbook/markbook_edit_add.php

Adding null coalesce to interface pages in Markbook module

Markbook - null coalesce in interface pages

---

modules/Library/library_browse.php
modules/Library/library_manage_catalog_fields_ajax.php
modules/Library/library_manage_catalog_idCheckAjax.php

Adding null coalesce to interface pages in Library module

Library - null coalesce in interface pages

---

modules/Messenger/groups_manage_editProcess.php
modules/Messenger/messenger_manage_delete.php
modules/Messenger/messenger_manage_edit.php
modules/Messenger/messenger_manage_report.php

Adding null coalesce to interface pages in Messenger module

Messenger - null coalesce in interface pages

---

modules/Students/report_students_new.php

Translation support for these terms has also been added in Poeditor (tag v23_review)

Added translation support

---

modules/Students/report_students_byFormGroup.php

- Fixed HTML appearing in Age column in header row on export
- Added translation support for the term "DOB"
Some HTML appearing in header row on export

Fixed HTML appearing in Age column in header row on export

---

CHANGEDB.php
CHANGELOG.txt
modules/System Admin/stringReplacement_manage_add.php
modules/System Admin/stringReplacement_manage_edit.php

Increase the length in the database and in the interface.
Sometimes there is a longer string that schools want to replace.
Locally.

System Admin: increase string translation length to 255

---

modules/Students/student_view_details.php
resources/templates/profile/family.twig.html

Added translation support in page Family (students and staffs)

Translation support

---

CHANGELOG.txt
modules/Finance/billingSchedule_manage.php
modules/Planner/outcomes.php
modules/Planner/planner.php
modules/Planner/resources_manage.php
modules/Planner/resources_view.php
src/Domain/Finance/BillingScheduleGateway.php
src/Domain/Planner/OutcomeGateway.php

printPagination in functions.php has been deprecated since v16. This removes the last two calls of this function by refactoring the tables they belong to. Next steps are to do the same for some additional modules, then this function can be removed in v25.
Keeping house.
Locally
Not worth the bytes.

Pagination Refactoring

---

modules/Markbook/src/MarkbookView.php

* Fix PDOException references: Missed the root namespace backslash.
* Replace obsoleted executeQuery calls in MarkbookView. Using select instead of deprecated executeQuery.
* Fix mistake in MarkbookView::error() created in previous refactoring.
* Remove obsoleted methods:
* Remove MarkbookView::filterByFormOptions().
* Remove MarkbookView::filterByQuery().
* Clean up several issues in the Markbook module.
* CI Environment.

Fix various Markbook issues

---

tests/unit/Forms/FormTest.php

* Remove, as much as possible, tests dependency on global variables setup of gibbon.php.
* Create own container instance setup for Form::create test.
* To clear unit tests dependencies on gibbon.php setup.
* Locally.

Test: refactor FormTest global variable dependencies

---

functions.php
modules/Finance/expenses_manage_approveProcess.php
src/Domain/System/NotificationGateway.php

* Mark archiveNotification() deprecated.
* Add NotificationGateway::archiveNotificationForPersonAction() that provdes the exact feature.
* Rewrite Finance module usage of archiveNotification() to NotificationGateway::archiveNotificationForPersonAction().
* Replace functions.php function with gateway implementation.
* Locally.

System: replace archiveNotification with gateway method

---

composer.lock
src/Auth/Adapter/DefaultAdapter.php
src/Auth/Adapter/MFAAdapter.php
src/Database/Updater.php
src/Forms/Builder/Fields/FieldGroupInterface.php
src/Forms/Builder/Fields/RequiredDocuments.php
src/Forms/Builder/FormBuilder.php
src/Forms/Builder/Process/CreateStudent.php
src/Forms/DatabaseFormFactory.php
src/Forms/Form.php
src/Gibbon/Core.php
src/Install/Config.php
src/Services/Payment/Payment.php

Fix various PHP level 0 issues
* Improve code quality and robustness 
* CI environment with phpstan.

Fix phpstan issues

---

.github/workflows/ci.yml
.gitignore

* Add twig compile cache to test artefact if test failed.
* Better folder structure for artefact export.
* Improve development experience.
* GitHub CI

GitHub CI: Improve debug experience with twig

---

tests/unit/Services/FormatTest.php

* Fix locale for testing environment. Fix issue when run locally.
* To fix issue when the unit tests are ran locally.
* Locally.

Services: improve FormatTest

---

modules/Library/library_browse.php

Category field changed to type
This page is the only place where the type field is displayed as category

Category field changed to type

---

modules/Library/js/module.js
modules/Library/library_manage_catalog_add.php
modules/Library/library_manage_catalog_edit.php

- Fixed error when displaying messages
- When you find the book, fill in the two ISBN fields (10 and 13)
Local

Fixed Get Book Data from Google and messages

---

functions.php
modules/Formal Assessment/internalAssessment_write_data.php
modules/Markbook/markbook_edit_data.php
modules/Planner/resources_addQuick_ajax.php
modules/Staff/applicationForm.php
modules/Staff/applicationForm_manage_edit.php
modules/Students/applicationForm.php
modules/User Admin/user_manage_add.php
modules/User Admin/user_manage_edit.php

* Change function signature to deprecate use of the $guid parameter.
* Add backward compatible $guid detection.
* Remove $guid from all getMaxUpload uses in core.
* Deprecate the use of $guid parameter 
* Locally
* CI Platform

Refactor: Deprecate getMaxUpload $guid parameter

---

modules/Behaviour/behaviour_manage_add.php
modules/Data Updater/data_family.php
modules/Data Updater/data_finance.php
modules/Data Updater/data_medical.php
modules/Data Updater/data_personal.php
modules/Finance/expenseRequest_manage_reimburse.php
modules/Finance/expenseRequest_manage_view.php
modules/Finance/expenses_manage_approve.php
modules/Finance/expenses_manage_edit.php
modules/Finance/expenses_manage_print.php
modules/Finance/expenses_manage_print_print.php
modules/Finance/expenses_manage_view.php
modules/Finance/invoices_view_print.php
modules/Messenger/groups_manage_edit_delete.php
modules/Messenger/messenger_manage_delete.php
modules/Messenger/messenger_manage_report.php
modules/Planner/units_delete.php
modules/Planner/units_dump.php
modules/Planner/units_duplicate.php
modules/Planner/units_edit.php
modules/Planner/units_edit_copyForward.php
modules/Rubrics/moduleFunctions.php
modules/Staff/staff_manage_edit.php
modules/Students/student_view_details_notes_edit.php
modules/Timetable Admin/tt_edit_day_edit_class_edit.php
modules/Timetable Admin/tt_edit_day_edit_class_exception_delete.php
modules/Timetable/spaceBooking_manage_delete.php
modules/Timetable/spaceChange_manage_delete.php
modules/User Admin/userSettings_usernameFormat_edit.php

Refactored  html errors to new syntax
locally

Refactored old html error messages to new syntax

---

CHANGELOG.txt
modules/Timetable/tt_space_view.php

Added basic information table to View Timetable by Facility and used the formGroups_details.php as an example for implementing the basic info table.
To provide users with the ability to check room capacity, phone number, room type, and projector availability.

Added basic information table to View Timetable by Facility.

---

src/Forms/FormFactory.php

"ราชอาณาจักรไทย" -> "ประเทศไทย"
Use the common form of the country name ("ประเทศไทย"/"Thailand"), not the full official ("ราชอาณาจักรไทย"/"Kingdom of Thailand").

[L10n] Update FormFactory.php: "ราชอาณาจักรไทย" -> "ประเทศไทย"

---

cli/attendance_dailyIncompleteEmail.php
cli/attendance_dailyIncompleteEmail_byClass.php
cli/attendance_weeklySummaryEmail.php
cli/behaviour_lettersNegative.php
cli/behaviour_lettersPositive.php
cli/library_overdueNotification.php
cli/userAdmin_removeStaleNotifications.php
modules/Behaviour/behaviour_manage_addMultiProcess.php
modules/Behaviour/behaviour_manage_addProcess.php
modules/Data Updater/data_personal_manage_editProcess.php
modules/Individual Needs/investigations_manage_addProcess.php
modules/Individual Needs/investigations_manage_editProcess.php
modules/Individual Needs/investigations_submit_detailProcess.php
modules/Messenger/src/MessageProcess.php
modules/Planner/planner_addProcess.php
modules/Planner/planner_editProcess.php
modules/Planner/planner_view_full_postProcess.php
modules/User Admin/user_manage_editProcess.php

Refactoring code for changing the notification object from manual to container.

System: Refactoring code to retrieve object from container

---

modules/System Admin/thirdPartySettings.php

Fixed the problem by which you can send an email without enabling the SMTP Email

thirdPartySettings: fixed the send email testing tool

---

CHANGEDB.php
CHANGELOG.txt
cli/staff_FirstAidExpiryNotification.php

Staff: Created a cli to send notification informing the names of the staff whose First Aid Qualification are due to expire within three months.

Staff: creating cli script for sending first aid expiry notifications

---

functions.php

* Reformat functions.php with VSCode formatter.
* To simplify PR of future contributors using VSCode (e.g. #1798).
* Locally.

Functions: reformatting functions.php

---

functions.php

System: Bug fix by adding null coalesce

---

CHANGELOG.txt
modules/Rubrics/rubrics_edit_editCellProcess.php

To allow user input HTML tags in Rubrics cells

Rubrics: allowed HTML in Rubrics cells

---

index_tt_ajax.php
modules/Activities/activities_attendance.php
modules/Activities/activities_view.php
modules/Activities/activities_view_full.php

Refactor activity error message

Activity error message refactoring

---

CHANGELOG.txt
src/UI/Components/Sidebar.php

incorrect translation(localization) of the items in Roles menu on the index/Sidebar

fix localization of Roles items in the sidebar

---

modules/Reports/src/Sources/YearGroupCriteria.php

Update YearGroupCriteria.php to support criteria categories

---

modules/Reports/src/Renderer/MpdfRenderer.php

Update MpdfRenderer.php to support A3 paper size
