GibbonEdu/core

- functions.php
One uses the address just like getModuleName, but returns the gibbonModuleID instead.
The other uses the name of the Module and returns the gibbonModuleID.
> Added 2 getModuleID functions.

- config-sample.php
- installer/install.php
- modules/System Admin/systemSettings.php
Currently evaluating Gibbon for a school in Saudi Arabia; rather delicious that I saw it a few days back (v9.X) but when I came around to downloading it, v10 with the Arabic translation had come out the day before: شكرا!!
Bit of a shame that Saudi Riyal wasn't available but simple enough to add in - that's if I've got it right!  It's worked so far during installation and initial testing but do let me know if I'm missing something important...
I've sneaked in a little typo-correction (x2) along the way.
> Add Saudi Riyal to list of selectable currencies

- modules/User Admin/user_manage_add.php
A quick bug fix: the Gender dropdown for Add User had F and M for the values of Other and Unspecified
> User - Gender Field Fix

- modules/Messenger/messenger_postProcess.php
- modules/Messenger/moduleFunctions.php
Hi Ross,
This pull request is strictly for after your holidays ;)
I discovered the getMessages() function was missing the necessary queries for Attendance target messages, so I added those. 
The looping for Students/Families just needed adjusted in a couple spots. The prepare() PDO function was altering the CSV list of student IDs, so I've embedded it directly in the query. It's safe because the IDs come from a previous query and the CSV list in built by the script (no user input).
Should be good to go. I don't have an SMS system so be sure to test that at some point.
Have a great summer!
> Messenger: Absentee Target Fix

- CHANGEDB.php
- modules/Markbook/markbook_edit.php
- modules/Markbook/markbook_edit_copy.php
- modules/Markbook/markbook_edit_copyProcess.php
- modules/Markbook/weighting_manage.php
- modules/Markbook/weighting_manage_copyProcess.php
Added two new tools to the markbook:
- Copy columns from one class to another. This helps with teachers who teach the same lessons across multiple classes or multiple semesters.
- Copy markbook weighting categories from one class to another. Same purpose.
Also fixed a bug with Manage Weightings_everything not having access when checking grouped actions (updated action precedence to fix the issue).
Tested locally and on our school's production system.
Thanks!
> Markbook Copy Tools

- modules/Timetable/moduleFunctions.php
If a Planner Entry is created twice it should no longer display an error on the timetable.
> Fixed Duplicate Planner Entry producing an Error.

- CHANGELOG.txt
- modules/Markbook/markbook_edit.php
- modules/Markbook/markbook_edit_add.php
- modules/Markbook/markbook_edit_copy.php
- modules/Markbook/markbook_edit_data.php
- modules/Markbook/markbook_edit_delete.php
- modules/Markbook/markbook_edit_edit.php
- modules/Markbook/markbook_edit_targets.php
- modules/Markbook/moduleFunctions.php
- modules/Markbook/weighting_manage.php
- modules/Markbook/weighting_manage_add.php
- modules/Markbook/weighting_manage_delete.php
- modules/Markbook/weighting_manage_edit.php
Added the class chooser to the markbook sidebar. It uses a basePage variable to determine where to send people to on submit, so if you're in the Edit area it stays in edit, if you're in Weightings it stays in that section, and certain pages like Add Column and Targets stay on the same page, making it easier to perform those tasks while switching between several courses.
> Markbook: Class Chooser in Sidebar

- functions.php
- index_fastFinder_ajax.php
- lib/jquery-tokeninput/styles/token-input-facebook.css
Fast Finder search now includes:
Action - Name
Student - Surname, Preferred Name, First Name, Student ID, Username, Roll Group
Staff - Surname, Preferred Name, Username
Course - Name, Name Short, Class Name Short
The results returned in brackets depend on the context, if a secondary search term was matched. Also removed the use of UNION queries in sql (which create temp tables).
> Fast Finder: Moved data to AJAX request

- functions.php
- index_fastFinder_ajax.php
- themes/Default/css/main.css
Note: A firstname that matches the search and is not the same as the preferred name will return the legal name with preferred name in "" (eg: Doe, John "Johnny"). This seemed to be a slightly more readable option than putting the firstname after the roll group.
Also increased the FF field size a bit.
> Fast Finder: Updated student token to always include roll group

- CHANGELOG.txt
- index_fastFinder_ajax.php
- lib/google/index.php
- login.php
- roleSwitcherProcess.php
- src/Gibbon/core.php
- src/Gibbon/session.php
The FF actions are translated & cached on login and role switch. This approach also includes string replacements which is a nice bonus (eg: our school uses Homeroom instead of Form Group, so it also handles this)
> System: added ability to search Fast Finder actions using current Gibbon language

- modules/Attendance/attendance_future_byPerson.php
- modules/Attendance/attendance_take_byCourseClass.php
- modules/Attendance/attendance_take_byPerson.php
- modules/Attendance/attendance_take_byPerson_edit.php
- modules/Attendance/attendance_take_byRollGroup.php
- modules/Attendance/report_graph_byType.php
- modules/Attendance/report_studentsNotOnsite_byDate.php
- modules/Attendance/report_studentsNotOnsite_byDate_print.php
- modules/Attendance/report_studentsNotPresent_byDate.php
- modules/Attendance/report_studentsNotPresent_byDate_print.php
- modules/Planner/planner_view_full.php
Standardized the require_once to all use absolute paths so there's no conflicts. For whatever reason PHP sees absolute and relative includes as separate files.
One day I'll go through and figure out the Autoloader for module use, which is meant to handle including classes.
> Attendance: require_once path fix

- src/Gibbon/core.php
Looks like although type-hinting is supported back to 5.5, string types are only supported in PHP 7.0. Discovered this when MAMP PHP 5.5 started silently failing to render without even giving an error message :P
> System: Removed string type-hinting to fix php 5.5 compatibility

- passwordResetProcess.php
Discovered passwordResetProcess was still using the old mail() class (& failing to send on our system). Updated it to use PHPMailer so it's SMTP compatible. Also did a search over the project, looks like this was the last page still using the mail() class.
Thanks!
> System: Updated password reset process to use PHPMailer

- modules/School Admin/schoolYearSpecialDay_manage.php
- modules/School Admin/schoolYearSpecialDay_manage_addProcess.php
- modules/School Admin/schoolYearSpecialDay_manage_edit.php
- modules/School Admin/schoolYearSpecialDay_manage_editProcess.php
Fixes:
- Updated the term query to grab special dates by date range rather than term ID: If a special day is tied to a term that is changed or deleted, it still shows up if it falls in any valid term (prevents the Input Invalid error)
- Editing a special day will update it to the appropriate term ID (adopting the orphans)
- Allows for overlapping terms without breaking things: the dates are still unique, but can show up within different date-ranges for various terms
> School Admin: Fix orphaned Special Days casing Input Invalid error

- lib/google/index.php
- login.php
Discovered a bug in the Google login. The code intends to create an error and cancel login if two accounts have the same email address, but it actually continued and completed login but failed to set a lot of vital session vars. The result was a user who could login but nothing seemed to work right for them.
Adding a hard `exit;` after the header fixed this. It seems setting the header() doesn't terminate the script, so any time header is used as a redirect it should be followed by exit to ensure no code continues to run. I've added these in the google login and regular login script, and can do a more thorough header find/update for v14.
> System: Fixed Google Login error when accounts have the same email

- CHANGELOG.txt
- functions.php
- login.php
Updated the Login functionality to allow a user to login with either a username or valid email address (as long as the email address is unique). 
Changes the Login field to use icons for Username and Password (because the field needed a bit more room to accommodate email addresses).
Also provides a more specific error message if a user's canLogin='N' ("You do not have sufficient privileges to login.") rather than the initial error ("Incorrect username and password.")
> System: Allow users to login with username or email address

- modules/Markbook/css/module.css
- modules/Markbook/markbook_view_allClassesAllData.php
This PR adds a row to the bottom of the Markbook View, which gives a class-wide average for an individual assignment or cumulative grade. In the Markbook, this is perpendicular to the previous student averages added in v12.
Only visible if Markbook setting enableColumnWeighting is on.
> Markbook: Add a class average row to the bottom of markbook views

- modules/Markbook/src/markbookView.php
Identified and fixed a calculation error that affected weighted cumulative totals in courses that spanned more than one term. Specifically, the overall weightings for each type were being calculated per term rather than on the set as a whole, resulting in them being weighted more than once.
My initial data set when writing the calculation must not have been complex enough to catch this one. The fix is live on our system now (and verified by calculator). Worth posting to the forum, for anyone who uses the v12+ markbook with weightings turned on?
(PS: Add w=1 to the URL, the changes aren't as big as it's implying, it's picking up on whitespaces)
> Markbook: Cumulative calculation fix for courses over multiple terms

- modules/Students/applicationFormProcess.php
If cookies are disabled in a user's browser the session variables like $_SESSION[$guid]['absolutePath'] are missing so the file uploads were silently failing.
This fix does two things: loads the system settings into $_SESSION if they don't exist, and does one more attempt at uploading using the base Gibbon path if the first attempt fails.
> Students: Fixed file uploads failing in applicationFormProcess

- modules/Timetable/moduleFunctions.php
Added a check for 'View Master Timetable' permission to allow loading a timetable without needing to be directly involved in it. Fixes the issue of the TT disappearing once any navigation links are clicked (Timetable names, Next/Last Week).
> Timetable: Fixed TT not navigable if user isn't involved in any TT

- CHANGEDB.php
- CHANGELOG.txt
Merged in Victor's language changes and added a couple requested ones from this end:
- Adds a unique key to gibbonLanguage (`INSERT IGNORE` and `DUPLICATE KEY` don't work otherwise)
- Adds Myanmar, Burmese, Filipino to gibbonLanguage
- Updates Croatian, Ukrainian, Swedish spelling in gibbonLanguage
- Updates iddCountryCode for Myanmar
> System: added Myanmar, Burmese, Filipino to list of languages

- src/Gibbon/locale.php
Here's a super tiny PR that ensures the default timezone is always set. Currently it's done by a copy-pasted line at the top of _most_ but not all files, which can cause inconsistency in dates and raises PHP warning messages in systems with display errors enabled.
Also helps address a warning-message related error from this forum thread: https://ask.gibbonedu.org/discussion/comment/2732/#Comment_2732
> System: Added date_default_timezone_set to Locale class constructor

- src/Comms/GibbonMailer.php
- tests/acceptance/System Admin/SystemSettingsCept.php
Automated testing caught an autoloader conflict between the regular Mailer and the OOified one used for NotificationEvents. Fixed (and snuck another test-related update into the PR)
> System: Fixed GibbonMailer bug related to PHPMailerAutoload

- modules/Timetable Admin/tt_addProcess.php
- modules/Timetable Admin/tt_editProcess.php
The add/edit timetable was checking uniqueness against the session school year vs. the target school year, which prevented adding timetables to upcoming years with the same name as the current year.
> Timetable Admin: Fixed school year uniqueness check for add/edit TT

- CHANGELOG.txt
- lib/google/index.php
Found a redirect-loop in the google login script and patched up a few other issues along the way:
- An account with too many failed logins was creating a redirect loop rather than giving an error message
- An account with canLogin set to N was causing a blank page rather than an error message
- An account with a non-unique email could cause a PHP error and fail to redirect back to index
- The old style password reset wasn't working; fixed to send user to the password reset page after login
- Failed login notifications were using the old mail() function (and not sending for our system); replaced with Notification Event
> System: Google login fixes

- CHANGELOG.txt
- src/Gibbon/sqlConnection.php
Allows users to add $databasePort to their config file to specify a MySQL port number. Due to a PDO limitation, the port is only recognized when using `127.0.0.1` instead of localhost, or when using a specific hostname.
> System: Added ability to set mysql port through config.php

- src/Comms/NotificationSender.php
A small but important fix, the NotificationSender was accidentally adding sequential recipients to the same email as a To: address, vs a new email for each
> System: Fixed NotificationSender to create a new object for each email

- cli/attendance_dailyIncompleteEmail.php
- cli/behaviour_dailySummaryEmail.php
- cli/behaviour_letters.php
- cli/library_overdueNotification.php
- cli/planner_parentWeeklyEmailSummary.php
- cli/userAdmin_statusCheckAndFix.php
- functions.php
Adds additional checks to help with systems running PHP cron tasks as cgi/fcgi. The checks are currently limited only to systems returning cgi from php_sapi_name(), to help ensure the cli scripts aren't potentially opened up to any unwanted access.
> System: Added function for checking CLI access, updated CLI scripts

- modules/Attendance/attendance_take_byCourseClass.php
- modules/Attendance/attendance_take_byPerson.php
- modules/Attendance/attendance_take_byRollGroup.php
The take attendance pages currently check the enrolment for a student based on their start and end dates using the current date. This can cause the class lists to appear incorrect when taking attendance for a date in the past when a student has joined the class after that day. This PR updates the roll group/class queries to use the date entered rather than current date, which reflects the enrolment at that point in time.
> Attendance: Updated date used to check enrolment for Take Attendance

- modules/User Admin/family_manage_edit_addAdultProcess.php
- modules/User Admin/family_manage_edit_deleteAdultProcess.php
- modules/User Admin/family_manage_edit_editAdultProcess.php
PR to help address the contact priority issue from the forums: https://ask.gibbonedu.org/discussion/comment/2348#Comment_2348
Helps preserve one each for CP 1 and 2:
- When adding a CP 1, it bumps other CP 1 to 2, and 2 to 3s
- When adding a CP 2, it bumps the 2 to 3
- When deleting a CP 1, it bumps the 2 up to a 1 (but won't ever bump a 3 up)
I think this should help with the issue. The other thing the Query likely needs is a Group By on gibbonPersonID to handle any duplication from multiple CP 3s.
> User Admin: Adjusted handling of Family Adult contact priorities

- src/Forms/Input/Input.php
- src/Forms/Layout/Column.php
- src/Forms/Layout/Table.php
The checkbox required a different LiveValidation function. The missing text area validation in the application was related to being nested in a column, which needed a Validatable interface.
> Form Class: Fixed LiveValidation for checkbox, column and table elements

- CHANGELOG.txt
- modules/Planner/units_editProcess.php
- modules/Staff/applicationFormProcess.php
- modules/Students/applicationFormProcess.php
- publicRegistrationProcess.php
- src/Data/Validator.php
Created a basic Validator class with a sanitize() method (for v14). The sanitization itself is fairly straight forward: removes HTML tags and a small set of known control characters (borrowed from wp_kses sanitization). 
The other methods in the class are there to handle sanitizing HTML fields. The sanitize() method accepts an optional string in tinymce or strip_tags format, which works with the existing allowableHTML setting. If the libxml extension is installed (which is generally on by default) it will sanitize the HTML attributes as well as the tags. 
Also added the sanitization to Unit Edit as an HTML example.
> System: Added a validation class and implemented on public forms

- modules/Students/student_view_details.php
Formal Assessment and Markbook each have a function called sidebarExtra in moduleFunctions.php. In the Student Profile these both get included and were causing a global namespace conflict.
> Students: Moved markbook file include to fix namespace conflict

- modules/School Admin/daysOfWeek_manage.php
- modules/School Admin/daysOfWeek_manageProcess.php
- Updates Manage Days of Week to set the time fields to be required when a day is active. 
- Adds some logic to the process page to ensure times aren't null for an active day. 
- Changed error3 to warning1 because the loop saves data as it goes, so it's only a partial failure.
- Relaxed the field for Minutes a little so it defaults to 00 if unselected vs. generating an error.
This fixes the source of the problem for line 97. Let me know if you think the timetable function should also check & ensure it's not receiving null values.
> School Admin: Fixed Days of Week to prevent unset times for active days

- CHANGELOG.txt
- modules/Attendance/attendance_take_byCourseClass.php
- modules/Attendance/attendance_take_byRollGroup.php
PR to fix attendance issue from release prep line 16:
- Pre-filled attendance will always show the most recent attendance status (except class attendance)
- Class attendance will pre-fill attendance logs from other contexts, but will no longer pre-fill from another class
- When pre-fill settings are disabled the Take Attendance pages will only show the most recent attendance status for the same context
> Attendance: Updated pre-fill logic for Attendance by Roll Group/Class

- modules/Students/applicationForm.php
- src/Forms/Input/Input.php
- src/Forms/Input/Radio.php
- themes/Default/css/main.css
PR for release prep issue, line 204:
- It would seem LiveValidation doesn't support radio elements, so the isRequired on the gibbonFamilyID radio caused the whole LV for the form to break
- Removed isRequired from the application radio element, updated the Form Class handling of validation for the radio element
- Added an extra check to ensure blank element IDs can't make it into the LiveValidation for a form
> Students: Fixed application form failing for logged in parents

- modules/Messenger/messenger_post.php
- modules/Planner/units_dump.php
- modules/User Admin/permission_manage.php
- themes/Default/css/main.css
Some random things noticed during release prep:
- Accidentally turned on/off the wrong permission a few times (it can be hard to visually scan across the table when there's a fair number of roles.) Added a row highlight on hover to help indicate which permission is being changed.
- Unit Dump appeared to be ignoring resources added that were added to a unit: updated it to also include the Unit Outline when collecting/displaying resources.
- Messenger target for Courses was showing duplicate course names (I think FF automatically removes non-unique option values in a select list, but Chrome doesn't appear to)
> System: Minor fixes for usability 

- CHANGELOG.txt
- modules/Activities/report_activitySpread_rollGroup.php
- modules/Data Updater/data_personal.php
- modules/Finance/expenseRequest_manage_add.php
- modules/Finance/expenseRequest_manage_view.php
- modules/Finance/expenses_manage_approve.php
- modules/Finance/expenses_manage_edit.php
- modules/Planner/planner_deadlines.php
Testing continues, clearing out some more notices.
In expenseRequest_manage_add.php, the hidden gibbonFinanceInvoiceID appears to be vestigial (no variables to set it, and not used by the process page), took it out to fix a PHP notice.
(Some whitespace changes snuck in, ?w=1 to ignore them)
> System: Fixes for PHP notices

- modules/Activities/activities_attendance_sheetPrint.php
- modules/Attendance/attendance.php
- modules/Attendance/attendance_future_byPerson.php
- modules/Attendance/attendance_future_byPersonProcess.php
- PR #263 fixed the checkmark on View Daily Attendance for roll groups but the query needed updated to ensure correct in/out counts
- Partial attendance wasn't working properly with the Future context (no differentiation in Future - Roll Group vs Future - Class). Changed it back to Class for partial future attendance. Wondering about the utility value of the Future context 🤔
- Something odd was up with the printable Activity attendance sheet (it was fetching the same result set twice, and so the student list didn't show up).
I think these are all v14-only fixes so I'm not sure if they're changelog worthy.
_(Again, ?w=1 as very few lines have actually changed. Wish I could default this.)_
> Attendance: Fixed daily attendance counts, partial future attendance

- tests/bootstrap.php
Added a check to the Codeception tests to help ensure it can't run on production systems. Someone would also have to install PHPUnit and Codeception on their server, and edit the config file to add the test environment variable ... but one more preventative measure couldn't hurt.
> Tests: Added additional check to prevent running on production

- CHANGELOG.txt
- modules/Students/applicationForm_manage_edit.php
- modules/Students/applicationForm_manage_editProcess.php
An odd one: looks like the process page for Edit Application Form was adding spaces to the privacy options csv. I checked the User Edit process page and it isn't doing the same, so I took out the extra spaces and updated the Edit Application page to handle records with existing spaces.
> Students: updated Edit Application Form to handle spaces in privacy options csv

- CHANGELOG.txt
- modules/Students/student_view_details.php
This one caused an unexpected surprise when the enrolment for upcoming years was visible even though the user role did not have access to future years 😧
> Students: Fixed School History in profile to exclude upcoming years

- CHANGELOG.txt
- src/Forms/Input/CustomField.php
Fix for #289. The CustomField class internally creates an object based on the variable types of custom fields. This fix updates the CustomField class to override the getValidationOutput() method from the Input base class to pass the getValidationOutput() from the internal object instead. Tested & working for each type of custom field.
> System: fixed form validation for dropdowns created with User Custom Fields

- CHANGELOG.txt
- modules/Students/applicationForm.php
For issue #291. This fix updates the Student Application Form to always select the first gibbonFamilyID when one or more families are available to select (ensuring the value is never null).
This one must have snuck past us in pre-release testing (although I do recall testing the logged-in application form a few times). Currently there isn't an automated test for the logged-in family-exists variant of the form so I've made a note to write one.
We had previously discovered that LiveValidation doesn't work for Radio elements (because LV uses IDs and they have to be unique). This means currently there's no handling for required radio elements. Do you think it would make sense to update the Radio class to always select a default value if its a required field? It makes it possible for a user to …
> Students: fixed default selected gibbonFamilyID in Application Form

- CHANGELOG.txt
- modules/Students/applicationForm.php
- modules/Students/applicationForm_manage_edit.php
- adds missing Other Fields heading for logged-in parent
- hides Other Fields heading for parents when no custom fields are set
- also adds missing translation wrapper on student Other Information heading
> Students: fixed display of Other Fields headings for parents in Application Form

- CHANGELOG.txt
- modules/Planner/planner_view_full.php
The reason and comment fields in planner attendance are hidden by default and only appear on change, to keep the sidebar less cluttered. Updated this behaviour to only apply when Present is the default attendance type.
> Planner: updated show/hide behaviour for attendance reason & comment

- CHANGELOG.txt
- src/Gibbon/core.php
- src/Gibbon/locale.php
- src/Gibbon/session.php
Timezones are set in the Locale class from a session variable. In CLI scripts, the system settings were being populated into the session after the locale was already set, resulting in the CLI running with UTC as the default timezone.
A lot of the page setup is still split between global function calls and newer class methods, this fix moves some more of the session populating logic into the Session class, but the overall architecture changes are still a work in progress. Hope to get more of these classes sorted out soon.
> System: fixed timezone not being set in CLI scripts

- CHANGELOG.txt
- functions.php
- login.php
- modules/School Admin/schoolYear_manage.php
- modules/School Admin/schoolYear_manage_add.php
- modules/School Admin/schoolYear_manage_addProcess.php
- modules/School Admin/schoolYear_manage_edit.php
- modules/School Admin/schoolYear_manage_editProcess.php
It's possible to accidentally set the current year to Past without setting a new Current year, which causes all further login attempts to fail. This PR aims to enforce the presence of a single Current year with the following changes:
- Current school year cannot be deleted or it's status changed
- Changing another year's status to Current will replace the current school year, and warn the user making the change:
- Changes to the current year updates session variables, which enables the top-of-page warning if they're now logged into a non-current year
- Clarified the error message when there's no current year, on the off chance it's changed through the database or some other means
> School Admin: updated Manage School Years to prevent removing or unsetting the current School Year

- src/Forms/Input/Select.php
Minor fix to the Select class, the size attribute was being overwritten if it had been manually set. Part of the changes Ray and I worked on for the Multi-Selector.
> Form Class:fixed size attribute for Select class with multiple options

- modules/School Admin/house_manage_edit.php
- modules/School Admin/house_manage_editProcess.php
- modules/Students/applicationForm_manage_edit.php
- modules/System Admin/alarm.php
- src/Forms/Input/FileUpload.php
- src/Gibbon/FileUploader.php
- themes/Default/css/main.css
Improves the layout of the File Upload field when there's an existing attachment. Currently only affects forms that are OOified (alarm, house edit, application form)
Eg:
- Moves the attachment name and options inside a box, same width as other form inputs
- Adds a delete button, and FileUpload methods to implement it. Allows attachment deletion/replacement to be part of the form submission rather than a separate action.
- Adds a download button, for ease of access
- File upload input displays allowed file-types on hover
> Form Class: usability improvements for the File Upload field

- src/Forms/Form.php
- src/Forms/Input/Input.php
- src/Forms/Input/Select.php
- src/Forms/Layout/Heading.php
- src/Forms/Layout/Label.php
- src/Forms/Layout/Row.php
Implemented getLabel in Select class to add a helper description "Use Control, Command and/or Shift to select multiple." for multi-select inputs.
> Form Class: added a getLabel method to Input class

- CONTRIBUTING.md
- issue_template.md
- pull_request_template.md
[Read the formatted text here](https://github.com/SKuipers/core/blob/a5bed274d2979f7c033544d9b3ea883550646719/CONTRIBUTING.md)
Adding this file will automatically link to these guidelines on the issues and pull request pages:
https://help.github.com/articles/setting-guidelines-for-repository-contributors/
*Edit:* added some issue and PR templates
https://help.github.com/articles/creating-an-issue-template-for-your-repository/
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
> Community: added contributor docs for GitHub

- modules/Planner/planner_view_full.php
Quick visual tweak to hide extra fields if the default attendance type is present _or_ the currently set attendance is Present.
> Planner: updated sidebar attendance show/hide behaviour

- tests/config/support/AcceptanceTester.php
**Bug Fix**
The login form OOification changed the form name to an ID, which broke the loginForm selector for acceptance tests, and I forgot to run the tests before that PR. Oops!
> Tests: fixed the loginForm to reference by ID instead of name

- cli/attendance_dailyIncompleteEmail.php
**Quick Fix**
Exceptions for staff added through Timetable Admin > Class List Exception will be honoured by the attendance CLI script.
> System: updated Attendance CLI to handle staff timetable exceptions

- cli/attendance_dailyIncompleteEmail.php
Improved the Attendance CLI query to help skip over empty classes.
This should do the trick, let me know if you still see any empty classes in your CLI notifications. There was a check in there to count students and omit empty classes but it wasn't doing a student status/dateStart/dateEnd check.
> CLI: updated Attendance CLI to check student status when counting classes

- CHANGEDB.php
Changed the required permission for Application Form Accepted and New Application Form to `View Student Profile_full`. This allows for staff who don't necessarily have rights to edit the application still receive the notification.
> System Admin: changed permission req for Student Application events

- modules/School Admin/department_manage_add.php
- modules/School Admin/department_manage_edit.php
- modules/School Admin/department_manage_editProcess.php
- src/Forms/Input/FileUpload.php
- themes/Default/css/main.css
**Bug Fix**
Also fixes the appended max upload text by adding the text to the FileUpload class by default. Adds two new methods to FileUpload: 
- setMaxUpload($value) : Displays the max filesize text. On by default and set to the system level. Can be used to set a smaller max upload value.
- uploadMultiple() : turns on the `multiple` flag for the input type="file"
> School Admin: fixed image attachment in Edit Department

- CHANGEDB.php
- CHANGELOG.txt
- modules/Students/applicationForm.php
- modules/User Admin/applicationFormSettings.php
- modules/User Admin/applicationFormSettingsProcess.php
- Adds an Available Years of Entry setting to Application Form Settings to select which years are selectable in the student application form.
- Defaults to the current behaviour of all current and upcoming years
Even though a school year exists in the database it's not always open for new student applications. Our office staff needed a way to limit which years could be applied to, and change it easily when application windows open/close.
Tested locally and in production at TIS.
> User Admin: added setting to limit Student Application Form years of entry

- src/Data/UsernameGenerator.php
- tests/unit/Data/UsernameGeneratorTest.php
**Bug Fix**
A missing `mb_` prefix on a string function caused a multibyte username to return blank. Fixed the function call and added an additional fallback to always prevent blank usernames.
Added a unit test to cover the basic functions of the username generator.
> System: fixed multibyte and blank usernames in UsernameGenerator

- src/Forms/Input/Finder.php
**Small Fix**
A couple small fixes to the AJAX url and default parameters in the Finder class.
Been testing this one out in custom modules and it's working well. Hope to get more finder-type fields into the core soon (to replace some of those massive drop-downs)
> Form Class: fixed AJAX url in Finder class, updated selected method

- installer/install.php
A couple very small changes. Re-names the labels in step 1 to remove the extra "this value cannot be changed" text. Removes the $form->setClass calls (to use the default, which has some spacing css for livevalidation)
> System: minor formatting changes in the installer

- src/Forms/FormRenderer.php
**Bug Fix**
The form renderer was aggregating the LiveValidation js for the entire form and outputting it at the bottom. The idea was to cut down on all the separate inline script blocks. The downside of this is a js error in one section could cause the whole script block to fail.
This fix changes the renderer to output the LV js for each row at a time. If one LV field fails it will not affect the rest of the form validation.
Tested locally (by hand & automated tests) and in production.
> Form Class: updated renderer to not aggregate LiveValidation javascript

- CHANGEDB.php
- cli/attendance_weeklySummaryEmail.php
From feature requests on the development roadmap: https://trello.com/c/LjKqL7th
The Weekly Attendance Summary is a breakdown of student absences and lates over a one-week span (intended to be sent on or after Fridays). Student absences are listed by weekday, grouped and ordered by Form Group. Hopefully this is a useful format & amount of information, happy to update it with any feedback.
Helps admin and office staff keep track of the overall absences for the school week and follow up as needed.
Tested locally and in production at TIS.
Example from demo data:
> System: add Weekly Attendance Summary CLI

- CHANGEDB.php
As discussed in Slack, changing the column size of the gibbonPerson column in gibbonActivityStaff to 10. The original column length (8 , I believe) meant that string based comparisons on the zerofilled int would result in failure.
> Fixing the length of the gibbonPerson column in gibbonActivityStaff

- CHANGELOG.txt
- modules/Students/applicationForm_manage_edit.php
- modules/Students/applicationForm_manage_editProcess.php
- src/Forms/Input/FileUpload.php
- themes/Default/css/main.css
- Updates the FileUpload class to handle displaying multiple attachments for one file input
- Adds the ability to delete application form attachments
- Adds the ability to upload multiple files to the application form (at the same time, or one at a time)
Admissions staff often need more tools to manage the files attached to an application form.
> Students: added ability to delete files and upload multiple files in Edit Application Form

- CHANGELOG.txt
- modules/Attendance/attendance_take_byCourseClass.php
- Adds a warning to the top of Attendance by Class if that class is not timetabled for the selected date (and only displays if it's a regularly timetabled class)
Provides and extra visual cue to help prevent staff from taking attendance for a class on the wrong date.
> Attendance: add a warning to Attendance by Class when not timetabled

- src/Forms/FormFactory.php
- src/Forms/Input/Button.php
Following on from previous PR where I clearly displayed my superior git knowledge and totally borked the branch... Here is a branch with just one fix instead of like 3 fixes bundled in!
Post copied from last PR:
==============
Ok I've set vim to use 4 spaces instead of tab chars now.
I've made a solution to the button class which leaves the constructors for the class alone. When created through FormFactory, the ID is assigned through a 3rd, optional, variable. If no ID is provided, the label is used, as before. If you want to use multiple buttons of the same name, you'll need to use the third variable to set it.
Here's what you can do with the changes:
```
$frm = Form::create('test',null,'get');
$frm->addRow()->addButton('hello'); //Create a button with a label and no onclick …
```
> Button Fix

- themes/Default/css/main.css
**Bug Fix**
By default the theme css applies a float to all form inputs. For form columns to align properly a clearfix was introduced. This PR updates the clearfix to only apply to the first div inside the column, so elements like Editor with many nested divs don't have unwanted clearfixes applied.
> Theme: update clearfix used in Form class columns

- src/Gibbon/sqlConnection.php
**Bug Fix**
Namespacing in the sqlConnection class was causing some exceptions to not be caught in the executeQuery method.
We may also want to consider logging the errors rather than echoing them, so we can opt to only output errors in non-production environments.
> System: Fix PDOException in sqlConnection class

- preferencesPasswordProcess.php
**Bug Fix**
The passwordForceReset flag wasn't turning off again after changing a users password through Preferences. Looks like the culprit may have been a missing $_POST value in the password form. Rather than passing it by post (which could be tampered with), updated it to grab from the existing session value.
> System: fix passwordForceReset not resetting after a password change

- modules/User Admin/role_manage.php
- modules/User Admin/role_manage_delete.php
- src/Forms/PrefabFormFactory.php
- themes/Default/css/main.css
This adds a new PrefabFormFactory class for creating predefined forms in one method call. Helps reduce duplicate code for forms that are nearly identical throughout the system. The createDeleteForm method has option for confirmation text-entry, off by default.
I've implemented it in Manage Roles as an example. Both the delete and duplicate actions function as modal windows with a small tweak to the code (also as an example, easy to revert out if needed).
> Form Class: add a prefab Delete Form, implement in Manage Roles

- CHANGELOG.txt
- preferences.php
- preferencesProcess.php
Adds an Enable Smart Workflow Help option to the preferences page for users in the Staff category.
It's often easy to dismiss and teachers currently have no way to turn it back on.
> System: add Enable Smart Workflow Help option to Preferences 

- CHANGEDB.php
- CHANGELOG.txt
- modules/Data Updater/data_personal.php
- modules/User Admin/userSettings.php
- modules/User Admin/userSettingsProcess.php
- modules/User Admin/user_manage_add.php
- modules/User Admin/user_manage_edit.php
- modules/User Admin/user_manage_emailAjax.php
Adds an option to Manage User Settings which allows requiring a user's primary email address to be unique. This option is off by default. The check is performed via AJAX when adding and editing users.
I also have a Query Builder query for finding non-unique emails which may be handy to add to the collection.
Systems using Google to login need to enforce unique emails otherwise conflicts arise and users cannot login. A unique email is also required to use the password reset form and login via email address.
Tested locally and in production at TIS.
_Edit: snuck in a tiny fix for the Emergency Contact 2 Name_
> User Admin: added a setting to require email addresses to be unique

- assets/js/core.js
- modules/User Admin/user_manage_add.php
- modules/User Admin/user_manage_password.php
- passwordReset.php
- preferences.php
- publicRegistration.php
- src/Forms/Input/Password.php
- src/Forms/Traits/BasicAttributesTrait.php
- themes/Default/css/main.css
This changeset helps cleanup the password code and move it into one location. 
- Moves the generatePassword JS function into assets
- Adds new methods to the form Password class:
- addConfirmation: links a password field as confirmation for another field
- addPasswordPolicy: attaches the validation for system-defined password requirements
- addGeneratePasswordButton: adds the button, hooked up to the JS function
- Fixes the alignment issue with buttons and LV messages by pulling the buttons over to the right-hand side of the input.
- Changes the password pop-up from an alert to a prompt to make copy-pasting easier ([from forum issue](https://ask.gibbonedu.org/discussion/2050/generate-password-when-creating-new-user-unable-to-copy-the-text))
- Adds addData and getData methods to the …
> System: cleanup and move password code into Password class

- functions.php
- modules/Activities/activities_view_register.php
**Bug Fix**
Fixes a bug in the activities register script (from ooification, my fault).
Plus a small usability tweak: Adds the student gibbonPersonID to the View Available Activities link so it's pre-selected on the following page
> Activites: fix error with SQL variable name in Activity Register

- index.php
Adds version numbers to the CSS and JS files for themes and modules. It's a common cachebusting technique and will help ensure changes in future versions aren't overridden by a users browser cache. It'll be particularly helpful as we're working towards updating the stylesheets and adding responsive elements.
> System: add version numbers to css and js URLs for cachebusting

- modules/Activities/activities_manage.php
- src/Forms/FormFactory.php
- src/Forms/Prefab/BulkActionForm.php
Following up on the previous PR, this one adds the BulkActionForm class to pull together the logic and layout elements into one prefab form. Makes things easier to maintain and implement.
Also updates the one ooified bulk action form so-far, with some more forms in the works for a future Timetable Admin PR.
> Form Class: add a BulkActionForm class

- CHANGEDB.php
- CHANGELOG.txt
- functions.php
- modules/User Admin/staffSettings.php
- modules/User Admin/staffSettingsProcess.php
A requested feature. This is an interim solution until we have a more system-wide oo approach. PR adds settings to User Admin > Manage Staff Settings to allow editing the formal and informal name formats in a similar pattern as the username formats.
Adds flexibility, different schools have specific formats for addressing teachers.
> User Admin: add settings to adjust formatting of staff names

- cli/planner_parentWeeklyEmailSummary.php
- functions.php
- modules/Finance/invoices_manage_editProcess.php
- modules/Finance/invoices_manage_issueProcess.php
- modules/Finance/invoices_manage_processBulk.php
- modules/Finance/invoices_payOnlineProcess.php
- modules/Messenger/messenger_manage_report_processBulk.php
- modules/Staff/applicationFormProcess.php
- modules/Staff/applicationForm_manage_accept.php
- modules/Students/applicationForm_manage_accept.php
Fixes a [sendmail issue](https://ask.gibbonedu.org/discussion/2081/sendmail-send-mail-gibbon-14-0) where some scripts were still manually calling the PHPMailer IsSMTP() method. The mailer config is already handled inside the getGibbonMailer function so it will default to the built-in PHP mail function (using sendmail) if SMTP is turned off in Third Party Settings.
> System: remove stray calls to IsSMTP outside getGibbonMailer function

- error.php
- src/Gibbon/core.php
- themes/Default/css/main.css
Two main purposes for this PR: to always prevent the display of error messages in Production (regardless of server config), and to improve the display of error messages in Development and Testing installs.
- Uses the built-in set_exception_handler and set_error_handler functions to define custom behaviour for error handling.
- In Production any fatal errors will fallback to the generic Gibbon error page. Any notices and warnings will not display.
- In Development and Testing, any code errors/warnings/notices are wrapped in an error div and the stack trace is formatted for improved readability.
- Fixes the visual glitch where sidebars don't render after a fatal error or exception.
It's likely a good idea to ensure the display_errors setting is always off for Production, especially …
> System: add error handling and prevent error messages in Production

- src/Gibbon/core.php
- src/Gibbon/menuModule.php
- themes/Default/css/main.css
- Moves the css inline to catch errors before the HTML head
- Adds display: flow-root; to prevent menu-overlap on fullscreen pages
- Adds to and updates the error handling doc comments
> System: visual tweaks to error handling

- fullscreen.php
- lib/google/index.php
- login.php
- modules/Activities/activities_view.php
- modules/Activities/moduleFunctions.php
- modules/Behaviour/behaviour_manage_add.php
- modules/Markbook/markbook_view_myMarks.php
- modules/Students/student_view_details.php
- modules/System Admin/thirdPartySettings.php
- modules/Timetable/moduleFunctions.php
- modules/Timetable/report_viewAvailableSpaces.php
- modules/User Admin/family_manage_edit_editAdult.php
- passwordResetProcess.php
Several small fixes to cleanup PHP notices, plus:
- Added a .change() event to contactPriority to fix the initial disabled state when editing family adults
- Adjusted how formatDateRange handles creating dates and tweaked the output format
- Changed the SMTP password field type from TextField to Password in Third Party Settings
> System: cleanup PHP notices, minor fixes

- modules/Attendance/attendance.php
- modules/Attendance/attendance_take_byCourseClass.php
- modules/Staff/staff_manage_edit.php
- preferencesProcess.php
- src/Forms/DatabaseFormFactory.php
- themes/Default/css/main.css
Attendance:
- Fixes an issue where attendance='Y' was hardcoded into addSelectClass in DatabaseFormFactory. Adds params to the method to optionally filter for attendance/reportable flags and applies the attendance='Y' flag to the Take Attendance by Class form.
- Display N/A in the Today column for instances where attendance has been taken on a non-timetabled day (and borrows the hover-over text from Take Attendance by Class)
- Adds a permission check back to the staff selector in View Daily Attendance - the intent being that for most staff it only shows their own attendance, and management-type roles with 'View Not Registered' permission can select and see daily attendance for any staff member.  
Staff:
- Removes the gibbonPersonID drop-down from Edit Staff and sets the field to readonly …
> Attendance, Staff, Theme, System: form fixes and display tweaks 

- cli/userAdmin_statusCheckAndFix.php
Fixes an issue where parents with multiple families could be unintentionally set as Left if the children in one family have left, but others are still active.
> System: update userAdmin_statusCheckAndFix CLI

- modules/System Admin/module_manage_installProcess.php
- modules/System Admin/module_manage_uninstallProcess.php
- roleSwitcherProcess.php
A small post-PR fix for a couple class names I missed in #454
> System: fix MainMenu objects with case-sensitive class names

- modules/Messenger/messenger_post.php
Fixes a messenger SQL error in course, class and activity queries for users whose highest permission is New Message_courses_my, New Message_classes_my, and New Message_activities_my respectively. Adds the table name prefix to a few other queries in that form to help prevent any other SQL ambiguity.
> Messenger: fix a post-ooification SQL integrity constraint error

- modules/Messenger/messenger_manage_edit.php
- modules/Messenger/messenger_manage_editProcess.php
- modules/Messenger/messenger_post.php
Found & fixed the messenger edit issue: 
- The Edit Message form was still pointing back to messenger_postProcess.php
- Fixed the roleCategories[] field which was likely a copy-paste error and still called roles[]
- Updated the setValue() calls for the message wall to handle editing the three date values
> Messenger: fix Edit Message form URL, fix dates for wall messages

- modules/Formal Assessment/internalAssessment_manage_add.php
- modules/Formal Assessment/internalAssessment_manage_edit.php
- modules/Formal Assessment/internalAssessment_write_data.php
- src/Forms/DatabaseFormFactory.php
- src/Forms/Input/TextArea.php
- src/Forms/Layout/Element.php
- src/Forms/Layout/NullElement.php
- src/Forms/Layout/Row.php
The markbook OOification is done but the change set ended up pretty big so I've split it into two parts. The first is just the related Form API changes, and some Formal Assessment updates that overlap with the same functionality:
Adds the following form elements to DatabaseFormFactory, and implements the change where needed:
- SelectSchoolYearTerm
- SelectGradeScale
- SelectGradeScaleGrade
- SelectRubric
Adjusts the append/prepend handlin g in Element class to be more succinct and allow nested wrap()s.
Adds the auto-resize functionality found in the markbook to the TextArera class as a method. 
Adds a conditional method which can be chained into form elements. This improves the overall readability of a form that has lots of conditionals, and allows for easier implementation of forms that …
> Form Class: markbook-related additions and changes

- CHANGEDB.php
- CHANGELOG.txt
- modules/Attendance/attendance_take_byPerson.php
- modules/Attendance/attendance_take_byPerson_delete.php
- modules/Attendance/attendance_take_byPerson_deleteProcess.php
A small but useful change. We have on occasion had the odd attendance logs recorded that were in error (on the wrong day, wrong class, etc). Currently attendance logs can only be edited but not deleted; the only way to delete them is via the database. The Manage Attendance Logs permission is separate from Attendance by Person, allowing it to be selectively given to the appropriate roles, and makes the most sense as a way to allow attendance deletion without giving wide access to the ability.
> Attendance: add a delete option to Manage Attendance Logs permission

- modules/Markbook/markbook_edit_data.php
**Bug Fix**
Fixes a post-OOification issue where the last student in the list appeared with the same name & details as the second last student. Caused by using `&$student` in a foreach 🤦‍♀️
> Markbook: fix issue where last student in Edit Data was duplicated

- assets/js/core.js
- modules/Data Updater/data_personal.php
- modules/Data Updater/data_personal_manage_edit.php
- modules/Library/library_manage_catalog_add.php
- modules/Library/library_manage_catalog_duplicate.php
- modules/Library/library_manage_catalog_edit.php
- modules/Library/library_manage_catalog_idCheckAjax.php
- modules/Students/applicationForm_manage_edit.php
- modules/User Admin/user_manage_add.php
- modules/User Admin/user_manage_edit.php
- modules/User Admin/user_manage_emailAjax.php
- publicRegistration.php
- publicRegistrationCheck.php
- publicRegistrationProcess.php
- src/Forms/Input/TextField.php
- src/Forms/Layout/Label.php
Adds a uniqueness method to the TextField class in the Form API:
`isUnique($ajaxURL [, $data = array() ])`
The first parameter is an ajax url for a script takes in the POST value of the current field and returns the number of matching entries. It can also pass an additional data array to POST, such as the current item ID to ensure uniqueness doesn't fail when editing an item.
Implemented in:
- Username - Public Registration
- Username - Add User
- Email - Public Registration
- Email - Add User, Edit User
- Email - Data Updater Personal
- Email - Application Form Manage
- Library ID - Add, Edit & Duplicate
> Form Class: add reusable ajax-based isUnique method to TextField

- installer/install.php
- modules/System Admin/systemSettings.php
Fixed the timezone array so the keys are kept the same and the values are run through __() to translate.
_I'll add my 2¢ here and then drop the issue: I do wonder if come release time every translator (and every future translator) is going to get hit with a pile of 400+ unnecessary translations, making it harder to maintain 100% translation. If it was a commonly used feature it would make sense, but timezone is pretty much set once and never changed again. Perhaps string replacement may be a decent compromise in cases where an admin really wanted that single value translated.`</soapbox>`_
> System Admin: apply translation function to timezones in System Settings

- assets/js/core.js
- gibbon.php
- modules/Finance/Forms/FinanceFormFactory.php
- modules/Finance/invoices_manage.php
- modules/Finance/invoices_manage_add.php
- modules/Finance/invoices_manage_addProcess.php
- modules/Finance/invoices_manage_edit.php
- modules/Finance/invoices_manage_editProcess.php
- modules/Finance/invoices_manage_issue.php
- modules/Finance/invoices_manage_issueProcess.php
- modules/Finance/invoices_payOnline.php
- modules/Finance/invoices_view.php
- modules/Finance/js/module.js
- modules/Finance/moduleFunctions.php
- src/Forms/DatabaseFormFactory.php
- src/Forms/FormFactory.php
- src/Forms/FormRenderer.php
- src/Forms/Input/CustomBlocks.php
- src/Forms/Input/Input.php
- src/Forms/Input/Number.php
- src/Forms/Layout/Grid.php
- src/Forms/Layout/Table.php
- themes/Default/css/main.css
_"It's just five pages, how hard could it be..."_ 😬 
This PR completes the ooification for the finance module, and adds in the reusable js and css for CustomBlocks which are the final piece of the puzzle for the remaining Planner forms. This builds on Ray's work on CustomBlocks and primarily separates out the inline code into reusable functions.
It ended up being a fairly large change set, although many of the files have only had a couple lines updated. Some of the notable changes are:
- Custom Blocks:
- Blocks are defined by passing a template into the CustomBlocks class, which is cloned for each new block. The contents of a block can be any `OutputableInterface` object, which includes all Form API elements. 
- Button clicks are dispatched as events so they can be handled in js with …
> Finance: Manage Invoices OOification, update CustomBlocks feature

- modules/Students/applicationForm_manage_edit.php
Minor bug fix (v16 only). I must have been a little overzealous applying the isUnique check to _all_ the email fields 😏
> Students: remove unnecessary isUnique in Manage Application Form

- modules/Timetable/moduleFunctions.php
The `$rowDay` was being set inside a loop, and then checked for `isset()`. Added an unset at the beginning of the loop to clear the value.
Also tweaks the recent This Week/Last Week changes to the translation strings, so the added symbols are outside the string.
> Timetable: fix days outside the term displaying the wrong name 

- src/Forms/Input/Select.php
- src/Forms/Input/TextArea.php
A couple minor adjustments to the Select and TextArea classes.
- Fixes an issue where the Select placeholder would not appear if the first option was a numeric 0
- Fixes an issue where a null value in the option list prevented other options from being selected (as seen in Trip Planner): changes the option values to always compare as strings.
- Adds the setCols and placeholder methods to TextArea, to make those HTML attributes usable.
> Form Class: tweak Select class logic, add TextArea methods

- src/Gibbon/Session.php
Adjusts the code that sets the current module & action in the Session class to be more backwards-compatible for the Reporting module. Most process pages pass a POST value and use `getModuleName($_POST['address'])` to determine the current module. The Reporting module currently uses the `$_SESSION[$guid]['module']` value having been set on the previous page prior to form submission.
> System: update Session class handling of address/module/action values

- modules/Timetable/moduleFunctions.php
Sundays show following days in Timetable regardless of which day of the week is the "first". Previously, Sundays only showed following days if Monday was the "first" day. Sunday "first" people were feeling a little excluded!
> Sundays show following days for Sunday people

- CHANGELOG.txt
- modules/Timetable Admin/courseEnrolment_sync.php
- modules/Timetable Admin/courseEnrolment_sync_add.php
- modules/Timetable Admin/courseEnrolment_sync_addEditProcess.php
- modules/Timetable Admin/courseEnrolment_sync_delete.php
- modules/Timetable Admin/courseEnrolment_sync_deleteProcess.php
- modules/Timetable Admin/courseEnrolment_sync_edit.php
- modules/Timetable Admin/courseEnrolment_sync_run.php
- modules/Timetable Admin/courseEnrolment_sync_runProcess.php
Sync Course Enrolment was missing a school year selector. You can still login to future years to manage it (so it's not broken), however to keep the workflow and functionality inline with the rest of Timetable Admin I've added the year selector here too.
Edit: looks like the changelog has ended up with a mix of tabs and spaces. I ran a convert tabs to spaces on it to match the rest of the codestyle.
Edit2: Nice! looks like hide whitespace changes is now a built-in option under Files Changes > Diff Settings 😄
> Timetable Admin: add school year selector to Sync Course Enrolment

- modules/Data Updater/data_family.php
- modules/Data Updater/data_personal.php
- modules/Students/applicationForm.php
- modules/Students/applicationForm_manage_edit.php
- modules/User Admin/family_manage_edit.php
- modules/User Admin/user_manage_edit.php
Currently addresses are edited in a text field, which is often too short to read the whole address (which requires using your cursor inside the field to scroll right). This PR makes a small visual tweak by changing the Address 1/Address 2/Home Address fields to a short two-row text area.
> User Admin: change all address fields to a short two-line text area

- modules/Students/applicationForm.php
- modules/Students/applicationForm_manage_edit.php
I'm pretty sure before ooification the application form only required an email, phone number and profession for the first parent and not the second one. This PR restores that behaviour.
> Students: un-require second parent contact info in Application Form

- gibbon.php
- modules/User Admin/user_manage.php
- src/Services/Format.php
- src/Services/FormatResolver.php
This PR adds a Format class, which helps clean up and replace a lot of the global formatting functions, and remove the need to pass in session and $guid data to them each time.
The specific formats and settings can be loaded in from the session and locale data, giving us a flexible way to internationalize and customize data that's output throughout the codebase.
The Format class can also pass a formatter to a DataTable as a closure with the `using()` method, which allows a specific format to be applied to a non-uniform array of row data when looped over. Eg: loop over an array of users, and pass each row of user data into different formatters that can extract the fields they need and display a string.
Modules can also use addFormatter to supply their own formats without needing to edit …
> System: add a Format class for locale-aware data formatting

- assets/js/core.js
- gibbon.php
- src/Domain/QueryCriteria.php
- src/Domain/QueryableGateway.php
- src/Services/Format.php
- src/Tables/Renderer/PaginatedRenderer.php
- tests/unit/Domain/QueryCriteriaTest.php
- tests/unit/Services/FormatTest.php
- themes/Default/css/main.css
- Reduces the size of the record count to match the regular table styles, for consistency. 
- Adjusts the criteria so that filters of the same type are always mutually exclusive. This makes selecting a new filter of the same type replace the current one, rather than allowing conflicting filters.
- Some more visual tweaks to fix the sort arrow placement, table footer, etc.
- Adds unit tests for the Format class (and adjusts the class internally to make it more testable)
> Table API: visual tweaks, adjust filter logic, add more unit tests

- assets/js/core.js
- modules/Roll Groups/rollGroups.php
- modules/User Admin/user_manage.php
- src/Domain/School/RollGroupGateway.php
- src/Services/Format.php
- src/Tables/Action.php
- src/Tables/Column.php
- src/Tables/DataTable.php
- src/Tables/Renderer/PaginatedRenderer.php
- src/Tables/Renderer/SimpleRenderer.php
- themes/Default/css/main.css
Sometimes you don't need a fancy paginated table, just a regular one will do. This PR adds a SimpleRenderer, which can take any SQL result set and transform it into a table. I've ooified the Roll Groups table as an example.
Also includes some other minor tweaks:
- Sortable columns are on by default, and easily disabled for a column with `notSortable()`
- Adds formatters for link and nameList
- Tidies up some internal table class logic
- Fixes filters not working after using the clear button
- Name format no longer outputs default values if params are empty
> Table API: add SimpleRenderer for DataTables, ooified Roll Groups

- CHANGELOG.txt
- modules/Data Updater/data_familyProcess.php
- modules/Data Updater/data_family_manage_edit.php
- modules/Data Updater/data_financeProcess.php
- modules/Data Updater/data_finance_manage_edit.php
- modules/Data Updater/data_medicalProcess.php
- modules/Data Updater/data_medical_manage_edit.php
- modules/Data Updater/data_personalProcess.php
- modules/Data Updater/data_personal_manage_edit.php
- modules/Data Updater/data_updates.php
This PR adds two small features:
- If required data updates are enabled, it will redirect the user back to the My Data Updates page after submitting a form if they still have pending updates. This helps the workflow of users to easily find their way back to the visual view of any updates they still have to make.
- Adds helper links to the top of the Manage Update pages to easily find and edit the associated records (if the user has permission to). This helps staff members who review and accept the updates, if there's a change they need to make manually either before or after accepting the data update.
> Data Updater: workflow improvements for submitting & managing updates

- functions.php
- src/Services/Format.php
I've marked the following functions as deprecated, and updated the code if a drop-in replacement was available (which is most of them).
- setNotification
- ynExpander
- formatName
- addressFormat
- getAge
- formatPhone
- printUserPhoto
- getUserPhoto
- dateConvert
- dateConvertBack
- dateConvertToTimestamp
- printPagination
- ExportToExcel
Removed:
- setStringReplacementList() Not used since v13
- dump() Not used since v13
- dateConvertToTimestampGM Not used anywhere, core or additional modules.
> System: mark deprecated functions, update where applicable

- modules/Students/medicalForm_manage.php
- modules/Students/medicalForm_manage_condition_add.php
- modules/Students/medicalForm_manage_condition_edit.php
- modules/Students/medicalForm_manage_edit.php
- src/Domain/Students/MedicalGateway.php
This PR also fixes what appears to be a post-ooification bug that made it into v15. The names for medical conditions have in the past been stored as strings, after ooification they have been coming through as ID numbers, ending up with a table of mixed names and IDs. The drop-downs have been updated to use the names as strings (the original behaviour) and the Edit Condition page will now select the appropriate name from the drop-down if an ID is present in the database.
> Students: Manage Medical Forms table ooification

- src/Forms/Input/MultiSelect.php
**Bug Fix**
Fixed a bug that would occur, where by duplicate entries form the MultiSelect input would be sent to the process page if the form had failed to send once or more.
Renamed destination source in MultiSelect to name of MultiSelect and removed the jquery hook that would create hidden inputs of the destination options when the submit button was pressed.
Duplicate entries would cause a problem when processing inputs and this should also marginally increase the speed of the MultiSelect Input on submission of a form.
This was tested using an isolated test page and with the Trip Planner Submit Request page. No errors were created in either case by these changes.
> Form Class: Fixed bug where duplicate entries would be sent through MultiSelect

- modules/Individual Needs/in_view.php
- modules/School Admin/space_manage.php
- modules/Staff/applicationForm_manage.php
- modules/Staff/staff_manage.php
- modules/Staff/staff_view.php
- modules/Students/medicalForm_manage.php
- modules/Students/studentEnrolment_manage.php
- modules/Students/student_view.php
- modules/System Admin/stringReplacement_manage.php
- modules/Timetable Admin/courseEnrolment_manage.php
- modules/Timetable Admin/courseEnrolment_manage_byPerson.php
- modules/Timetable Admin/course_manage.php
- modules/Timetable/tt.php
- modules/Timetable/tt_space.php
- modules/User Admin/family_manage.php
- modules/User Admin/user_manage.php
- src/Tables/Renderer/PaginatedRenderer.php
This changes a fair number of files, but the change is fairly small and the same each time:
- Moves the creation of $criteria above the search form.
- Changes the search text field to use `$criteria->getSearchText()` rather than the raw `$_GET['search']` value. This is the processed search text that has filters removed.
Usability wise this means the filter text (eg `all:on` `active:Y`) will no longer show up in the search field, including filters typed into the search. This still feels pretty intuitive, since the filters can be seen and managed via the UI, and it separates the function of the clear search and clear filter links.
> Tables: don't display filters in search field after Back to Search Results

- src/Services/Format.php
This changes the date methods in Format to behave more like the original date format functions, in that they return the original string back if no formatting changes were made, rather than an empty string. This helps in instances where the date passed in may have already been in the correct format.
> System: fix Format date methods to return original string on failure

- modules/School Admin/house_manage_assignProcess.php
The assign houses tool has a Balance by Gender option that currently does not properly handle users with Other or Unspecified genders. This fix randomly selects M or F _only_ for the purposes of numerical distribution, so it can continue to balance the house totals by gender and/or year group.
> School Admin: fix the Assign Houses tool to handle unspecified genders

- src/Gibbon/sqlConnection.php
This is a small change, but it will likely help reduce the friction for the v16 update process by implementing the new database Connection contract in the old sqlConnection class. This will prevent type-hinting related errors for additional modules that haven't been updated and may still contain duplicate $connection2 instances.
> System: update old sqlConnection class to implement Connection contract

- modules/Data Updater/data_updates.php
- src/Domain/DataUpdater/DataUpdaterGateway.php
A small tweak that will not count required updates for users whose start date is after the cutoff date. A brand new student shouldn't need to update their info right away.
> Data Updater: do not require updates for new students after the cutoff

- fullscreen.php
- modules/Data Updater/report_student_dataUpdaterHistory.php
- modules/Markbook/css/module.css
- modules/Markbook/markbook_view_allClassesAllData.php
- modules/Students/report_student_emergencySummary.php
- modules/Students/report_student_medicalSummary.php
- modules/Students/report_students_byHouse.php
- modules/Students/student_view_details.php
- modules/Timetable/tt.php
- Fixes a visual alignment issue with long titles and unit names in View Markbook Columns; adds some css to keep the column actions and sub-headings aligned better.
- Removes the drag-handle when a markbook column should not be editable.
- Fixes an issue in View Timetable by Person where the generic 'no results found' message was superseding the built-in data tables one, causing the table to disappear when certain filters were applied.
- The rest are PHP notice fixes.
> System: fixes for PHP notices + other minor testing-relates fixes

- modules/Students/applicationForm_manage_accept.php
One _small_ fix. The `$values` array which holds the application data was being overwritten in one logic-branch of the application accept process, leading to missing data later on in the process page.
> Students: fix parent relationship check in Accept Application Form

- CHANGELOG.txt
- assets/js/core.js
- src/Forms/Input/Select.php
- themes/Default/css/main.css
I'd love to one day forget that IE ever existed 😏 ...until that day, here's a couple backwards compatibility fixes for IE10-11. The changes are only a couple lines and work just as well with modern browsers, so worth the effort... maybe.
- Changes some default argument assignment and array destructuring to use javascript that's compatible with older browsers.
- Fixes an IE rendering issue with max-height and multiple selects where the select area was not scrollable.
> System: fix IE incompatibility with javascript and select inputs

- assets/js/core.js
- src/Tables/Renderer/PaginatedRenderer.php
Adds a spinner icon, identical to the submit button, that shows up on data table refreshes that take longer than 0.5s. 
This helps as a visual clue to the user that the AJAX process is still working, but on a delay so it doesn't flash on & off for quick page loads.
> Tables: add a spinner icon to Data Tables for reloads longer than 0.5s

- modules/System Admin/updateProcess.php
This error manifests in cutting edge installs on update, they'll see an 'Update success' message, but upon further inspection none of the SQL updates had been run. 
It happens only when a cutting edge install is one full version behind, which likely hasn't happened much before, but in this case v16.0.01 has been added in-between v16 and v17.
In the code, the error arises when `$tokenCount` was being accessed as an array `$tokenCount[0]` and incremented as a plain integer. Oddly, no errors were thrown by this syntax.
> System: fix update process for cuttingEdge code

- CHANGEDB.php
- CHANGELOG.txt
- modules/Data Updater/report_family_dataUpdaterHistory.php
- src/Domain/DataUpdater/FamilyUpdateGateway.php
- src/Forms/Input/Select.php
- themes/Default/css/main.css
Similar to the student updater history, the family updater history gives an overview of families in the school and whether the family data & personal data of family members has been updated recently. This view helps school admin when undertaking an effort to update data school-wide.
> Data Updater: add a Family Data Updater History report

- CHANGEDB.php
- CHANGELOG.txt
- lib/google/index.php
- login.php
- modules/User Admin/role_manage.php
- modules/User Admin/role_manage_add.php
- modules/User Admin/role_manage_addProcess.php
- modules/User Admin/role_manage_duplicateProcess.php
- modules/User Admin/role_manage_edit.php
- modules/User Admin/role_manage_editProcess.php
- src/Domain/User/RoleGateway.php
This feature gives school admin access to toggle a Can Login option for an entire role. Similar to the Can Login option per-user, if the role-level access is set to No then any primary user of that role will not be able to login.
There are a number of use-cases where it can be handy to prevent login access for an entire role:
- When first setting up a system, so that newly imported users cannot use Forgot Password to reset and login to their account before the system is ready.
- To disable login access by role for a period of time, eg: during a holiday or school break.
- Assigning different access by roles, eg: younger students cannot login and older students can.
Locally and in production at one school.
> User Admin: add a Can Login option for roles in Manage Roles 

- CHANGELOG.txt
- src/Tables/Renderer/PaginatedRenderer.php
Adds an option for pagination to select "All" as the page size, displaying all results for the table.
If used too frequently on large tables it could add strain to the system 🤔 Perhaps we can keep an eye on it, and it may be worth changing this to an optional parameter for specific data tables (invoices, etc.), off by default.
> Tables: add an All option to the pagination size selector

- CHANGELOG.txt
- assets/js/core.js
- modules/Finance/invoices_manage.php
- src/Forms/Layout/Trigger.php
- src/Tables/Renderer/PaginatedRenderer.php
- themes/Default/css/main.css
Fixed an issue where the hidden fields in a bulk action form were not properly showing/hiding after pagination.
Also fixed an issue with LiveValidation after pagination. The paginated data tables work by re-loading the table with an AJAX call. When this happened it was disconnecting the LV fields from the script that controls them, causing the LV to believe the form had been filled incorrectly. Fixed this by moving the bulk action form elements outside the data table, so they persist separate from the AJAX-reloaded part of the table.
> Tables: fix hidden fields in bulk action forms after AJAX reload

- modules/Activities/activities_manage.php
- modules/Activities/activities_view.php
- modules/Finance/expenses_manage.php
- modules/Formal Assessment/externalAssessment.php
- modules/Individual Needs/iep_view_myChildren.php
- modules/Individual Needs/in_view.php
- modules/Library/library_browse.php
- modules/Library/library_manage_catalog.php
- modules/Markbook/markbook_edit.php
- modules/Markbook/moduleFunctions.php
- modules/Markbook/weighting_manage.php
- modules/Messenger/messenger_manage.php
- modules/Planner/curriculumMapping_outcomesByCourse.php
- modules/Planner/report_parentWeeklyEmailSummaryConfirmation.php
- modules/Planner/report_workSummary_byRollGroup.php
- modules/Students/applicationForm_manage.php
- modules/Students/studentEnrolment_manage.php
- modules/System Admin/stringReplacement_manage.php
- modules/Timetable Admin/courseEnrolment_manage.php
- modules/Timetable Admin/courseEnrolment_manage_byPerson.php
Fixes a minor issue where the HTML id attribute for search `<form>`s were the same ID as the search `<input>`s, causing LiveValidation to silently fail for that form.
> System: fix html IDs of search forms

- modules/Timetable Admin/course_rollover.php
- modules/User Admin/rollover.php
**Bug Fix**
- The surname & preferred name in 'Enrol New Students (Status Full)' were reversed
- The current status in 'Set Final Year Students To Left' was listed as Expected rather than Full
> User Admin: fix display of student name and status in Rollover

- CHANGELOG.txt
- modules/Staff/staff_manage.php
- modules/Staff/staff_manageProcessBulk.php
Adds a bulk action form to the Manage Staff page, with a Mark as Left action. This will set any selected staff members status to Left and update their End Date with the date provided.
Any time there's a changeover in staff, such as the end of year, it's helpful to be able to see the full list of staff members and check off any that have left in one action.
Also adds a row highlight based on user status to make checking the list of active staff easier.
> Staff: add a Mark as Left bulk action to Manage Staff 

- src/Domain/DataUpdater/FamilyUpdateGateway.php
- src/Domain/DataUpdater/PersonUpdateGateway.php
I'm not sure I was 100% able to reproduce the issue, but I did take a close look at the query and made some changes. Previously it was comparing the timestamp in a GROUP BY query, so the field being compared needed wrapped in a group aggregate function (eg: MAX()). This then changed the conditional for the cutoff from a WHERE to a HAVING.
> Data Updater: fix an SQL aggregation related issue in updater history

- modules/Students/studentEnrolment_manage_edit.php
**:bug: Post-oofication Bug Fix**
When editing enrolments the selected student should be read-only, and was in the past.
> Students: fix read-only student field in Edit Student Enrolment

- tests/config/envs/.gitignore
To ignore `*.yml` in `tests/config/envs/` except `travis_ci.yml`.
Codeception test framework allow setting up multiple testing environment. It is helpful if a developer can define his own environment file for testing on local machine. But the local test files would contain local database information, which are not supposed to be commit and push anywhere.
Adding the `.gitignore` file would prevent accidentally adding such file and submit to the internet.
1. Unit test pass.
2. But seriously, it is only a `.gitignore` file.
> Test: Ignore additional test environment file

- CHANGELOG.txt
- modules/Messenger/messenger_post.php
- modules/Messenger/messenger_postProcess.php
- modules/Messenger/moduleFunctions.php
In Messenger, the Year Group target for Staff was including all staff in the system. This updates the logic to look for year group associations by two criteria: teaching a course for that year group, or a form group tutor of any student in that year group.
This tweak doesn't remove any capabilities, as the Role Category target for Staff can still be used if someone wishes to target all staff in the system.
> Messenger: update logic for Staff selected via the Year Group target

- modules/Activities/report_activitySpread_rollGroup.php
- src/Domain/Activities/ActivityReportGateway.php
- src/Domain/Students/StudentGateway.php
- src/Tables/Columns/Column.php
- src/Tables/DataTable.php
- src/Tables/Prefab/ReportTable.php
- src/Tables/Renderer/SimpleRenderer.php
- src/Tables/Renderer/SpreadsheetRenderer.php
Many of the reports in Gibbon group the column headings together for context. This PR adds the ability to nest columns when adding them to DataTables, which enables the renderers to display them as grouped headings. 
OOifies the Activity Spread by Roll Group report as an example, which now handles the dateType for terms and dates separately.
SimpleRenderer: (handles nested columns with colspan and rowspan)
SpreadsheetRenderer: (handles nested columns by merging cells)
The nesting can handle a fair bit of complexity too:
> Tables: add ability to create nested columns, Activity Spread by Roll Group ooification

- src/Tables/Renderer/JsonRenderer.php
The goal for DataTables is to keep them abstracted enough that we can render them out in many different forms: paginated tables, printable, spreadsheets, etc. This PR adds a renderer class for JSON data, which also handles grouped column headings as nested object data.
This isn't used anywhere _just yet_ but it's part of some unit tests I'm working on for the DataTables, and in the future it will give us more export options, and tie into API functionality.
> Tables: add a JsonRenderer class for outputting JSON object data

- CHANGELOG.txt
- modules/Data Updater/data_personal.php
- modules/Students/applicationForm.php
- modules/Students/applicationForm_manage_edit.php
- modules/User Admin/user_manage_add.php
- modules/User Admin/user_manage_edit.php
This is a small tweak to how Privacy settings are displayed. Visually, it's in line with other similar sections: SEN, Agreement, Required Documents, etc.
- In Applications and Data Updater, it adds a heading to that section and some more room for longer descriptive text. 
- In User Admin, it reduces the section to a smaller description text. 
Here's an example (the text might be longer than the average school, but helps illustrate the change).
Application:
User Admin:
> Students: update how the Privacy section is displayed in forms

- CHANGEDB.php
- CHANGELOG.txt
- functions.php
- installer/install.php
- lib/google/index.php
- modules/System Admin/i18n_manage.php
- modules/System Admin/i18n_manage_install.php
- modules/System Admin/i18n_manage_installProcess.php
- modules/System Admin/moduleFunctions.php
- modules/System Admin/updateProcess.php
- preferences.php
- src/Domain/System/I18nGateway.php
- src/Forms/DatabaseFormFactory.php
- src/Forms/FormFactory.php
This PR builds on the i18n features added in #628 to address the issue of installing and updating language files.
Database:
- Adds two fields to the gibboni18n table: `installed` & `version`
Installation:
- Step 2 will download & install the language file for the System Default language, ensuring each new system has at least one language installed.
- Step 2 displays a message if the download failed, so the user can install language files manually.
- The final install step will also check for & set installed to Y any languages that may have been manually installed by adding them to the `i18n/` folder.
Update:
- The update process will find & set installed to Y any languages where the files already exist (populating the Manage Languages list). It will also set installed to N for any files …
> System Admin: handle i18n files during Install and Update

- CHANGELOG.txt
- modules/Timetable/moduleFunctions.php
- modules/Timetable/spaceBooking_manage_add.php
This is a usability tweak for schools using the facility booking options. It adds a quick way to book a period of time relative to the school's timetable, by looking up a room in View Timetable by Facility and clicking a + button to create a booking. This pre-fills the Add Facility Booking page with the details of the selected space & times.
> Timetable: add a bookings button to TT in View Timetable by Facility

- modules/Timetable/moduleFunctions.php
- modules/Timetable/spaceBooking_manage.php
- modules/Timetable/spaceBooking_manage_add.php
- modules/Timetable/spaceBooking_manage_addProcess.php
- modules/Timetable/tt_space.php
- modules/Timetable/tt_space_view.php
- src/Domain/Timetable/FacilityBookingGateway.php
Replaced the target='_blank' with a selective redirect based on the starting point of the booking.
A few other tweaks:
- Only show the + bookings button for future dates & times
- Link back to the facility's timetable from Manage Bookings
- Fix a bug where bookings were not showing up when navigating week by week
> Timetable: redirect back to facility timetable from Add Facility Booking

- login.php
- passwordReset.php
- passwordResetProcess.php
This PR makes two changes to how the canLogin field is handled:
- On login, if the canLogin failure is based on the users role rather than the user account, it uses the more verbose fail9 message: `Your primary role does not support the ability to log into the specified year.` which is less jarring, in the case that access is temporarily turned off.
- Check for canLogin on password reset and fail (with the same messages as login) if the user does not have privileges to login to the system. The logic here is that a user should not be able to go through the whole password reset process if they cannot actually login to the system.
> System: prevent password reset if canLogin is disabled, update error messages

- CHANGEDB.php
- modules/Data Updater/data_updates.php
- modules/Data Updater/report_family_dataUpdaterHistory.php
- src/Domain/DataUpdater/DataUpdaterGateway.php
- src/Domain/DataUpdater/FamilyUpdateGateway.php
This PR reverts the start date logic added in #564 which was causing some inconsistencies in Data Updater reports. The Student & Family Data Updater History reports already filter by student enrollment, which should be sufficient.
I've done some tests to compare the updater history reports to the view that parents see on the My Data Updates page and they appear to be consistent.
This change set also adds some database keys for the Data Updater, Family Adult/Child and Student Enrolment tables. These address the performance issues encountered with the Family Data Updater History, and will generally help speed up any queries involving these tables.
Ross: you'll want to delete the keys you've added before updating, otherwise you'll end up with some unnecessary extra keys on your table. The …
> Data Updater: remove the start date check from required updates logic

- gibbon.php
- src/Contracts/Services/Locale.php
- src/Contracts/Services/Session.php
- src/Gibbon/Locale.php
- src/Gibbon/Session.php
- src/Services/CoreServiceProvider.php
This is part of the Dependency Injection container setup. I've added a [Service Provider](http://container.thephpleague.com/2.x/advanced/#service-providers) class for the core services, which boots the initial services and can also lazyload non-essential ones. As we get up and running there can be separate Web/API/CLI service providers, as things like the API/CLI won't need any of the presentational stuff like forms and templates, but will still need core services.
Also working to decouple some of the transitional classes introduced during refactoring. I've added some interfaces for the Session and Locale classes. These have inadvertently been referenced as concrete implementations here and there in the codebase. I'll submit a future PR that cleans those up and uses interfaces + DI to …
> System: add a CoreServiceProvider for initializing services

- modules/Planner/planner_add.php
Just a couple of minor changes prompted by feedback from professors. Namely, changing the label of the "Name" field to "Name of Lesson Plan". It seems there was some confusion as to what name to put in there! Also, the "Notify all class participants check box" is now checked by default. Some professors were forgetting to check and it seemed that an opt-out approach was less hazardous.
> Planner: Name clarification and pre-checked notifications

- .travis.yml
* To test forward compatibility, added PHP 7.1 and 7.2 to Travis
test.
* Add php 7.1 and 7.2 to Travis CI test target.
* To test forward compatibility.
* Tested with Travis.
> CI: add php 7.1 and 7.2 for CI test

- src/View/AssetBundle.php
- tests/unit/View/AssetBundleTest.php
This PR tweaks the behaviour of sorting in AssetBundle, based on @yookoala's suggestions https://github.com/GibbonEdu/core/pull/653#issuecomment-427787522  
It uses the index of the array internally as a secondary sorting criteria, so that all assets can use a default weight of 0 and still maintain the original order they were added to the array. 
Adds an extra check to the AssetBundle unit tests.
> System: update AssetBundle to handle uasort with a default weight of 0

- modules/Messenger/messenger_manage_edit.php
- modules/Messenger/messenger_manage_editProcess.php
Handles the edge case where a user can post a Quick Wall message but doesn't have access to the `New Message_role` target. In this instance, the Role Category target will appear read-only and the targets will be retained via hidden fields:
> Messenger: add a read-only role category field for Quick Wall messages

- index.php
- resources/templates/welcome.twig.html
- src/View/Page.php
- src/View/View.php
- Moves the template rendering logic from the Page class into a base View class. There are other instances in the codebase where we will want to render templated content, specifically emails.
- Re-orders some of the index logic so that the template variables are assigned before the include() for the page's content is run. This helps ensure the page can render even if a fatal error is encountered in the run-time of the included file (see #659).
- Rewrites the welcome page as a template, moving some more display-related code out of the index.
> System: add a base View class, adjust index.php processing order 

- modules/Behaviour/moduleFunctions.php
This adds an Edit link to the behaviour page generated by `getBehaviourRecord()`, which includes the Student Profile and View Behaviour Records.
Our secondary VP is pretty sure this existed pre-ooification, so I'm not counting it as a new feature.
> Behaviour: add a link to edit behaviour records from Student Profile

- CHANGEDB.php
- modules/Behaviour/behaviour_manage_editProcess.php
There are currently notification events for adding new behaviour records but not for editing them. This adds an `Updated Behaviour Record` event, which is triggered when editing a behaviour record (esp. to add follow-up). It will notify the student's form group tutors, the person who created the record (if someone else edits it), and optionally anyone else subscribed to the event.
As with other notification events, a user can be subscribed to receive all notification, or only those for a particular year group or student. This can help if there's leadership or support staff who wish to receive notifications for a particular purpose.
Uses the `sendNotificationsAsBcc()` method to ideally speed up the sending of multiple emails.
> Behaviour: add a notification event for editing behaviour records

- modules/School Admin/markbookSettings.php
Adds an alert to Markbook Settings when turning on Enable Column Weighting if the current Default Assessment Scale is not percentage.
Related forum post: https://ask.gibbonedu.org/discussion/comment/4668/#Comment_4668
> School Admin: add an alert to Enable Column Weighting based on Default Assessment Scale

- src/Domain/Finance/InvoiceGateway.php
**Bug Fix**
Looks like the filter needed to account for checking the `gibbonFinanceFeeCategoryID` vs the `gibbonFinanceInvoiceFee` table post-separation, and `gibbonFinanceFee` table pre-separation/issuing of the invoice.
> Finance: fix filtering of Fee Category for issued invoices

- CHANGELOG.txt
- modules/Attendance/report_studentHistory.php
- src/Forms/Traits/MultipleOptionsTrait.php
**Bug Fix**
This appears to be caused by PHP 7.1+ no longer implicitly converting an empty string to an array:
http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.empty-string-index-operator
in < PHP 7.1, the following code would run:
```php
$options = '';
$options['foo'] = 'Bar';
echo is_array($options)? "Yep, it's an array" : "Is not an array!! Commence breaking stuff...";
```
After 7.1 it'll generate an error. I've looked for other instances in the parent-child selectors that might break and didn't see any, but we will certainly need to keep an eye out for these backwards-incompatible changes.
I've also added an extra check to MultipleOptionsTrait to be more forgiving with empty values passed to `fromString` and `fromArray` (because they can come from many …
> Attendance: fix PHP 7.1+ exception in parent view of Student History

- .gitlab-ci.yml
- .travis.yml
- composer.json
- tests/config/envs/.gitignore
- tests/config/envs/gitlab_ci.yml
- tests/install/InstallCept.php
This PR aims to make it easier to test with other CI platform. In particular, this PR
* extracts CI test from .travis.yml to composer.json. And then;
* implemented a Gitlab CI configuration as a demonstration. And; 
* some minor improvement for debugging codeception install script.
The workflow of Gibbon development depends heavily on the Github/Travis combo. This make it hard for developers to work on this project with other platform. And make it hard to, potentially, migrate to other Git hosting platform.
It is much more flexible to have CI-platform-independent tests that could even work locally. Like this:
```
composer test
```
Besides testing on Travis, the code in PR is also tested with [Gitlab CI](https://gitlab.com/yookoala/gibboneducore/pipelines) to make sure …
> Tests: Gitlab CI compatible tests

- CHANGELOG.txt
- modules/Markbook/markbook_edit_addMultiProcess.php
- modules/Markbook/markbook_edit_addProcess.php
- modules/Markbook/markbook_view_allClassesAllData.php
- modules/Markbook/moduleFunctions.php
- modules/Markbook/src/markbookView.php
- src/Domain/Markbook/MarkbookColumnGateway.php
- src/Domain/Planner/PlannerEntryGateway.php
Adds a search option, inline with the other filters in the teacher-view of the markbook. This PR also sets up the gateway classes for MarkbookColumn and PlannerEntry. It's nowhere near a complete refactoring (that's still on the list), just a step in the right direction. Also marked a few methods as deprecated and fixed a default attainmentWeighting value.
Teachers using markbook types may wish to filter the markbook to see only columns of one type (Formative vs. Summative, or Homework vs Tests). Rather than limiting it to just this purpose, I've added this feature as a text search which looks at the name, description and type fields.
> Markbook: add a search option to the filters in Markbook View

- index.php
- modules/Students/report_graph_studentEnrolment.php
- src/UI/Chart/Chart.php
- src/UI/Chart/ChartDataset.php
- tests/unit/UI/Chart/ChartDatasetTest.php
- tests/unit/UI/Chart/ChartTest.php
Adds some basic PHP classes to make creating & rendering chart.js charts easier.
Refactors the Student Enrolment Trends chart.
Example usage:
```
$chart1 = Chart::create('roles', 'doughnut')
->setTitle(__('Active Users by Role Category'))
->setOptions(['height' => '250', 'legend' => false])
->setLabels($chartData);
$chart1->addDataset('pie')
->setData($chartData);
$chart1->render();
```
> System: add a Chart class

- fullscreen.php
- modules/Markbook/markbook_view_rubric.php
- modules/Rubrics/moduleFunctions.php
- modules/Rubrics/rubrics_view_full.php
- src/UI/Chart/Chart.php
Updates the recently added rubric visualization.
Also updates the Chart class to handle embedding ad-hoc functions in the chart configuration. It does this by adding an `addFunction()` method to the class, which returns a string identifier used internally to string-replace the function after the json_encode step, because otherwise the function would be wrapped in "".
Eg:
```
'callback' => $chart->addFunction('function(tickValue, index, ticks) {
return Number(tickValue).toFixed(1);
}'),
```
The above function has been added to the rubric chart to fix the chart labels. Looks like the bug with the polar area float precision has been fixed in a more recent version.
> Rubrics: refactor visualisations to use the Chart class

- CHANGELOG.txt
- index.php
- modules/System Admin/update.php
- resources/templates/index.twig.html
- themes/Default/css/main_rtl.css
- Adds the theme `main_rtl.css` file contributed by Haim Hillel 👍 
- Adds the HTML `dir="rtl"` attribute to enable browser-based rtl rendering
- Commits the most recent i18n submodule changes to the core
- Removes a `getSystemSettings()` call from update.php which was causing the session to overwrite the personal language selection
> System: improve support for right-to-left languages

- themes/Default/css/main.css
- themes/Default/css/main_rtl.css
The main menu css was using `left: -999em;/left: 0;` to hide menu items. Switched it to `display: none;/ display: block;`, which fixes the visual glitch in the menu for rtl languages. Also right-aligns the text inside the menu.
> System: fix position of main menu items for RTL languages

- modules/.gitignore
**Nitpicking**
* Use a whitelist based structure for `modules/.gitignore`.
* Ignore everything except for the core modules.
Kind of a nitpicking. But it seems strange for the current [`modules/.gitignore`](https://github.com/GibbonEdu/core/blob/ca259435be1a8de70d7340b9f643315122f4e819/modules/.gitignore) to specifically only ignore one optional module, "Query Builder".
For the convenience of developing and committing live installation, its seem to be reasonable to ignore everything except for the core modules.
> Modules: update .gitignore

- CHANGEDB.php
- CHANGELOG.txt
- installer/install.php
- modules/Data Updater/data_personal.php
- modules/Messenger/messenger_post.php
- modules/Staff/applicationForm.php
- modules/Staff/applicationForm_manage_edit.php
- modules/Students/applicationForm.php
- modules/Students/applicationForm_manage_edit.php
- modules/User Admin/user_manage_add.php
- modules/User Admin/user_manage_edit.php
- publicRegistration.php
- src/Forms/FormFactory.php
This PR updates the FormFactory to apply the max length to all email fields, and removes the individual max lengths from existing fields. This will help standardize the forms, as there's many places where an email can be copied from one form to another (application acceptance, data updaters, etc.). Also applies the increased limit of 75 chars to email fields in the database.
> Forms: increase the max email length to 75 chars

- docs/CODE_OF_CONDUCT.md
Our community may yet be small but it's growing. Adding a code of conduct is a recommended step for open source projects. This one is provided by the great folks at https://www.contributor-covenant.org under CC BY 4.0
> Project: add a code of conduct to the project docs

- modules/Library/library_browse.php
- modules/Library/library_import.php
- modules/Library/library_lending.php
- modules/Library/library_lending_item.php
- modules/Library/library_lending_item_edit.php
- modules/Library/library_lending_item_renew.php
- modules/Library/library_lending_item_return.php
- modules/Library/library_lending_item_signout.php
- modules/Library/library_manage_catalog.php
- modules/Library/library_manage_catalog_add.php
- modules/Library/library_manage_catalog_delete.php
- modules/Library/library_manage_catalog_duplicate.php
- modules/Library/library_manage_catalog_edit.php
- modules/Library/report_catalogSummary.php
- modules/Library/report_studentBorrowingRecord.php
- modules/Library/report_viewOverdueItems.php
**Refactor**
See #696
* Locally
* Travis
> Library: refactor breadcrumbs

- composer.json
Extremely minor issue. The composer.json declared that PHP version supported is `"^5.5 || ^7.0"`, but it is announced that Gibbon will only support PHP 7.0 and above. This PR simply changed that.
> Composer: officially remove PHP 5.5

- modules/Markbook/markbook_edit.php
- modules/Markbook/markbook_edit_add.php
- modules/Markbook/markbook_edit_copy.php
- modules/Markbook/markbook_edit_data.php
- modules/Markbook/markbook_edit_edit.php
- modules/Markbook/markbook_edit_targets.php
- modules/Markbook/markbook_view_allClassesAllData.php
- modules/Markbook/weighting_manage.php
- modules/Markbook/weighting_manage_add.php
- modules/Markbook/weighting_manage_edit.php
**Refactor**
* use __() to replace previously used strtr() logics.
* New translation string: "`View {courseClass} Markbook`".
* New translation string: "`Edit {courseClass} Markbook`".
* New translation string: "`Manage {courseClass} Weightings`".
* see #701 and #709.
* Travis
> Markbook: refactor breadcrumb translations

- modules/Planner/planner.php
- modules/Planner/planner_add.php
- modules/Planner/planner_bump.php
- modules/Planner/planner_edit.php
- modules/Planner/planner_unitOverview.php
- modules/Planner/planner_view_full.php
- modules/Planner/planner_view_full_post.php
- modules/Planner/planner_view_full_submit_edit.php
**Refactor**
* use __() to replace previously used strtr() logics.
* New translation string: "`Planner for {classDesc}`".
* New translation string: "`View Lesson Plan for {classDesc}`".
* see #701 and #709.
* Travis
> Planner: refactor breadcrumb translations

- modules/Data Updater/data_personal_manage_editProcess.php
- modules/User Admin/user_manage_editProcess.php
When a student's privacy changes it triggers an Updated Privacy Settings notification. This PR updates the notification text to include what the change in privacy is.
In this case, we were finding that the notification recipients were either confused by what the notification meant, or not always sure where to check what the updated privacy is. Since it's important to ensure the appropriate people have this info, I've tweaked the notification to include the updated privacy value.
> User Admin: add privacy value to Updated Privacy Settings notification

- src/Forms/DatabaseFormFactory.php
- src/Forms/FormFactory.php
- src/Forms/Input/Range.php
- src/UI/Chart/Chart.php
A couple minor tweaks and changes to the forms and charts, aslo adds a Range slider as a input type, and adds an onTooltip method for charts to customize the tooltip data via the chart.js api
> Forms: add Range input type, Charts: add onTooltip method

- functions.php
**Refactor**
* The class in `functions.php` is not referenced in v17.0.00 core and any of the latest version of open sourced modules. It is safe to remove.
Clean up code base.
* Locally
* Travis
> Functions: remove obsoleted ExportToExcel class

- modules/Students/report_students_byRollGroup_print.php
- modules/Students/student_view_details.php
- publicRegistrationProcess.php
**Refactor**
* remove all usage of the function `getAge()` in the codebase.
There is only a few usage left of `getAge()` in the core. Removing them helps to lift dependencies from it and make it ready to be removed.
* Locally
* Travis
> Modules: remove uses of getAge

- .gitignore
- CHANGELOG.txt
- functions.php
- modules/Messenger/messenger_postProcess.php
- src/Comms/GibbonMailer.php
Deprecated getGibbonMailer and call GibbonMailer wrapper to remove duplicate code.
PHPMailer wrapper updated for use with GMAIL, which requires SMTPSecure = 'ssl'
Refactored Messenger Post Process to use GibbonMailer.
**Bug Fix | New Feature**
Changes are made to remove duplicate code for use of PHPMailer whilst maintaining backwards compatibility.  I added a @deprecated tag for development, and also added a E_USER_DEPRECATED throw to be logged when this old code is used.  Check php_error log for results.
> [30-Nov-2018 11:15:55 Australia/Sydney] PHP Deprecated:  getGibbonMailer method is deprecated and replaced by Gibbon\Comms\GibbonMailer class.   in F:\websites\crayner\Gibbon\functions.php on line 4648
> [30-Nov-2018 11:15:55 Australia/Sydney] PHP Stack trace:
> [30-Nov-2018 11:15:55 …
> Deprecated getGibbonMailer and call GibbonMailer wrapper to remove duplicate code.

- CHANGELOG.txt
- modules/Finance/budgetCycles_manage_add.php
- modules/Finance/budgetCycles_manage_edit.php
Fixed the bug that prevented saving the value of the field "status" in the table "gibbonFinanceBudgetCycle" when the current Gibbon language is other than English 
If the current Gibbon language is other than English, DB don't save the values of the field "status", because this field is ENUM('Past', 'Current', 'Upcoming')
Local in languages Portuguese and Italian
> Fixed bug internationalization and indentation adjustment

- functions.php
While translating additional modules outside the core, it becomes a bit clunky to include the module name for each string, especially with it now being an array parameter. Since the system already knows the name of the current module for any given page, it'd be pretty easy to include this automatically.
With this change, the following:
`__('Import From File', [], ['domain' => 'Data Admin'])`
is identical to:
`__d('Import From File')`
This can also help to ensure module strings are not accidentally included in the core, as the xgettext script won't be looking at `__d()` functions.
@yookoala What do you think?
> System: add a function to help with module translations

- modules/Departments/department.php
A small tweak to the list of courses in the departments module. It removes courses from the list that either don't have any classes, or don't have any year groups selected. In this case, they could be new courses not setup yet, or possibly not offered in the current year. Any knock-on effects from this change?
_Edit: caught a missing translation function_
> Departments: don't display courses with no classes or no year groups

- functions.php
- index_notification_ajax_alarm.php
- modules/System Admin/alarm.php
Fixes a small bug where the alarm window, once triggered, would turn the screen dark but wouldn't popup for several seconds (until the notifications refreshed in the background). This would also happen each time after navigating to a new page.
The fix: since the index_notification_ajax script handles the triggering of the alarm, the functions.php code was tweaked to cause an immediate notification refresh. Beyond that, I resisted the temptation to refactor any of the other parts of these scripts 😁 
Also fixes two random javascript errors that were showing up in the console.
> System: fix a delay in the alarm window popup

- CHANGELOG.txt
- cli/behaviour_letters.php
- cli/planner_parentWeeklyEmailSummary.php
- modules/Finance/invoices_manage_editProcess.php
- modules/Finance/invoices_manage_issueProcess.php
- modules/Finance/invoices_manage_processBulk.php
- modules/Finance/invoices_payOnlineProcess.php
- modules/Messenger/messenger_manage_report_processBulk.php
- modules/Staff/applicationFormProcess.php
- modules/Staff/applicationForm_manage_accept.php
- modules/Students/applicationFormProcess.php
- modules/Students/applicationForm_manage_accept.php
- passwordResetProcess.php
Updates the remaining uses of getGibbonMailer in the core with the Mailer class, via the DI container.
Tested locally & with Travis CI.
> System: replace getGibbonMailer function calls with Mailer class

- modules/Attendance/attendance_take_byCourseClass.php
The logic of the error message states that the date SHOULD BE IN THE FUTURE, but the TEST does the opposite.  The test is correct.
Bug Fix
> Incorrect Error Message Logic in Attendance Course Class

- CHANGELOG.txt
- lib/google/index.php
- modules/Timetable/moduleFunctions.php
Google is shutting down their Google+ APIs by March 7, 2019: https://developers.google.com/+/api-shutdown
This PR replaces the `plus.me` scopes with the basic `email` and `profile` scopes recommended for [Google sign-in](https://developers.google.com/identity/protocols/googlescopes#google_sign-in). It looks like the client library we use has already not been accessing the Google+ API (based on console usage data), so this change shouldn't have an effect on end users. At the most, they may be asked to re-accept the Google consent screen.
> System: update Google login scopes to remove plus.me

- CHANGELOG.txt
- src/Tables/Columns/Column.php
Method for columns that require the translation, and update the columns where this is applicable, for example:
schoolYear_manage.php
gradeScales_manage.php
attendanceSettings.php
fileExtensions_manage.php
schoolYear_manage.php - line 63
before: $table->addColumn('status', __('Status'));
after:  $table->addColumn('status', __('Status'))->isTranslatable();
> Render tables - Support to internationalization - v18

- CHANGEDB.php
- CHANGELOG.txt
- modules/Planner/curriculumMapping_outcomesByCourse.php
- modules/Planner/moduleFunctions.php
- modules/Planner/planner_duplicateProcess.php
- modules/Planner/planner_view_full.php
- modules/Planner/planner_view_full_smartProcess.php
- modules/Planner/unitsProcessBulk.php
- modules/Planner/units_duplicateProcess.php
- modules/Planner/units_edit.php
- modules/Planner/units_editProcess.php
- modules/Planner/units_edit_copyBackProcess.php
- modules/Planner/units_edit_copyForwardProcess.php
- modules/Planner/units_edit_deploy.php
- modules/Planner/units_edit_deployProcess.php
- modules/Planner/units_edit_smartBlockifyProcess.php
- modules/Planner/units_edit_working.php
- modules/Planner/units_edit_workingProcess.php
- modules/Planner/units_edit_working_copyback.php
- modules/Planner/units_edit_working_copybackProcess.php
The current Smart Block setup is bloated, and so to ease OOification, and to remove unneeded code, the little (never?) used feature of mapping unit outcomes to lesson outcomes via Smart Blocks is removed by this PR.
> Planner: removed Smart Block to Lesson outcome mapping

- CHANGEDB.php
- CHANGELOG.txt
- modules/System Admin/thirdPartySettings.php
- modules/System Admin/thirdPartySettingsProcess.php
- src/Comms/Mailer.php
Adds a new SMTP Encryption option under Third Party Settings, defaulting to the same behaviour we have currently. This allows a system admin to select the specific SSL or TLS setting they need, based on their mail server. The 'none' option is available for the rare case that a mail server requires TLS/SSL disabled.
Via the forum post:
https://ask.gibbonedu.org/discussion/2388/send-email-via-amazon-ses-service-failed-due-to-ssl-and-tsl-field
More info about the `SMTPSecure` and `SMTPAutoTLS` settings here:
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#check-you-have-the-openssl-extension
> System: add an option to explicitly set PHPMailer SMTPSecure

- resources/imports/timetableComplete.yml
- src/Data/ImportType.php
- src/Data/Importer.php
This import definition aims to replicate the same functionality as the Import option in Timetable Admin. It uses the somewhat-complex syntax for multi-table imports to allow:
- Create courses if they don't already exist
- Creates classes if they don't already exist
- Adds teachers to classes
- Adds the timetable day/row/column schedules
- Assigns the facility to the timetabled class
The only thing it doesn't have is the additional feedback messages that the current Import tool provides, although it does provide more pre-import feedback via the Dry Run step. I've tested it with demo data so far, will test it with some actual timetables for our next school year which are being made in the next month or so.
Also tweaks the ImportType and Importer class to handle dot notation for column …
> System Admin: add import type for Timetable - Complete 

- src/Forms/Input/TextField.php
- src/Forms/Traits/InputAttributesTrait.php
- src/Tables/Action.php
A follow-up to [a previous discussion](https://github.com/GibbonEdu/core/pull/787) about getter/setter naming consistency, this PR renames some methods currently used in the form and table classes. For backwards compatibility it leaves the current methods in place, marked with a `@deprecated` doc tag. After this is merged I'll catch all the current instances in the core, and we can aim to catch additional modules as part of our ongoing refactoring.
`isUnique` → `uniqueField`
`isDisabled` → `disabled`
`isRequired` → `required`
`isModal` → `modalWindow`
`isDirect` → `directLink`
> Forms, Tables: rename setters that start with isXXX for code consistency

- lib/jquery-tokeninput/ChangeLog.md
- lib/jquery-tokeninput/README.md
- lib/jquery-tokeninput/src/jquery.tokeninput.js
- src/Forms/Input/Finder.php
This PR updates the jQuery Token Input library: http://loopj.com/jquery-tokeninput/  This enables us to use the resultsFormatter & tokenFormatter parameters, which allows passing a javascript function to control how the tokens and results are formatted. Using these, we have more control over the tokens, such as adding thumbnails of user photos to the results, displaying multi-line results, etc. Part of an upcoming people-finder PR.
> Forms: add resultsFormatter & tokenFormatter methods to Finder input

- src/Services/Format.php
Updates the `dateReadable`, `dateTimeReadable` and `dateRangeReadable` methods to use `strftime`, which handles localization of date strings: http://php.net/manual/en/function.strftime.php 
Also adds a `relativeTime` method, which aims to provide an easy-to-use, translatable way to display simple time strings like 1 hr ago, 3 mins from now, etc.
@leofreitas Let me know what you think. We should be able to use something like `Format::dateReadable($date, '%b');` to properly handle the date strings in `modules/Attendence/attendence.php`. By using this class, in the future we should be able to enable more customization of preferred date formats for admins, by pulling in the system-wide preferred date formats from settings.
> System: update date and time localization in Format class

- gibbon.php
- resources/templates/components/form.twig.html
- src/Forms/Form.php
- src/Forms/FormRenderer.php
- src/Forms/View/FormRendererInterface.php
- src/Forms/View/FormView.php
- src/Services/CoreServiceProvider.php
- src/Services/ViewServiceProvider.php
- tests/unit/Forms/FormTest.php
This is part of the re-wiring to get setup for mobile-responsive layouts in v18. The Form classes predate the Twig templating and DI container, so we can now update them to remove the FormRenderer class and handle the HTML output using a View class. This is done through the new `FormView` class and `form.twig.html` template.
This PR also adds a `ViewServiceProvider` class, which will be the home of view-related services. It sets up the service provider to create Forms and inject their necessary dependencies.
There is a somewhat sneaky use of a `global` here, as a transitional step for the `Form::create` method. I did this in part to keep the scope of this PR small: I'll put in some follow-up PRs to replace the static `Form::create` method used by our many forms with the DI …
> Forms: update the Form class to use a template-based renderer

- modules/Activities/activities_attendance.php
- modules/Activities/activities_payment.php
- modules/Activities/css/module.css
- modules/Individual Needs/in_edit.php
- modules/System Admin/css/module.css
- modules/System Admin/i18n_manage.php
- modules/System Admin/import_run.php
- modules/Timetable Admin/courseEnrolment_sync_edit.php
- modules/Timetable Admin/courseEnrolment_sync_run.php
- modules/Timetable Admin/course_rollover.php
- modules/Timetable Admin/ttDates.php
- modules/User Admin/permission_manage.php
- themes/Default/css/main.css
Cleaning some things up to get ready to introduce templating for the Form class. This removes the `setWrapper()` calls, which were somewhat hack-ish and used for forms which have a blank layout and contain nested tables. It replaces the wrapper method calls with the `blank` css class, from the original main.css file. Also contains some small tweaks to the activity attendance page for displaying the double-scrollbar.
> Forms: remove calls to setWrapper

- fullscreen.php
- modules/Markbook/markbook_edit_data.php
- modules/Markbook/markbook_view.php
- modules/Rubrics/rubrics.php
- modules/Rubrics/rubrics_view.php
- modules/Students/student_view_details.php
- resources/templates/components/form.twig.html
- resources/templates/finder.twig.html
- resources/templates/fullscreen.twig.html
- resources/templates/head.twig.html
- themes/Default/css/main.css
This PR adds some extra styles to help the Thickbox size more reasonably on small screens.
It also helps address the XMLHTTPRequest error seen on newer browsers by removing the additional ajax-loading of scripts in a thickbox window. The caveat is that scripts needed in a thickbox will have to be loaded by their parent widow, so this PR updates the Markbook to load the Chart script for rubrics.
Also adjusts the flexbox form rendering via tempalte to not apply to non-standard tables. The rubric looked very artistic in it's non-linear form, but not as usable as I expect teachers would like : )
> Templates: responsive Thickbox update

- functions.php
- resources/templates/components/editor.twig.html
- themes/Default/css/main.css
A follow-up PR to #827, which moves the display code for the TinyMCE editor out of functions.php into a Twig template, and updates the editor tools to be mobile-friendly.
> Templates: responsive TinyMCE rich text editor 

- modules/Attendance/attendance_take_byCourseClass.php
- modules/Attendance/attendance_take_byRollGroup.php
- modules/Attendance/css/module.css
- resources/templates/components/form.twig.html
- src/Forms/Input/CustomBlocks.php
- src/Forms/Layout/Grid.php
Another follow-up to #827. This PR updates the form Grid class to make use of flexbox, and applies some responsive breakpoints via Tailwind to the attendance pages. The result is the Take Attendance actions are now usable on all device sizes:
> Attendance: update the Take Attendance grid to use responsive breakpoints

- installer/install.php
- resources/templates/index.twig.html
- resources/templates/install.twig.html
- src/View/Page.php
So... the installer might be a little broken at the moment 😅 well... it works, but it looks wonky, which was caused by creating some new css files and starting to delete css from the theme's main.css file.
I took the opportunity to update the installer to use a template for rendering, extended from the `index.twig.html` template. This will help ensure that as we update and style things, the installer will also be updated. This will help future theme developers too. Currently, the HTML had been hard-coded onto the page and remained fairly static.
Be sure to hide whitespaces when viewing the changes, there's not a lot of changes to the installer itself, this PR mostly just removes the chunk of HTML from the top and bottom of the page and replaces it with a Page object to render from a …
> System: update the installer to use a template for HTML rendering

- report.php
- resources/templates/report.twig.html
- themes/Default/css/main.css
The `report.php` page is one the the last places still outputting the page layout manually. This PR updates the reports to use a `report.twig.html` template. Also deletes the now-unused styles from `main.css`.
> Templates: update the printable report page to use a template

- CHANGELOG.txt
- modules/System Admin/systemCheck.php
- modules/System Admin/systemCheck_clearCacheProcess.php
Template cache is cleared on update, and Development systems continuously reload the cache, so for the most part admins don't need to worry about it. However for Production systems running cutting edge code, it is handy to be able to quickly clear the cache folder after uploading changes. This PR adds a Clear Cache button under the System Check page.
> System Admin: add a clear cache option under System Check

- CHANGELOG.txt
- modules/Rubrics/moduleFunctions.php
- modules/Rubrics/src/Visualise.php
- modules/Rubrics/src/visualise_saveAjax.php
- src/UI/Chart/Chart.php
This PR separates out the rubric visual into an object, which can be invoked to display normally (e.g. within the rubric) or to export as a PNG image, via ajax, to the file system.
ICHK are moving towards including a visual rubric overview in reports, and this is a first step. 
Locally
> Rubric Visualisation Image Export

- src/Domain/QueryableGateway.php
- src/Domain/Traits/TableAware.php
So-far we've been using the `Aura\SqlQuery` library in the background to power the pagination, search and filters in DataTables. This PR updates the QueryableGateway and TableAware trait to enable some additional functionality from the library: simple inserts, updates, deletes and selects. 
Many Gateways relate one-to-one to a database table, so using the query builder methods provides a simplified way to access the basic CRUD operations without writing additional SQL.
```php
// For example, deleting a user:
$data = array('gibbonPersonID' => $gibbonPersonID);
$sql = "DELETE FROM gibbonPerson WHERE gibbonPersonID=:gibbonPersonID";
// Becomes:
$userGateway->delete($gibbonPersonID);
```
```php
// Getting a record
$data = array('gibbonPersonID' => $gibbonPersonID);
$sql = "SELECT * FROM …
```
> System: enable use of Aura\SqlQuery classes for basic CRUD operations

- CHANGELOG.txt
- src/Domain/Students/StudentGateway.php
A small fix. The staff `type` field allows selecting general "Teaching", "Support" types, as well as specific roles. This was causing the particular query used for View Timetable by Person to not list some staff if their type was set a role, eg: "Teacher".
> Timetable: fix some staff not showing up in View Timetable by Person

- CHANGEDB.php
- CHANGELOG.txt
- modules/School Admin/rollGroup_manage_add.php
- modules/School Admin/rollGroup_manage_edit.php
Another small change. Currently, the Roll Group names are limited to 10 characters, which isn't quite enough for the word "Kindergarten" 😄 Abbreviations work fine in the `nameShort`, but some schools prefer the full word in the `name` field.  Similarly, even with abbreviations, the 5 char limit on short names can be a bit restrictive. I've bumped the field lengths up a bit, but not so much that should should cause any display issues.
> School Admin: increase field lengths for Roll Group name and nameShort

- src/Database/Connection.php
- src/Domain/Messenger/GroupGateway.php
- src/Domain/RollGroups/RollGroupGateway.php
- src/Domain/User/UserGateway.php
These are part of a set of upcoming changes, I split them out to try and keep the future PR size sane.
The `Connection::update` method was using an `affectingStatement` for the return value, which only returns true if the update actually changed values. This fix changes the return value to a `statement` so it's always true if the update was successful, regardless of values changed (eg: submitting an Edit form even with no changes shouldn't fail).
> System: fix Connection::update return value, add some method to Gateway classes

- gibbon.php
- index.php
- lib/google/index.php
- modules/Timetable/moduleFunctions.php
- src/Services/GoogleServiceProvider.php
When we access a Google service via one of the classes like `Google_Service_Calendar`, we first need to instantiate the `Google_Client` class and configure it, including adding scopes. Currently this code has been duplicated in a couple different locations. As we add any additional features that interact with Google, the code needs a standardized way to retrieve and configure the client, as well as refresh any expired tokens.
This PR adds a `GoogleServiceProvider` class, which enables us to grab a fully-configured Google_Client object from the DI container. It also updates the three locations in the code currently accessing Google services.
> System: add a GoogleServiceProvider class for accessing google APIs 

- CHANGELOG.txt
- modules/Attendance/attendance_take_byPerson.php
- src/Domain/Attendance/AttendanceLogPersonGateway.php
- src/Tables/DataTable.php
Continuing the attendance changes started in #860 and #863
This PR updates the attendance logs displayed per student.
If `countClassAsSchool` is set to `N`, then the attendance logs are separated into two tables. The class attendance log is ordered by the timetable, and helps highlight gaps where attendance wasn't taken:
If `countClassAsSchool` is set to `Y`, all attendance logs are displayed together:
> Attendance: refactor the attendance log table in Attendance by Person

- modules/Departments/departments.php
- resources/templates/components/dataTable.twig.html
- resources/templates/components/gridTable.twig.html
- src/Tables/View/GridView.php
Fixes a bug from my GridView refactor and tweaks the blank slates a bit. Currently, if a school has Learning Areas but no Administration departments defined, the learning areas were showing up twice. This was from the data present in the renderer object when the second table was rendered.
Blank slate (rather than alert-style message):
> Departments: fix duplicate list of departments

- modules/System Admin/notificationSettings_manage_edit.php
Updated table name gibbonperson to gibbonPerson
Unix-based systems are case-sensitive and in this case generates a warning
Warning: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gibbonperson' doesn't exist
Local
> Fixed table name gibbonperson to gibbonPerson

- themes/Default/css/main.css
In Languages that the name of day has three chars, the calendar needs be greater
> Adjusted the size of Datepicker Calendar

- CHANGELOG.txt
- modules/Behaviour/behaviour_manage_add.php
- modules/Behaviour/behaviour_manage_addMulti.php
- modules/Behaviour/behaviour_manage_addMultiProcess.php
- modules/Behaviour/behaviour_manage_addProcess.php
- src/Domain/Students/StudentNoteGateway.php
This new feature adds a Copy to Notes checkbox to the bottom of the Add and Add Multiple behaviour record screens.
Sometimes Behaviour incidents spiral into something bigger, which requires the creation of a Note in the student profile. Rather than manually copying content to a new note, this automates it.
Locally
>  Behaviour: new Copy To Notes feature

- CHANGELOG.txt
- modules/Students/student_view_details.php
For various historical reasons, Tutors and Learning Support Assistants aren’t listed with teachers in the Student’s Teachers of the student profile. This PR unifies everything into a single list.
Some people weren't getting emails they ought to have.
> Students: improved display of Teachers' emails in student profile

- index.php
Page generated by index.php has an error in the console log 'Uncaught SyntaxError: Unexpected token <' due to empty 'jquery-date' script for "en-US" locale caused by the fix from #769 
The empty script attached generated a <script> tag with src back to the site url where the main page is being loaded as a script hence causing the error.
> Fix 'Uncaught SyntaxError: Unexpected token <' caused by empty script on 'en-US' locale

- CHANGEDB.php
- CHANGELOG.txt
- modules/Attendance/attendance_take_byCourseClass.php
- modules/Attendance/attendance_take_byCourseClassProcess.php
- modules/Attendance/attendance_take_byRollGroup.php
- modules/Attendance/attendance_take_byRollGroupProcess.php
- modules/School Admin/attendanceSettings.php
- modules/School Admin/attendanceSettingsProcess.php
- modules/School Admin/attendanceSettings_manage_add.php
- modules/School Admin/attendanceSettings_manage_addProcess.php
- modules/School Admin/attendanceSettings_manage_edit.php
- modules/School Admin/attendanceSettings_manage_editProcess.php
- src/Domain/Attendance/AttendanceCodeGateway.php
This PR further refines the available settings for attendance by adding two options:
- A setting to enable the first class attendance taken in a day to optionally count as school-wide attendance.
Which enables a checkbox on Take Attendance by Class:
- An option to disable the prefilling of an attendance code, applied to Present - Late by default.
The notable code and database changes in this PR are:
- Added and implemented a `recordFirstClassAsSchool` setting.
- Added a `prefill` column to the `gibbonAttendanceCode` table.
- Added a `gibbonRollGroupID` column to the `gibbonAttendanceLogPerson` table. This was necessary to track the roll group for each log, so the difference between recorded and prefilled logs could be determined.
- Updated the prefill logic for Take Attendance by Class …
> Attendance: add more options to control attendance prefilling

- modules/Markbook/markbook_view_allClassesAllData.php
Add new feature to sort markbook columns by date. A modal box is display when reset order button is pressed, giving the option to sort by **entry order** OR **date**
Currently pulling the columns from different pages is not possible.
Some teacher enter markbook entries in different orders where sorting by date would allow them to see the flow.
Besides that if bulk import of markbook columns is done(did it manually thru SQL - hopefully a new feature), teacher would be able to slot in new markbook columns and arrange it by date. 
only on v18
> Markbook: Add sorting by date

- CHANGELOG.txt
- modules/System Admin/notificationSettings_manage_edit.php
- src/Domain/System/NotificationGateway.php
- Fixes an issue where notification events were sending emails to non-Full users (oops!)
- Adjusts the handling of Permission Required to allow for grouped actions.
- OOifies the Edit Subscribers table, highlights left users so they can be removed.
> System Admin: fix Notification Events to only send to Full users

- CHANGELOG.txt
- modules/Attendance/src/StudentHistoryData.php
- resources/templates/components/studentHistory.twig.html
- src/Domain/Attendance/AttendanceLogPersonGateway.php
Currently, student attendance history does not display class attendance when countClassAsSchool is N. This means taking class attendance for informational purposes is less useful. Even though it's not prefilled or counted as school attendance, it's still handy to be able to see that it exists. 
This PR:
- Highlights days as Incomplete when school attendance has not been taken, but class attendance has. Previously, these showed as No Data, even when there was class data.
- Adds a list of class attendance below school attendance if countClassAsSchool is N.
- Labels and visually separates School Attendance and Class Attendance.
- Enables the badge count when attendance logs differ from the end-of-day status.
- No change if countClassAsSchool is Y.
Even when class …
> Attendance: update Student History to display class attendance

- CHANGELOG.txt
- modules/Activities/activities_manage.php
- src/Domain/Activities/ActivityGateway.php
In large schools with many year levels, it can become hard to manage a large number of activities. This filter helps those who manage activities to quickly filter the list down by year group. It also adds the max participant count next to the enrolment count, so it's easier to see available spaces.
> Activities: add a Year Group filter in Manage Activities

- CHANGELOG.txt
- modules/Messenger/groups_manage.php
- modules/Messenger/groups_manageProcessBulk.php
- src/Domain/Messenger/GroupGateway.php
Adds a bulk action to Manage Groups so they can be selectively copied to future years. Currently, groups are tied to a particular school year, and it's handy to be able to bump them forward to a new year, particularly when they're being used in conjunction with the staff absence notification feature.
Locally.
> Messenger: add a Copy to Next Year bulk-option for Manage Groups

- CHANGELOG.txt
- modules/Staff/absences_manage_deleteProcess.php
- src/Domain/Staff/StaffCoverageDateGateway.php
- src/Domain/Staff/StaffCoverageGateway.php
Bug fix. If a staff absence is removed the coverage attached to that absence also needs cleaned up so there's no orphaned records.
> Staff: fix Delete Staff Absence to also delete any related coverage

- CHANGELOG.txt
- modules/Staff/report_subs_availability.php
- modules/Staff/report_subs_availabilityWeekly.php
- modules/Staff/src/Tables/CoverageMiniCalendar.php
- src/Domain/Staff/StaffCoverageGateway.php
- src/Domain/Staff/SubstituteGateway.php
The current Substitute Availability page only shows one day at a time. This PR updates it to have two views: a Daily View and a Weekly View. It also updates both views to have a fine-grained visual of the time a sub is booked and available for.
In this PR:
- Adds a CoverageMiniCalendar class to handle the display of availability by time.
- Adds a Weekly View button to the original Substitute Availability report:
- Adds a Weekly View page, with the option to switch back to Daily View:
Booking and managing subs in a large school can be hard! This PR aims to give school admins a more visual view of substitute coverage so they can easily spot availability.
> Staff: add a Weekly View and Daily View to Substitute Availability

- CHANGELOG.txt
- cli/attendance_dailyIncompleteEmail_byClass.php
This PR splits the class attendance from the `attendance_dailyIncompleteEmail.php` script into a separate script `attendance_dailyIncompleteEmail_byClass.php`. This enables schools to schedule these CLI scripts to run at different times of the day. Generally, class attendance notifications must run at the end of the day to catch all classes, and form group attendance could optionally run earlier in the day.
Added under the "Changes With Important Notices" section in the CHANGELOG to let admins know to update their CLI schedule (if needed).
> System: split Daily Attendance CLI into two separate scripts

- CHANGELOG.txt
- modules/User Admin/user_manage_password.php
It's not always clear why a user cannot login. This PR aims to make admins life a bit easier by adding a Login Troubleshooting section to the Reset Password page. It checks and reports on the various reasons why a user can or cannot login.
> User Admin: add a Login Troubleshooting section to Reset Password page

- CHANGELOG.txt
- modules/Attendance/attendance_future_byPerson.php
- modules/Attendance/attendance_future_byPersonProcess.php
- Fixes the date check in attendance_future_byPersonProcess to not allow the current date.
- Applies the Date class `minimum()` method to the dates in Set Future Absence to ensure they only allow future dates:
Eg:
> Attendance: fix Set Future Absence to only allow future dates

- modules/School Admin/yearGroup_manage.php
- modules/School Admin/yearGroup_manage_editOrderAjax.php
- src/Domain/School/YearGroupGateway.php
- src/Tables/Columns/DraggableColumn.php
- src/Tables/View/PaginatedView.php
Updates the Manage Year Groups page as an example of drag-drop row ordering.
> School Admin: add drag-drop Year Group ordering

- modules/System Admin/theme_manage.php
- modules/System Admin/theme_manage_uninstall.php
- modules/System Admin/theme_manage_uninstallProcess.php
When I changed active theme the message was "Uninstall was successful" and I changed for the default [success0] "Your request was completed successfully." and add translation support to message "The specified theme cannot be found or is active and so cannot be removed."
Travis and Local
> Theme change message fixed and added translation support

- modules/Messenger/messenger_post.php
- modules/Messenger/messenger_postProcess.php
Makes individual naming optional, on by default.
Some times naming is not needed.
Locally and in production
> Messenger naming option

- CHANGELOG.txt
- modules/Messenger/messenger_post.php
This PR makes some usability changes to the New Message screen:
- Adds a check to ensure that the user sending a message has at least one delivery mode available: Email, Wall or SMS. If they do not have a delivery mode, they cannot send a message, which prevents an odd behaviour where messages can be created but go nowhere.
- Adds a `$roleCategory == 'Staff'` check to the new Individual Naming feature. It feels like it may not be as useful for other users to have this option, and it helps reduce the overall interface clutter for non-staff users.
- Flips the default staff/student/parent values for Parent users. By default, parents will have Include Staff = N, Include Students = N, and Include Parents = Y.
> Messenger: adjust the default sending options for non-staff users

- CHANGELOG.txt
- modules/Staff/absences_view_byPerson.php
- src/Domain/Staff/StaffAbsenceDateGateway.php
- src/Domain/Staff/StaffAbsenceGateway.php
View Absences was accidentally showing all absences, regardless of the school year. This fixes it so the calendar and tally view display only the current school year. The table below with a list of absences has a new `School Year: Current` filter, which shows current absences by default but can be cleared to allow staff to see their past absences too.
> Staff: fix View Absences to only show the current year by default

- CHANGEDB.php
- CHANGELOG.txt
- modules/Students/firstAidRecord.php
- modules/Students/firstAidRecord_add.php
- modules/Students/firstAidRecord_edit.php
- modules/Students/firstAidRecord_editProcess.php
- src/Domain/Students/FirstAidGateway.php
Follow up on student First Aid Records is now no longer a single field, but a non-editable log that can be added to over time.
Concerns have arisen over editing and deletion of follow up details.
Locally
> Students: turned First Aid Record Followup into a non-editable log

- CHANGEDB.php
- CHANGELOG.txt
- index.php
- modules/Messenger/moduleFunctions.php
- modules/School Admin/messengerSettings.php
- modules/School Admin/messengerSettingsProcess.php
- resources/templates/ui/pinnedMessages.twig.html
- src/UI/Dashboard/StaffDashboard.php
- src/UI/Dashboard/StudentDashboard.php
- Adds a new setting in School Admin > Messenger Settings called "Enable Pinned Messages on Home"
- Adds code to `index.php` which loads (and caches) pinned messages, displaying them at the top of the home page, above the dashboard.
Feel free to suggest any visual changes. I kept it pretty minimal, to not distract from the content or add too much vertical space to the page.
Locally
> Messenger: add a setting to display pinned messages above the dashboard

- CHANGELOG.txt
- resources/templates/components/dataTable.twig.html
- resources/templates/index.twig.html
- src/Tables/DataTable.php
I've whipped up a small tweak that enables us to use sticky headers on tables that have been refactored, ideally without breaking any legacy tables. Sticky headers are quite handy for long data tables, but don't work if any of the containing divs have a css overflow property. 
This workaround uses a Page template variable to disable the overflow properties once a data table is created. The workaround can be removed once we've ooified all the tables, but for now I think it gives us the best of both worlds.
Sticky header on Manage Users:
> Tables: add sticky header to DataTables without breaking legacy tables

- CHANGEDB.php
- modules/System Admin/systemSettings.php
- modules/System Admin/systemSettingsProcess.php
- src/Services/BackgroundProcessor.php
Not all systems may support using the `exec` function for background processing, so this adds a system setting to manually disable all background processing system-wide. Also useful for testing.
> System: add a system setting to disable background processing

- CHANGEDB.php
- CHANGELOG.txt
- src/Domain/System/DiscussionGateway.php
This adds a new table and gateway class which can be used for feedback, evidence, discussion, etc. The idea is that by having a central location for discussion then we can then query and display recent comments in areas such as dashboards and student profiles. 
Some possible uses so-far include Planner, Mastery Transcript, Free Learning, Badges, House Points (when awarded individually).
Adds a gibbonDiscussion table, linked to a foriegnTable by ID, with the following schema:
```
CREATE TABLE `gibbonDiscussion` (
`gibbonDiscussionID` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
`foreignTable` VARCHAR(60) NOT NULL,
`foreignTableID` INT(14) UNSIGNED ZEROFILL NOT NULL,
`gibbonModuleID` INT(4) UNSIGNED ZEROFILL NOT NULL,
`gibbonPersonID` INT(10) UNSIGNED ZEROFILL NOT …
```
> System: add a general-purpose DiscussionGateway class

- CHANGELOG.txt
- modules/System Admin/module_manage_uninstallProcess.php
- modules/System Admin/updateProcess.php
One fix and one tweak:
- Update the module uninstaller to also remove notification events. This fixes a bug where uninstalling and installing the Trip Planner caused an SQL error. Tidied up the script a bit.
- Add a `pageLoads` refresh on update for non-cutting-edge installs.
> System: update module uninstaller, tweak cache refresh in system updater

- CHANGELOG.txt
- modules/Students/report_graph_studentEnrolment.php
Fixes https://github.com/GibbonEdu/core/commit/1f4d47fd00afd6445f81244d38d91e331a46a34e 👀 Accounts for a use-case where schools want to see enrolment excluding left students.
> Students: add Exclude Left Students checkbox to Student Enrolment Trends

- CHANGELOG.txt
- modules/Reports/reporting_proofread.php
- modules/Reports/reporting_proofreadProcess.php
- modules/Reports/src/Domain/ReportingAccessGateway.php
- modules/Reports/src/Domain/ReportingProofGateway.php
Currently, proof reading can be done by person, which shows all the comments that person has written. This adds an optional Proof Read Mode by form group/roll group, which shows all the comments that have been written for students in that form group. Teachers still receive edits and view their own overall progress on a per-person level.
> Reports: add a Proof Read by Form Group option

- CHANGEDB.php
- CHANGELOG.txt
- modules/Departments/departments.php
- modules/School Admin/department_manage.php
- modules/School Admin/department_manage_editOrderAjax.php
- src/Domain/Departments/DepartmentGateway.php
Currently the order of departments is alphabetical. For larger schools this order may end up with a very mixed-up list of departments. This PR adds the option to drag-drop sort the order of departments. They will fall back to the original numeric order by default.
> Departments: added drag-drop ordering to Departments in School Admin

- CHANGELOG.txt
- modules/Reports/reports_generate_singleProcess.php
- modules/Reports/src/GenerateReportProcess.php
- modules/Reports/src/Renderer/HtmlRenderer.php
- modules/Reports/src/Renderer/MpdfRenderer.php
- modules/Reports/src/Renderer/ReportRendererInterface.php
- modules/Reports/src/Renderer/TcpdfRenderer.php
- modules/Reports/src/ReportBuilder.php
- modules/Reports/src/ReportTemplate.php
- modules/Reports/src/Sources/CustomFields.php
- modules/Reports/src/Sources/Report.php
- modules/Reports/src/Sources/YearGroupCriteria.php
- modules/Reports/templates/preview.twig.html
- modules/Reports/templates_assets_components_preview.php
- modules/Reports/templates_assets_fonts_preview.php
- modules/Reports/templates_manage_add.php
- modules/Reports/templates_manage_addProcess.php
- modules/Reports/templates_manage_edit.php
- modules/Reports/templates_manage_editProcess.php
- modules/Reports/templates_preview.php
Requires #988 
This PR adds an option to select the PDF renderer when setting up a report template. In the back-end, it introduces a `ReportRendererInterface` and separates the previous `ReportRenderer` into `HtmlRenderer`, `TcpdfRenderer` and `MpdfRenderer`.
By the end of v20 we may want set mPDF as the default. For now, I think support for both options is a reasonable way to go.
> Reports: add an option to select the PDF rendering library in Template Builder

- src/Domain/Students/StudentReportGateway.php
People -> Students -> Reports -> Emergency Data Summary
The report is showing empty parents column.
gibbonPersonID get's replaced with blank which when passed to FamilyGateway produced nothing. Moving gibbonPersonID to the end solve the problem.
Besides that, I removed $data variable since it's not used.
> Students: Fix emergency data report not showing parents column

- CHANGELOG.txt
- yearSwitcherProcess.php
Fixed the first and last day of the selected school year in session
When I switch the school year, I can't see the data for the selected school year because the system keeps the first day and last day of current school year. e.g modules/Attendance/report_summary_byDate.php
> Fixed the first and last day of the selected school year

- CHANGEDB.php
- CHANGELOG.txt
- modules/Reports/src/Domain/ReportTemplateFontGateway.php
- modules/Reports/src/Renderer/MpdfRenderer.php
- modules/Reports/src/ReportBuilder.php
- modules/Reports/templates/preview.twig.html
- modules/Reports/templates_assets_fonts_edit.php
- modules/Reports/templates_assets_fonts_editProcess.php
- modules/Reports/templates_assets_scanProcess.php
- modules/Reports/templates_manage_edit.php
- modules/Reports/templates_manage_editProcess.php
- modules/Reports/templates_preview.php
This PR adds the ability to define which fonts should be included in a template. 
- Fonts can be discovered and configured though the Manage Assets screen, then added to a template in Edit Template.
- Fonts are included in the HTML preview using the `@font-face` css rule, and in the MpdfRenderer as configuration data. Fonts in the TCPDFRenderer are implicitly included.
- Fonts can be grouped in to Font Families using the Edit option in Manage Assets to set the font family name and font type.
Font selector:
Font preview:
> Reports: add the ability to select fonts in Template Builder

- CHANGEDB.php
- CHANGELOG.txt
- modules/Reports/reporting_write_byStudent.php
- modules/Rubrics/src/Visualise.php
- modules/Rubrics/src/visualise_saveAjax.php
- src/Domain/Rubrics/RubricGateway.php
- src/Domain/System/HookGateway.php
This PR adds a "Report Writing" hook type, which can be used to display custom form fields in the report writing screen. For example, some schools may want to use a custom layout for certain inputs, generate an image, or display a diagram inside the report writing screen. Any hook that matches the name of a Criteria Type will be included as custom code instead of the default form fields.
For example, a custom hook can used to display a Chart.js diagram and save it as an image during report writing:
This PR also tweaks the Visualize.php code to optionally return the filename of the image it generated (related to the image above, should not affect any other core features).
> Reports: add hooks for custom criteria types in the report writing screen

- CHANGELOG.txt
- modules/User Admin/applicationFormSettings.php
This PR adds text editors for the Introduction and Postscript settings. Not many users have HTML skills and this is one area often updated by non-system-admin users. Should be backwards compatible for most HTML content already in those fields.
> User Admin: add rich text editors to the Application Form Settings

- CHANGEDB.php
- CHANGELOG.txt
- modules/Staff/coverage_manage_edit.php
- modules/Staff/coverage_manage_edit_deleteProcess.php
- modules/Staff/coverage_manage_edit_edit.php
- modules/Staff/coverage_manage_edit_editProcess.php
- modules/Staff/src/Tables/CoverageDates.php
Adds the option to edit the time and values of a coverage record, or delete a date from a coverage record spanning more than one day. Also adjusts the value fields to accept two decimal places (eg: 0.25).
Coverage details can change and admin occasionally need the ability to edit the exact timing of staff coverage, or adjust the calculated value of that coverage for the day.
Tested locally and in production.
> Staff: add an option to edit or delete staff coverage dates

- CHANGEDB.php
- CHANGELOG.txt
- modules/Students/student_withdraw.php
- modules/Students/student_withdrawProcess.php
- src/Domain/Timetable/CourseEnrolmentGateway.php
This PR adds an action under Admissions to allow privileged users to withdraw a student. 
Currently the workflow to withdraw a student is to edit their status in User Admin. This can be counter-intuitive for some staff, or they may forget to update other fields such as end date and departure reason. 
This feature combines the student withdraw workflow into one page and adds optional student notes and notifications to help keep relevant parties informed. This includes a notification event, which allows admin to subscribe users to automatically receive all withdraw notifications.
> Students: add a Withdraw Student page with the option to notify staff

- CHANGELOG.txt
- modules/Students/css/module.css
- modules/Students/student_view_details.php
- resources/templates/components/listOptions.twig.html
- src/Domain/Students/StudentGateway.php
- Refactors the list of student's teachers into a data table
- Adds a grid view of teachers which have links to staff profiles and classes
- Adds an updated list view that also includes the class names
- Uses some css to ensure the list view can still be copy-pasted into an email
This feature request emerged after the addition of the new staff directory. The idea was that adding photos can help new parents and students see who their teachers are, and a visual list with photos can be more inviting than a text list. For staff, it also gives people an easier way to lookup the teacher of a student by subject. The original text list is preserved, including the copy-paste functionality.
I've refactored a bit of the code along the way, boyscout-rule, but the student …
> Students: add a grid view of teachers to student profile

- CHANGELOG.txt
- modules/User Admin/rollover.php
Adds the option to enter a departure reason for final year students in Rollover.
Without entering this value at this step, the students are often marked as Left with no departure reason, and it can be difficult for staff to infer if they left with the year incomplete or if they graduated. The "Class of" field is helpful for this, but doesn't _specifically_ indicate if a student has graduated.
> User Admin: add departure reason for final year students in Rollover

- modules/Staff/staff_view_details.php
- resources/templates/components/dataTable.twig.html
- resources/templates/components/detailsTable.twig.html
- src/Services/ViewServiceProvider.php
- src/Tables/DataTable.php
- src/Tables/View/DetailsView.php
Adds a new renderer for details tables, which represent a set of labels and data to display. There are lots of random areas in the system where these types of tables are displayed, and currently a regular data table or form doesn't work well.
Includes an example details table on the Staff Profile:
With the following code:
```php
table = DataTable::createDetails('personal');
$table->addColumn('preferredName', __('Name'))
->format(Format::using('name', ['title', 'preferredName', 'surname', 'Parent']));
$table->addColumn('type', __('Staff Type'));
$table->addColumn('jobTitle', __('Job Title'));
$table->addColumn('initials', __('Initials'));
$table->addColumn('gender', __('Gender'));
$table->addColumn('initials', __('Initials'));
echo $table->render([$row]);
```
> Tables: add a DetailsTable view and template

- CHANGELOG.txt
- modules/Finance/invoices_manage_editProcess.php
- modules/Finance/invoices_manage_issueProcess.php
- modules/Finance/invoices_manage_processBulk.php
- modules/Finance/invoices_payOnlineProcess.php
Finance emails now use the same template as other emails in the system.
Hackathon! 
Locally
> Finance: apply email template to invoices, receipts, and reminders

- src/Domain/Library/LibraryGateway.php
The enum within the mysql table for gibbonLibraryItem confirms that the renewal enum is not supported and therefore serves no purpose within the domain.
> Removing renewal from the Library domain as it is not used

- CHANGEDB.php
- CHANGELOG.txt
- modules/Reports/archive_manage.php
- modules/Reports/archive_manage_import.php
- modules/Reports/archive_manage_upload.php
- modules/Reports/archive_manage_uploadPreview.php
- modules/Reports/archive_manage_uploadProcess.php
- modules/Reports/src/Domain/ReportArchiveEntryGateway.php
- resources/templates/components/form.twig.html
- src/Domain/Students/StudentGateway.php
- src/Forms/Form.php
- src/Gibbon/FileUploader.php
Adds an Upload Reports option under Archives. This enables a user to upload a ZIP file of report PDFs that include student usernames, which are then added to the View Reports by Student page. This is similar to the user photo upload, with a few extra features:
- Includes a preview page to display which reports will be uploaded, and which already exist.
- Optionally overwrite existing reports when importing.
- The uploader can handle filenames inside the ZIP archive that have a separator character.
- The report name and date can be specified, which controls how the report displays in the student archive.
- Adds a uploadFromZIP method to the FileUploader class.
- Adds a setDescription method to the Form class, to match the functionality in the DataTable class. …
> Reports: add an option to bulk upload existing report PDFs

- modules/Library/library_lending.php
- src/Domain/Library/LibraryGateway.php
Adding OOified DataTable to the Library Lending page. There are two functional differences here:
1. Removing number column on the far left. I don't see a reason for it being there.
2. The row is NOT red if the item is on loan. I'm not sure if the current DataTable would support such an "optional" CSS class. If there is, lemme know and I'll update it.
A screenshot detailing the difference is below. The new table is above the old one here.
> OO: Library Lending

- .travis.yml
- composer.json
- tests/install/InstallCept.php
Previously, the Travis test was failing on PHP 7.4 because there's no version of PHP 7.4 on Ubuntu Trusty which includes the zip extension. This PR does a couple of things to remedy this:
- We're now testing on Ubuntu Xenial
- Due to Ubuntu Xenial image not enabling mysql by default, the service is now enabled directly in the `.travis.yml`
Additionally, to partially assist with any future issues where mysql doesn't start or isn't accessible, there's now a Codeception test to make sure that the install page doesn't show the connection failed test.
Finally, a debug version of the Codeception test has been added to the composer.json which doesn't run as a default test, it's just there for convenience.
> Partial PHP 7.4 Test Fix

- modules/Library/library_lending_item.php
- src/Domain/Library/LibraryGateway.php
Finished a first pass of library_lending_item.php OOification. A couple of possibilities here still:
- There's another hard coded table above the log which shows the details of the item. I suspect this can be OOified too. Is this worthwhile? Would this need to be build through some kinda lower level DataTable class?
- There's a header on the log on the original version. Is there a way to add a title to those DataTables? I suspect there was but I didn't find anything on the docs.
- This table uses italicised text where the action header usually appears to show that the item is not available for sign out. I don't believe there's a way to do that with the current OO tables so in place of that I've used a div with error class. Is that best practice? Could switch it for a warning class maybe? …
> OOification: Library Lending Item

- composer.json
- composer.lock
I believe Sandra mentioned in passing that PSR-2 was something we could have some robot fix for us, this PR kind of spawned from that but also my own lack of tooling with a GUI-less editor. 
This PR introduces codesniffer alongside a composer script for testing for PSR-2 styling. In doing so, it also bumps a couple of other packages due to what I believe to be fuzzy package version references.
It bumps:
aura/sqlquery
container-interop/container-interop
league/container
tecnikcom/tcpdf
twig/twig
I'm not 100% on these packages so would appreciate if one of you guys could see if you can explain that change. I'm not exactly an expert with composer but I get the gist of it through the use of npm.
I can, by all means, revert those vendorfiles and look to add some kind of versionlock to …
> Codesniffer

- CHANGELOG.txt
- modules/Timetable Admin/courseEnrolment_manage_class_edit.php
- modules/Timetable Admin/courseEnrolment_manage_class_editProcessBulk.php
- modules/Timetable Admin/courseEnrolment_manage_class_edit_delete.php
- modules/Timetable Admin/courseEnrolment_manage_class_edit_deleteProcess.php
- modules/Timetable Admin/courseEnrolment_manage_class_edit_edit.php
- modules/Timetable Admin/courseEnrolment_manage_class_edit_editProcess.php
- src/Domain/Timetable/CourseEnrolmentGateway.php
On the off chance that duplicate enrolments end up in the Course Enrolment by Class page, either through a manual import or other tool, they are currently not deleteable. 
- For the Delete action, this is because the page looks at the gibbonPersonID, sees more than one entry for that student, and returns an error. 
- For the Bulk action, the result is even more alarming: instead of deleting the duplicate or not deleting anything, it deletes everything, both the original and duplicate records are deleted.
This PR changes the Course Enrolment by Class page to use the gibbonCourseClassPersonID when editing and deleting enrolments, to ensure that the duplicates can be removed without causing an issue with the original record.
Locally.
> Timetable Admin: fix Course Enrolment by Class unable to delete duplicates

- modules/System Admin/logs_view.php
Error, if the field serializedArray is empty (e.g. extended module Help Desk)
Local
Before
After
> Log view - small adjustment

- CHANGELOG.txt
- modules/Messenger/messenger_post.php
- modules/Messenger/messenger_postProcess.php
Adds finer-grained controls to the Applicants target in Messenger's New Message interface.
Sometimes you want to email students, sometimes parents, sometimes both. Nice to have the choice, which also makes the interface more intuitive in terms of what behaviour to expect.
Locally
> Messenger: added Parent and Student options to Applicants target in New Message

- modules/School Admin/attendanceSettings_manage_edit.php
This field (name) must be readonly, as changing the value causes many problems. It's used as a key in queries, e.g src/Domain/Attendance/AttendanceLogPersonGateway.php:120
Local
> Field name readonly in edit form

- modules/Finance/invoicees_manage.php
- src/Domain/Finance/InvoiceeGateway.php
OOification of the Manage Invoicees page alongside PSR2 compliance. Also:
- Adds a title to the form on this page using setTitle instead of inline HTML.
- Moves table description to above the table instead of the form and is now using setDescription in place of inline HTML.
- Domain-side date handling for better support should the database datetime format change.
- Now using switches for the invoiceTo/companyAll checks for better readability.
*Known Bug*: DataTable actions do not send null variables and therefore, when you click edit on the invoicees, an error is shown on the edit invoicee page. #1057 fixes this by adding handling of empty variables within that action.
> OO: Manage Invoicees

- CHANGELOG.txt
- modules/Formal Assessment/externalAssessment.php
- modules/Formal Assessment/externalAssessment_manage_processBulk.php
- src/Domain/FormalAssessment/ExternalAssessmentStudentEntryGateway.php
- src/Domain/FormalAssessment/ExternalAssessmentStudentGateway.php
This PR adds an Add bulk action for External Assessment Data, which can be used when setting up placeholders for a large number of students at once. It works with the Copy Target Grades option, which copies CAT targets into the GCSE/iGCSE assessment.
The bulk action is only available to users with the `External Assessment Data_manage` permission.
> Formal Assessment: add a bulk action for External Assessment Data

- resources/templates/components/detailsTable.twig.html
Implemented Header Action rendering for Details Tables. Detail Tables without Header Actions should look the same.
Locally on Detail Tables with and without Header Actions, in both core and Help Desk module.
Example of simple details table with Header:
Example of simple details table without Header (i.e. no change):
> Added Header Actions to Details Tables

- CHANGELOG.txt
- modules/Planner/moduleFunctions.php
- modules/Planner/planner_deadlines.php
- modules/Students/student_view_details.php
- resources/templates/ui/upcomingDeadlines.twig.html
- src/Domain/Planner/PlannerEntryGateway.php
- src/UI/Components/Sidebar.php
- src/UI/Dashboard/ParentDashboard.php
Currently all the Upcoming Deadlines sections are duplicated in many areas of the system, and some of the colouration isn't consistent. This PR adds and implements a template for the deadlines section and moves related SQL into a gateway class. It also makes small visual tweaks to make the meaning of colours more apparent.
Areas changed:
- Parent Dashboard
- Student Dashboard sidebar
- Planner Deadlines page (for parents, students and staff)
- Student Profile page
- Planner sidebar (for students and staff)
> Planner: added a common template for all Upcoming Deadlines sections

- CHANGELOG.txt
- modules/Timetable Admin/ttColumn.php
- modules/Timetable Admin/ttColumnProcessBulk.php
- modules/Timetable Admin/tt_edit.php
- modules/Timetable Admin/tt_editProcessBulk.php
- src/Domain/Timetable/TimetableColumnGateway.php
- src/Domain/Timetable/TimetableDayGateway.php
Adds the ability to bulk duplicate timetable days and columns
Makes rescheduling for school closures considerably easier, as you can duplicate days and columns to created editable versions, without losing your regular schedule.
Locally
> Timetable Day & Column Bulk Duplicate

- CHANGELOG.txt
- modules/Data Updater/data_familyProcess.php
- modules/Data Updater/data_financeProcess.php
- modules/Data Updater/data_medicalProcess.php
- modules/Data Updater/data_personalProcess.php
This PR changes the data update process so that a data update with no changes is automatically accepted and does not generate a notification. It does this by comparing the new values to the old values when processing the request.
It is good to encourage people to submit a data update even if there are no changes, so that the system knows their data is up to date. However, accepting all these changes can be tedious. This PR aims to save some time for admin.
> Data Updater: auto-accept data updates with no changes

- CHANGEDB.php
- CHANGELOG.txt
- modules/Students/applicationForm_manage_accept.php
- modules/Students/studentEnrolment_manage_addProcess.php
- modules/Students/studentEnrolment_manage_editProcess.php
- modules/Timetable Admin/courseEnrolment_manage_byPerson_editProcessBulk.php
- modules/Timetable Admin/courseEnrolment_manage_byPerson_edit_addProcess.php
- modules/Timetable Admin/courseEnrolment_manage_byPerson_edit_edit.php
- modules/Timetable Admin/courseEnrolment_manage_byPerson_edit_editProcess.php
- modules/Timetable Admin/courseEnrolment_manage_class_editProcessBulk.php
- modules/Timetable Admin/courseEnrolment_manage_class_edit_addProcess.php
- modules/Timetable Admin/courseEnrolment_manage_class_edit_edit.php
- modules/Timetable Admin/courseEnrolment_manage_class_edit_editProcess.php
- modules/Timetable Admin/courseEnrolment_sync_runProcess.php
- modules/Timetable Admin/course_rollover.php
- modules/Timetable Admin/tt_import.php
- modules/Timetable/studentEnrolment_manage_edit.php
- modules/Timetable/studentEnrolment_manage_editProcessBulk.php
- modules/Timetable/studentEnrolment_manage_edit_addProcess.php
- modules/Timetable/studentEnrolment_manage_edit_edit.php
- modules/Timetable/studentEnrolment_manage_edit_editProcess.php
- modules/User Admin/rollover.php
This PR adds dateEnrolled and dateUnenrolled fields to the gibbonCourseClassEnrolment table. It updates these dates when enrolling as well as syncing or auto-enrolling. The dates 
We've discovered a few instances where it is helpful to know when a student joined or left a class, for the purpose of filtering relevant lessons and homework for that student.
Locally.
> Timetable Admin: add a dateEnrolled and dateUnenrolled to class enrolments

- CHANGELOG.txt
- src/Services/Format.php
This PR adds the formatter function for a linked profile
Discussed on slack with @SKuipers after encountering the need for a name to link to a profile. Current method of doing so involves nesting a format::name in a format::link with a few extra steps to define the URL etc, this automatically does it based off of the role type in one function.
Locally, using the development helpdesk module as a playing ground
> Format: nameLinked

- CHANGEDB.php
- CHANGELOG.txt
- modules/Rubrics/moduleFunctions.php
- modules/Rubrics/rubrics_edit_editRowsColumns.php
- modules/Rubrics/rubrics_edit_editRowsColumnsProcess.php
- src/Forms/FormFactory.php
- src/Forms/Input/Color.php
Adds the option to specify a background colour for rubric row and column headings. Also adds the HTML colour picker to the form class.
Adds some visual interest to an otherwise dull looking grid. Helps differentiate column types.
Rubric view:
Edit view:
> Rubrics: add an option to colour rubric column and row headings

- CHANGEDB.php
- CHANGELOG.txt
- modules/Data Updater/data_medical.php
- modules/School Admin/medicalConditions_manage.php
- modules/School Admin/medicalConditions_manageProcess.php
- modules/Students/medicalForm_manage_edit.php
This PR adds the option to display text before the medical conditions section in the data updater and medical forms. This text can be used by schools to inform users about how to use this section, as well as display specific information that parents may need to know about medical conditions in general. Currently, with the Add Condition option being a single checkbox, it can be easy for parents to not notice it is there. This text can help draw attention to this section. 
- Adds "Medical Condition Introductory Text" setting to the top of the Manage Medical Conditions page
- Displays intro text above the Add Condition option on the Data Updater > Update Medical Data page
- Displays intro text above the Medical Conditions section in Students > Edit Medical Form
**How Has This …
> School Admin: add intro text setting to Medical Conditions section

- composer.json
Add `--colors=always` flag to phpunit call in Travis. See [Documentations](https://phpunit.readthedocs.io/en/9.3/textui.html).
This is purely for better development experience.
On Travis.
> travis: phpunit always use color

- .gitlab-ci.yml
Various GitLab CI fixes.
Some long standing maintenance fix to the GitLab CI configurations:
1. Only do checksum check if environment variable `COMPOSER_CHECKSUM` is present.
2. Remove the global codeception and phpunit installation.
3. Refactoed gitlab-ci.yml to use extends.
1. The previous config hardcoded the SHA checksum of composer, which is unreasonable.
2. Since phpunit and codeception are both in the `require-dev` section of composer.json, there is no need for a global installation.
3. The previous config yml was clumsy and need better styles.
Tested with my GitLab fork:
* [The repository](https://gitlab.com/yookoala/gibboneducore/)
* [The relevant pipeline …
> Fix GitLab CI builds

- modules/Individual Needs/moduleFunctions.php
- src/Domain/IndividualNeeds/INGateway.php
This PR contains the OOified version of the moduleFunctions script for Individual Needs with a number of improvements.
- Now using DataTables in place of inline HTML for the most part.
- Error handling for archives (see note below)
- Gateway functions for alert levels and descriptors for students have been added. 
- sequenceNumber within alert and descriptor tables is now used as part of the IN gateway. This does affect other pages but will only order them based on the ingrained sequenceNumber instead of whatever order SQL outputs it in.
**Archives**
It was previously possible to have an archive show which would not actually tick any of the boxes giving the appearance that the student never had any IN attributes. The table will now check that the relevant descriptor and alert level exist …
> OO: Individual Needs moduleFunctions

- modules/Students/student_view_details.php
OOifying Student View Details page's Activity subpage. Some other improvements bundled too:
- Moving to common DataTable object in lieu of inline tables
- Using isModal() on actions to prefer the users modal size over the preset.
- Using Format::dateReadableRange in place of previous reused code block.
- Term concat is now done in SQL rather than PHP which should be marginally quicker.
- Using setTitle in place of basic inline h3 tags
**One unrelated fix** but so small I don't think it really requires a separate PR, now using setTitle on the student notes subpage.
All changes are PSR2 compliant according to PHPCS
> OO: Student View Details - Activity

- gibbon.php
In `gibbon.php`, used `__DIR__` to resolve the absolute path to the `error.php` instead.
When `gibbon.php` is run within the context of `installer.php`, the statement "include './error.php'" would resolve an incorrect path and hence unable to display the error message.
> Installer: fix gibbon.php include path

- installer/install.php
- installer/installerFunctions.php
- resources/templates/installer/config.twig.html
- tests/unit/Installer/ProcessConfigVarsTest.php
1. Properly sanatize the config variables before printing them in config file.
2. Remove the "bad character" check for the database password (for it is no longer needed).
3. Resolve #1040.
The config file is rendered from [config.twig.html](https://github.com/GibbonEdu/core/blob/3f27cf3e5ee857a2d4936a3210671b2d7b860c9f/resources/templates/installer/config.twig.html), which would manually wrap the variable with single quote `'` to make them string literals. This is approach is susceptible to injection attack. So the installer has some [bad-character check inplace](https://github.com/GibbonEdu/core/blob/3f27cf3e5ee857a2d4936a3210671b2d7b860c9f/installer/install.php#L123-L128) to mitigate the issue.
While this would work in many cases, this also …
> Fix installer config rendering

- src/Domain/System/Module.php
missing "type" attribute in Module class
In addition to the commit (https://github.com/GibbonEdu/core/commit/82aa1e9870e54e31d5ad8fdf935ee15be08c6cf4)
> V21 breadcrumb fix

- CHANGELOG.txt
- modules/Formal Assessment/internalAssessment_manage.php
- modules/Formal Assessment/internalAssessment_write.php
- modules/Markbook/moduleFunctions.php
- modules/Students/student_view_details.php
- modules/Timetable Admin/courseEnrolment_manage_byPerson_edit_edit.php
- modules/Timetable Admin/courseEnrolment_manage_class_edit_edit.php
Updates the gibbonCourseClassPerson reportable flag to optionally apply to teachers, to be able to hide them from places where class teachers are listed.
There are cases where teachers need to be added to a course, so they can help manage it or take attendance, but do not need to show up in the list of teachers for that course.
Locally.
> Timetable Admin: hide non-reportable teachers from teacher lists

- CHANGELOG.txt
- modules/Planner/planner_view_full.php
Given the right permissions, students can see birthday icon alerts for classmates in the class and form group table views, but not in the Planner lesson view. This PR adds the birthday icon to the Planner lesson view using the same logic as the other two locations.
To resolve this inconsistency in order to deliver the same behaviour across the board.
Locally
> Student birthday option

- CHANGEDB.php
- CHANGELOG.txt
- modules/School Admin/medicalConditions_manage.php
- modules/School Admin/medicalConditions_manage_add.php
- modules/School Admin/medicalConditions_manage_addProcess.php
- modules/School Admin/medicalConditions_manage_edit.php
- modules/School Admin/medicalConditions_manage_editProcess.php
- modules/Students/student_view_details.php
- src/Domain/Students/MedicalConditionGateway.php
v21 adds the option to edit the list of Medical Conditions available in the medical section. This adds an optional description field for these conditions, which helps schools define any additional information for specific conditions.
Some medical conditions aren't self-explanatory, such as G6PD deficiency, so additional information can be useful. On a school-by-school basis, this could be used for specific information, for example allergies could list the location of epipens in the school in the description.
> School Admin: add optional descriptions for medical conditions

- CHANGELOG.txt
- gibbon.php
- resources/templates/error.twig.html
- src/Gibbon/Locale.php
- src/View/Page.php
Currently, if the database connection fails or temporarily cannot connect, a blank white page with the 'oh no' message is displayed. This PR improves the error page so that the index template is still displayed, aimed to make this error less jarring for any users that experience it.
Feel free to suggest some better error message text 🤔 
Locally
> System: improve the error page when the database connection fails

- CHANGEDB.php
- modules/Data Updater/data_personal.php
- modules/Data Updater/data_personalProcess.php
- modules/Data Updater/data_personal_manage_editProcess.php
- modules/Staff/applicationFormProcess.php
- modules/Staff/applicationForm_manage_editProcess.php
- modules/Staff/staff_view_details.php
- modules/Students/applicationFormProcess.php
- modules/Students/applicationForm_manage_edit.php
- modules/Students/applicationForm_manage_editProcess.php
- modules/Students/student_view_details.php
- modules/User Admin/user_manage_editProcess.php
- publicRegistrationProcess.php
- src/Database/Migrations/2020-11-20-CustomFields.php
- src/Domain/Traits/TableAware.php
This PR is a follow-up to #1176 which adds a migration for changing serialized custom fields into JSON custom fields. JSON in a database is more stable and has better functionality in more recent versions of MySQL. 
- Adds a migration file in src/Database/Migrations.
- Changes instances of unserialize/serialize to json_decode/json_encode.
- Allows the selectBy to be used with no constraints, returning all rows.
Locally
> System: migrate all custom fields from serialized data into json data

- installer/assets/installer.js
- installer/install.php
- resources/templates/installer/install.twig.html
* Separate the code that expose environment data to javascript for the javascript that uses the data.
* Extract majority of `install.php` javascript into `installer.js` for easier development and debug. Leave only the variable exposing part for inline.
* Make the installer easier to read and maintain.
* A step to gradually improve the installer.
Tested locally as well as with Travis.
> Installer: extract inline-javascript as much as possible

- modules/Students/report_students_byRollGroup.php
- modules/Students/student_view_details.php
- resources/templates/formats/medicalConditions.twig.html
**Motivation and Context **
The pages doesn't show the color correctly
- Hash deleted from the code, because the alertColor attribute has the value with hash
- alertColor attribute fixed in template medicalConditions
 Local and Travis
> Hash deleted in code, because the alertColor attribute has hash in the value

- src/Tables/View/DataTableView.php
Fix for a bug that occurs when two (or more) row modifiers are added to a table. If any (except the last) row modifier returns null, an error will be thrown as all subsequent modifiers will be given the null variable.
Expandable columns use rowModifiers, however, if a custom row modifier that can (and does) return null is used, an error will be thrown and the table will not render.
Locally on the Trip Planner (where the bug existed) and on the Help Desk (where an existing table with a row modifier exists)
> Fixed null reference when row modifier returned null

- .editorconfig
- .github/workflows/ci.yml
A proof-of-concept setup to run the CI tests with [GitHub Actions](https://github.com/features/actions). Basically a drop-in-replacement of the current Travis CI tests.
Travis CI has seen [some issue](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works). And its fun to learn about GitHub Actions in the process.
The speed seems a little bit faster. And the output in Pull Requests look a bit nicer. Also it paves road to implement #1123 with [GitHub Action - Releases API](https://github.com/actions/upload-release-asset), which should enjoy some level of native support.
The obvious downside is making the source release process more reliant on GitHub.
Tested in my fork of …
> WIP: GitHub Actions for CI

- modules/Activities/activities_manage_addProcess.php
- modules/Activities/activities_manage_editProcess.php
* The variable $staff (from $_POST['staff']) should be an array
from the form input. The previous fallback was to null, which
is not Countable nor array. In PHP 8, using count() on anything
other than the 2 is a TypeError.
* Instead, changed the fallback to empty array would fix the issue.
* In addition, add extra sanitation step to make sure it is an
array.
> Activities: fix count error with null in php 8

- .github/workflows/ci.yml
* Showing error messages normally in CI test environment. The
failed test artifact will get the full xdebug message instead
of nothing at all.
* Have the test server to save logs to tests/log/server_log so
it will be included in the test artifact for download and
debug.
GitHub Actions CI workflow would save test logs as artifact when failed. This is for easier debugging on test failure. But the CI's PHP environment would hide all error message (even fatal errors) by default. So it would be very hard to debug a test failure without reproducing the environment locally. And this defeats the purpose of multiple version test in CI environment.
Tested in my fork of the repository.
You may download the test artifact of this …
> github-actions: Setup test server to show error

- .github/workflows/ci.yml
* Add PHP 8.0 test to CI.
* Mark it as "experimental" and do not treat failure as an error.
* Failure will still have message in the CI result. And test artifacts will still be available for study.
As as step to gradually resolve issue #1210 without disturbing other PR and updates.
On this PR, with GitHub Actions.
**Screenshot**
> github-actions: add experimental php8 test

- tests/acceptance.suite.yml
* Fix previously obsoleted grouping config.
* Regroup the tests by functionality.
* According to documentations, the [groups](https://codeception.com/docs/07-AdvancedUsage#group-files
) directive in configuration serves to specify files and folders so user can run tests selectively. But the directive has to specify files and folders that exists.
* The current configuration seems to be generated by `codecept init`. All previous iterations of this file don't seems to match with any specific subfolder in the `tests/` folder:
https://github.com/GibbonEdu/core/blob/7272bd60218ac59dc5e259556f923ee8d2dc6eb4/tests/acceptance.suite.yml#L17-L18
https://github.com/GibbonEdu/core/blob/adf8f0f5b5556219024413c790db0eb3d0c785ca/tests/acceptance.suite.yml#L33-L34 …
> Tests: revamp grouping

- installer/install.php
- src/Database/MySqlConnector.php
* Add a backward-compatible change to connector to allow it to rethrow PDO connection error.
* Improves the installer error message with database connection issue(s).
* Probably fixed an installer bug. Instead of checking `empty($pdo)`, which is `false` instead of `null` when error, the installer should either check something like `$pdo instanceof \PDO` or `$pdo !== false`.
It's really hard to tell what went wrong if the installer failed to connect to database. Especially if you're debugging CI build errors. It would be really helpful to show some internal error message on the page. Then the test artifact would be more helpful to debug with.
> Feature: connector debug in installer

- tests/acceptance.suite.yml
- tests/codeception.yml
* Change according to warning message: "DEPRECATION: 'settings: bootstrap:
bootstrap.php' option is deprecated! Replace it with: 'bootstrap:
bootstrap.php' (not under settings section). See https://bit.ly/2"
* Simply to remove a deprecation message and make it more potent to future codeception upgrades.
Locally and in CI environment.
**Screenshot**
Before:
After:
> Tests: Fix deprecation message

- tests/unit/Data/UsernameGeneratorTest.php
- tests/unit/Domain/QueryCriteriaTest.php
- tests/unit/Domain/QueryableGatewayTest.php
- tests/unit/Domain/System/ModuleTest.php
- tests/unit/Domain/System/ThemeTest.php
- tests/unit/Forms/Layout/RowTest.php
- tests/unit/Gibbon/FileUploaderTest.php
- tests/unit/Gibbon/Locale/TranslateNTest.php
- tests/unit/Gibbon/Locale/TranslateTest.php
- tests/unit/Gibbon/TranslationTest.php
- tests/unit/Installer/ProcessConfigVarsTest.php
- tests/unit/Services/FormatTest.php
- tests/unit/View/PageTest.php
* Fix forward all unit test compatibiliy with phpunit 9 by updating setUp and tearDown function signatures.
* Newer PHPUnit TestCase setUp and tearDown method needs to specifically hint to return "void".
* The change is backward compatible. Loose parent methods are compatible with strict children implementations.
* This fixed a few errors that block #1214.
On CI platform.
> Tests: fix TestCase for phpunit 9

- tests/unit/Domain/QueryCriteriaTest.php
* assertContains should be only used on iterables (e.g. array) in newer phpunit. To check if a string contains another string, use assertStringContainsString or assertStringNotContainsString instead (if available).
* Make the test forward compatible with phpunit 9
* This fixed an error that block #1214.
CI platform.
> Tests: fix test Domain/QueryCriteriaTest

- .github/workflows/ci.yml
* PHP 8.0 test failure will no longer be ignored.
* Test Artifact of PHP 8.0 will only be uploaded any of the tests failed.
* To ensure #1210 is delivered in v22.0.00, we should do this at some point of time.
* Since all tests are green in PHP 8.0 now, it seems to be a good time to do so.
* CI Environment
> Tests: promote PHP 8.0 to formal test target

- functions.php
- src/Gibbon/Locale.php
* Improve docblock comment for __() and Gibbon\Locale::translate().
* It's not obvious how to use the `Locale::translate` or the `__()` function. Improve the docblock can improve the translation strings written in long term (i.e. the usage of string placeholder).
**How Has This Been Tested?*
Documentation don't seems to have a way to test.
> Documentation: better docblock for translation functions

- modules/User Admin/user_manage_editProcess.php
- src/Forms/DatabaseFormFactory.php
* Fix a mistake in reusing variable.
* In createSelectStudent
* When the query is both byRoll and byName and is neither allStudents
nor activeStudents, the $data defined in the first query will affect
that of the second query.
And in some MySQL / MariaDB / PDO configuration or version, this
will cause error: "SQLSTATE[HY093]: Invalid parameter number: number
of bound variables does not match number of tokens".
* The solution is to re-initialize $data (and $value) before the
second condition.
* In createSelectUsers
* A query without placeholder is supplied with a non-empty data
array, causing "SQLSTATE[HY093]: Invalid parameter number: number
of bound variables does not match number of tokens". Simply change
to query with empty array would fix it. …
> Fix Gibbon\Forms\DatabaseFormFactory database methods

- src/Forms/Layout/Row.php
* Properly handle the case when function returned anything other than `Gibbon\Forms\OutputableInterface`.
* Properly rewrite the error messages from sprintf to __().
* Fix #1227.
CI Environment
> Fix Gibbon\Forms\Layout\Row::__call magic method issue hanlding error output of actually called function

- .gitlab-ci.yml
* Update GitLab CI to test PHP 7.3 to 8.0.
* Clean up the syntax of the GitLab CI config.
* Improve test review by uploading artifact of failed tests.
* Move the GitLab CI config along side the latest repository changes
On [my fork at GitLab.com](https://gitlab.com/yookoala/gibboneducore/-/pipelines?page=1&scope=branches&ref=feature%2Fphp8-test-in-gitlab-ci)
> Tests: php8 test in GitLab CI

- resources/templates/menu.twig.html
- resources/templates/navigation.twig.html
* Twig 2.x used to support using condition as a part of the for
statement. But 3.x no longer support this syntax. Using it will
result in "syntax error" exception from Twig.
Reference:
https://twig.symfony.com/doc/2.x/tags/for.html#adding-a-condition
https://twig.symfony.com/doc/3.x/tags/for.html
* To future-proof the templates, simply extract the if statement
from the for loop and wrap it on outside.
* Stumbled upon this error when trying to upgrade Twig from 2 and 3.
* We might not upgrade to Twig 3, we can still future proof our templates.
Locally and In CI testing platform.
> Twig: fix template forward compatibility

- functions.php
* Add a secondary ordering column "gibbonActionID" to fix the order
to make sure the ordering consist in different storage engine.
* Fix #1237
Locally and in CI platform. All tests are pass.
> Core: fix getHighestGroupedAction ordering

- src/Forms/Traits/MultipleOptionsTrait.php
When an empty DataSet is given to a select with the function from DataSet, a warning and a notice will pop up.
Locally.
> Fixed errors when DataSet is empty

- src/Forms/Input/MultiSelect.php
With the new theme, the MultiSelect takes up more space and as a result the Add and Remove buttons do not properly stack. They also do not properly expand. 
Locally with both the original and new theme.
**Before:**
**After:**
**Before (old theme):**
**After (old theme):**
> Fixed MultiSelect buttons not stacking and not expanding dynamically

- functions.php
- index.php
- src/View/Components/ReturnMessage.php
- src/View/Page.php
OOification of Return Processing. This PR deprecates the old returnProcess method and implements a new ReturnMessage class which is handled by Page to process and render return messages. ReturnMessage has methods to set the edit link for a page and add custom returns for processing. For backwards compatibility, the returnProcess method calls the new ReturnMessage methods to set the relevant details.
Locally on several modules with untouched returnProcess methods and pages altered to use new system.
> OOification: Return Process

- src/Domain/System/LogGateway.php
Implemented setLog function into LogGateway to replace setLog in functions.php. The new function doesn't require a gibbonModuleID, but instead the module name, making logging easier.
Locally with the Help Desk.
> OOification: Set Log

- CHANGEDB.php
- CHANGELOG.txt
- modules/User Admin/publicRegistrationSettings.php
- modules/User Admin/publicRegistrationSettingsProcess.php
- publicRegistration.php
- publicRegistrationProcess.php
This PR adds an optional Public Registration Setting to enable restricting public registration to users from a comma-separated list of allowed domains. The domains are checked with client-side and server-side validation. OOifies and tidies up some code along the way, as well as adds a password confirmation field, which was oddly missing.
Enables administrators to restrict who can register.
Locally
**Setting**
**Registration**
> User Admin: enable restricting Public Registration to a list of allowed domains

- CHANGELOG.txt
- resources/templates/ui/enrolmentOverview.twig.html
- src/Domain/Students/StudentGateway.php
- src/Domain/Students/StudentReportGateway.php
- src/Domain/Traits/SharedUserLogic.php
- src/Services/Format.php
- src/Tables/Prefab/EnrolmentTable.php
- src/UI/Dashboard/StaffDashboard.php
This PR adds an Enrolment tab to the staff dashboard, which displays the current enrolment count, the breakdown by year group, as well as any new or left students in a +/- 60 day range.
This gives staff a quick glace at the enrolment numbers, and a quick way to see who is joining or leaving the school. Also useful for themes that don't have an enrolment count in the Fast Finder box.
Locally.
> System: add an Enrolment tab to the Staff Dashboard

- tests/config/envs/travis_ci.yml
* Extend timeout from 30s (default) to 180s to tolerate the long installer operation.
* GitHub Actions CI process easily run into timeout in the installer because wait time for the data base import is too much.
CI Environment
> GitHub Actions: fix curl time issue

- CHANGEDB.php
- CHANGELOG.txt
- modules/System Admin/customFields.php
- modules/System Admin/customFields_add.php
- modules/System Admin/customFields_addProcess.php
- modules/System Admin/customFields_delete.php
- modules/System Admin/customFields_deleteProcess.php
- modules/System Admin/customFields_edit.php
- modules/System Admin/customFields_editOrderAjax.php
- modules/System Admin/customFields_editProcess.php
- src/Forms/Input/CustomField.php
Requires #1260.
Third piece of the Custom Fields refactoring.
- Adds new field types: Rich Text, Checkboxes, Radio, Time, File, Image, Yes/No, Number, Colour
- Improves the layout and usability of the Add/Edit Custom Fields pages
- Enables optgroups in Dropdown fields using [] around an option name
- Adds drag-drop ordering to the Custom Fields page
Locally.
Example of a variety of custom fields displayed through a Details table:
> System Admin: add new Custom Field types

- CHANGEDB.php
- CHANGELOG.txt
- modules/Data Updater/data_medical.php
- modules/Data Updater/data_medicalProcess.php
- modules/Data Updater/data_medical_manage_edit.php
- modules/Data Updater/data_medical_manage_editProcess.php
- modules/Data Updater/data_personal_manage_edit.php
- modules/Data Updater/data_personal_manage_editProcess.php
- modules/Students/medicalForm_manage.php
- modules/Students/medicalForm_manage_add.php
- modules/Students/medicalForm_manage_addProcess.php
- modules/Students/medicalForm_manage_edit.php
- modules/Students/medicalForm_manage_editProcess.php
- modules/Students/report_student_medicalSummary.php
- modules/Students/student_view_details.php
- modules/System Admin/customFields_add.php
- modules/System Admin/customFields_edit.php
- resources/imports/medicalForms.yml
- resources/templates/formats/medicalForm.twig.html
- src/Database/Migrations/2021-03-03-MedicalFields.php
- src/Domain/DataUpdater/MedicalUpdateGateway.php
- src/Domain/Students/MedicalGateway.php
- src/Domain/System/CustomFieldGateway.php
- src/Forms/CustomFieldHandler.php
- src/Forms/FormFactory.php
- tests/acceptance/Data Updater/UpdateMedicalDataCept.php
This PR is a proof of concept of the extended custom fields system, but is also more complex than most applications of custom fields because medical data is included in the Data Updater as well as the Student Profile and student reports.
Includes a  number of changes:
- Enables the Medical Form context in System Admin > Custom Fields
- Implements custom fields in Students > Manage Medical Forms
- Implements custom fields in Data Updater > Medical Updates
- Migrates the Blood Type and Tetanus fields into Custom Fields (using a migration script)
- Removes the built-in  Blood Type and Tetanus fields from various areas of the system
- Updates the Student Profile > Medical section to include custom medical fields
- Updates the Student Medical Data Summary report to include custom medical …
> Students: add custom fields to Medical Forms, migrate some data into custom fields

- CHANGEDB.php
- modules/System Admin/update.php
- modules/System Admin/updateComposerProcess.php
- src/Database/Updater.php
In preparation for merging #1209, we're looking at how we can help inform developers of the change in workflow, as well as ensure their systems remain up to date with the cutting edge code. This PR adds a check to the Update process to see if the content-hash in the composer.lock file has changed, and prompts users if they need to run a composer install.
Locally
> System Admin: add a composer.lock hash check to the Update page

- src/Forms/CustomFieldHandler.php
* Unparenthesized ternary is deprecated in php 7.4 and
considered fatal error in php 8.0. Added explicit
parentheses to fix the error.
* Optional parameters should be provided after required
parameters. Provide default value '' to the later $oldValue
and $newValue in CustomFieldHandler::addCustomFieldsToDataUpdate
to make them also optional and fix the message.
* Also add typehint `array` to `$params` of
CustomFieldHandler::addCustomFieldsToDataUpdate.
References:
* https://www.php.net/manual/en/migration74.deprecated.php
* https://www.php.net/manual/en/migration80.incompatible.php
* https://php.watch/versions/8.0/deprecate-required-param-after-optional
CI environment
> Fix nested ternary operator in custom field

- modules/Planner/moduleFunctions.php
- Issue 1271 fixed (as a result, the calendar is now responsive)
- translation support in the name of the month
https://github.com/GibbonEdu/core/issues/1271
> Issue 1271 fixed and translation support in the name of the month

- resources/templates/index.twig.html
The value of  property xl:overflow-x-unset changed to xl:overflow-x-scroll
When the button "sidebarToggle" is clicked, the display tab (Enrolment) on high-resolution screens not working correctly.
Local in high resolution 1920 x 1080
> Display dashboard tab (Enrolment) for high resolution screens fixed

- composer.json
- composer.lock
* Fix reference to deprecated ReflectionParameter::getClass method.
* Only change the composer.json and composer.lock. The changes to the `/vendor` folder are not included here, so this will not work without a local `composer install`. Users who don't know composer will have to rely on #1209 bundle for simple installation.
* Fix #1226
* Depends on #1209.
Locally and in CI environment
Note: CI test runs `composer install` before tests so things works there actually means the library upgrade works.
> Core: Upgrade league/container

- CHANGEDB.php
- modules/Data Updater/data_personalProcess.php
- src/Database/Migrations/2021-03-18-CustomFieldIDs.php
- src/Forms/CustomFieldHandler.php
As part of our custom field improvements, the gibbonCustomFieldID length was increased from 3 to 4. This change ended up requiring various checks in the code to ensure old and new custom fields were compared correctly. This PR addresses the issue by adding a migration to update all custom field ID lengths, which enables removing the added complexity from the code.
The `SELECT NULL;` in the changedb is there to trigger an update. Ideally, this generally wont be needed because the migration almost always entails a database change. However, this migration happens to be a follow-up change to the previous migration.
> System: add a migration to update all custom field IDs

- CHANGEDB.php
- CHANGELOG.txt
- modules/Departments/department_course.php
- modules/Departments/department_course_class.php
- modules/System Admin/customFields_add.php
- modules/Timetable Admin/course_manage_add.php
- modules/Timetable Admin/course_manage_addProcess.php
- modules/Timetable Admin/course_manage_class_add.php
- modules/Timetable Admin/course_manage_class_addProcess.php
- modules/Timetable Admin/course_manage_class_edit.php
- modules/Timetable Admin/course_manage_class_editProcess.php
- modules/Timetable Admin/course_manage_edit.php
- modules/Timetable Admin/course_manage_editProcess.php
- src/Forms/CustomFieldHandler.php
Next step in the process. This PR adds custom fields for courses and classes. They are editable in Manage Courses & Classes, and will show up on the department page unless hidden.
Continues extending the areas in the system which can be customized.
Locally.
Example of custom fields on a course:
Example on the Custom Fields page:
> Timetable Admin: implement custom fields for Courses and Classes

- CHANGELOG.txt
- modules/Timetable Admin/ttDates.php
- modules/Timetable Admin/ttDates_addMultiProcess.php
- src/Domain/Timetable/TimetableDayDateGateway.php
- This PR adds a checkbox to the bottom of the Tie Days to Dates page, which enables overwriting existing TT day dates when adding new ones. 
- It also makes the weekday header sticky, to make it easier to see and select columns when scrolling through the whole year.
- Also tidies up the ttDates_addMultiProcess.php script.
When making a timetable change, currently one would need to manually delete existing entries, or use an SQL command to do so.
Locally.
> Timetable Admin: add an option to overwrite existing TT dates in Tie Days to Dates

- CHANGELOG.txt
- modules/System Admin/moduleFunctions.php
- modules/System Admin/module_manage.php
This PR adds a `$coreVersion` variable to a module's version.php file. This enables tagging which core version a module requires. If a module does not meet the minimum requirement, it cannot be installed or updated. It currently ignores version.php files that do not have a $coreVersion defined, which will enable us to add them in future module releases.
Help prevent errors with modules that require a different core version.
Locally.
> System Admin: prevent installing or updating a module that requires a newer core version

- CHANGELOG.txt
- modules/Reports/reports_generate_batch.php
- modules/Reports/reports_generate_batchProcess.php
- modules/Reports/reports_generate_single.php
- modules/Reports/reports_generate_singleProcess.php
Currently there is no way to delete reports once generated. This PR adds Delete as a bulk action to the Generate Reports page, on the bulk and single report generation pages. Deleting a report removes it from the archive and also deletes the PDF from the server. It is not necessary to delete a report before re-generating it, as it will be overwritten in that case.
I placed it in Generate Reports, rather than anywhere else, because there should be very few reasons to delete a report, and the only ones doing so should also be the ones able to create reports.
Occasionally, you may generate a report, draft or not, that you'd rather not show up in the report archive. This often happens during testing or debugging of reports, but can also occur in production.
**How …
> Reports: added an option to delete report files from Generate Reports page

- CHANGELOG.txt
- modules/Messenger/messenger_postProcess.php
- modules/Messenger/src/MessageProcess.php
Updates the send report email from Messenger to include any email addresses that failed to send.
Locally.
> Messenger: update the send report to list any emails that failed to send

- modules/Reports/src/Sources/AttendanceByCycle.php
- modules/Reports/src/Sources/CourseCriteriaByCycle.php
- modules/Reports/src/Sources/InternalAssessmentByCourse.php
- modules/Reports/src/Sources/ReportingCycle.php
- modules/Reports/templates/reports/attendance.twig.html
- modules/Reports/templates/reports/courseCriteriaByCycle.twig.html
- modules/Reports/templates/reports/internalAssessmentByCourse.twig.html
This PR adds to new sections to the Template Builder: Courses by Cycle and Internal Assessments by Course. These sections each include a new data source and a new template. They provide an example for displaying grades or criteria in a two-dimensional table. 
For the internal assessment example, assessments across multiple courses are displayed side-by-side. For the courses example, grades from previous reporting cycles are displayed side-by-side. Comments are still only shown for the current reporting cycle.
To assist schools in setting up their own reports with similar requirements.
Locally
Example report:
> Reports: add new data sources and templates for Internal Assessment and Course Criteria

- CHANGELOG.txt
- modules/Reports/templates_assets_components_edit.php
- modules/Reports/templates_assets_components_help.php
- modules/Reports/templates_assets_components_preview.php
This PR adds additional tools to help users when editing or creating their own template components. The first tool is a Help button at the top of the Edit Component page, which lists all available data sources and their available fields. The second tool is an Inspect option, similar to the Preview HTML page, which displays the data schema available to that template component.
Locally
**Screenshots**'
Help button along with Preview button:
Help page:
Preview page:
> Reports: added a help tool with Data Source information to Edit Component page

- modules/Attendance/src/StudentHistoryData.php
The $date is a object of class DateTimeImmutable, so it couldn't be converted to string 
> Attendance studentHistoryData - date format

- .github/workflows/ci.yml
Modify GitHub action workflow to add the developing PHP 8.1 as an experimental target. It means that CI workflow will test the target, but failure of it will not stop PR from merging.
PHP 8.1 is [now supported](https://github.com/marketplace/actions/setup-php-action#tada-php-support) in GitHub Actions. Adding it as a target could provide insight for Gibbon's potential forward compatibility issue, if any. Tests are run in parallel. There should be no perceivable time difference after adding the target.
In CI environment.
> Experimental php 8.1 test

- CHANGEDB.php
- CHANGELOG.txt
- modules/Reports/templates_manage.php
- modules/Reports/templates_manage_duplicate.php
- modules/Reports/templates_manage_duplicateProcess.php
This PR adds a duplicate option to the Template Builder.
Now that we're up and running with the Reports module, it's a common enough occurrence that a template needs changed in some way, while not changing the original copy of the template.
Locally.
> Reports: add a duplicate action in Template Builder

- CHANGEDB.php
- src/Database/Migrations/2021-05-20-PersonalDocuments.php
- src/Database/Migrations/2021-06-03-RemoveCitizenshipFields.php
- src/Domain/System/DataRetentionGateway.php
- src/Domain/User/PersonalDocumentGateway.php
This PR removes the citizenship fields from the database, since the data has already been migrated into personal document records. Also updates the PersonalDocument gateway to make it scrubbable. 
Requires #1360 (tests will fail until merged)
Locally
> System Admin: add a migration to remove citizenship fields, make Personal Documents scrubbable

- composer.json
- composer.lock
- src/Comms/Mailer.php
Resolve #1370. Fix CI test error caused by the PHPMailer upgrade.
* Well. #1370 failed.
* The `PHPMailer` class now lives within the namespace `PHPMailer\PHPMailer` instead of the global namespace.
* From [their upgrade guide](https://github.com/PHPMailer/PHPMailer/blob/v6.5.0/UPGRADING.md), I don't see any more changes that are needed.
CI environment.
> Bump phpmailer/phpmailer from 5.2.27 to 6.5.0

- CHANGELOG.txt
- error.php
- fullscreen.php
- gibbon.php
- index.php
- report.php
- resources/templates/error.twig.html
- src/View/Page.php
In the past, we've moved the error message page into a template, which is a nice way to ensure it's formatted and looks good. However, in the event that a fatal error occurs, the current error message may be plain text and looks jarring, especially if font-end users see it. 
This PR adjusts the error messages so that the soft-fail messages will use the template, but any hard-fail states will default back to an error.php page that contains enough HTML to render and still look okay. The error.php page does not depend on any functions or libraries, and should always be renderable.
Soft-fail:
Hard-fail:
> System: improved the appearance of the fatal error message page

- tests/unit/Gibbon/FileUploaderTest.php
* The mocked class name hould be "Session" instead of "session".
Working on some unit-test-related refactor. Came across this typo. Might have been tolerated by Windows or specific container setup. But was not suppose to work.
* Local CI test.
> Test: Fix typo in class name

- functions.php
- lib/paypal/expresscheckout.php
* With the statement, functions.php can never be included by itself.
And gibbon.php might not work within the context where functions.php
could be useful.
* The lib/paypal/expresscheckout.php includes functions.php, which
in turn includes gibbon.php (which includes functions.php). This is
purely redundent. Changed to include gibbon.php directly.
Another piece of my work needs to include the `functions.php` file. But since it includes `gibbon.php`, there are logics that stops things from working in my situation. There is no point blocking the include of `functions.php`. It should be dry and without unnecessary dependencies.
I've only found 1 direct include of `functions.php` in the code base in `lib/paypal/expresscheckout.php`. I figure it might …
> Remove gibbon.php include from functions.php

- modules/Reports/reporting_cycles_manage_editProcess.php
* In Reporting ([reporting_cycles_manage_editProcess.php](https://github.com/GibbonEdu/core/blob/v22.0.00/modules/Reports/reporting_cycles_manage_editProcess.php#L55-L58)), the submitted value `$_POST['milestones']` is supposed to be an array. However, if there is no milestone submitted, the value `$_POST['milestones']` would be not set.
* The null coercion in [line 48](https://github.com/GibbonEdu/core/blob/v22.0.00/modules/Reports/reporting_cycles_manage_editProcess.php#L48) would provide an empty string as the fallback value, which is not an array. This would cause issue in the array_map in [line 55-58](https://github.com/GibbonEdu/core/blob/v22.0.00/modules/Reports/reporting_cycles_manage_editProcess.php#L55-L58).
* Changing the fallback value from an empty string …
> Reporting: fix issue with empty milestone

- CHANGEDB.php
- CHANGELOG.txt
- modules/Reports/reports_send_batch.php
- modules/Reports/reports_send_batchProcess.php
- modules/Reports/src/SendReportsProcess.php
- modules/System Admin/emailTemplates_manage.php
- modules/System Admin/emailTemplates_manage_delete.php
- modules/System Admin/emailTemplates_manage_deleteProcess.php
- modules/System Admin/emailTemplates_manage_duplicate.php
- modules/System Admin/emailTemplates_manage_duplicateProcess.php
- src/Domain/System/EmailTemplateGateway.php
The email template feature isn't widely utilized (yet!), however to improve it's usability we discovered it'd be nice to be able to create and select specific templates for different tasks. In this case, we needed one email template for sending report cards home, one for sending transcripts. In hindsight, this feature does work best if the user can select which template to use, rather than having a single template.
This PR:
- Adds the ability to duplicate existing email templates, which tags them as "Custom"
- Adds the ability to delete custom email templates (but not the built in ones, so there's always at least one of each type)
- Adds a drop down to the Reports > Send Reports bulk action, which is the only area that uses Email Templates
- Adds table fields as needed to …
> System Admin: enable creating multiple different email templates per type

- CHANGEDB.php
- modules/System Admin/import_manage.php
- modules/System Admin/import_manageProcess.php
- src/Data/ImportType.php
The importCustomFolderLocation setting was previously attached to Data Admin, but after moving the functionality in to the core, the core ImportType.php file was still referencesing the Data Admin setting. This prevented anyone without Data Admin installed from changing the setting. I've fixed ImportType.php and added the setting as a small form at the top of the Import from File page.
Fixes #1391 
Locally
> System Admin: fix missing Custom Imports Folder setting

- modules/Data Updater/data_medicalProcess.php
- modules/Data Updater/data_medical_manage_editProcess.php
- modules/Finance/moduleFunctions.php
- modules/Markbook/markbook_edit_dataProcess.php
- modules/School Admin/daysOfWeek_manage.php
- modules/Students/applicationForm_manage_edit.php
- modules/System Admin/customFields_addProcess.php
- modules/System Admin/moduleFunctions.php
- modules/User Admin/user_manage_edit.php
- src/Domain/DataSet.php
- src/Forms/Input/Checkbox.php
- src/Forms/Input/TextArea.php
- src/Forms/Layout/Column.php
- src/Forms/PersonalDocumentHandler.php
- src/Forms/Traits/MultipleOptionsTrait.php
- src/Services/CoreServiceProvider.php
- src/Services/Format.php
- src/Tables/Columns/DraggableColumn.php
- src/UI/Components/Header.php
- src/View/View.php
Fix PHP code issues that causes any PHP Deprecated or Warning messages in CI test server_log.
* Improve forward compatibility with PHP 8.1 and PHP 9.0.
* Improve code quality and robustness.
* CI environment
* Run `grep 'PHP Warning\|PHP Deprecated' server_log` against the PHP 8.1 test artifacts. The total number of error and warning in it reduced from 4208 lines to 2018 lines. The remaining lines are mostly contributed by Twig, which will most likely have full PHP 8.1 support in the upcoming release (version v3.3.3 or v3.4.0).
> Fix PHP 8.1 warning deprecated messages in CI test

- src/UI/Components/Sidebar.php
- src/UI/Dashboard/ParentDashboard.php
* Replace with Format::userPhoto() calls.
* The function `getUserPhoto` was marked obsoleted in v16 but found some trace of it.
* Locally
> Remove uses of obsoleted getUserPhoto

- src/Gibbon/Session.php
- src/Services/CoreServiceProvider.php
* Extract container and environment / side-effect dependent logics into Session::create.
* Be specific about the variables that Session needed in its constructor.
* Changed the `CoreServiceProvider` to adapt it.
* `Session::__construct` was heavily depending on the environment and specific container setup.
* By separating the container dependency, now the Session is dry and easy to mock. It's much easier to debug, too.
In CI environment.
> Refactor Session constructor

- src/Contracts/Database/Connection.php
- src/Database/Connection.php
* Fix phpdocs for better IDE support.
* The original return was ambiguously "mixed", which was not very helpful describing what the select method would return.
* Especially annoying when I was working on rewriting some obsoleted `executeQuery()` calls to `select()`. VSCode complains that it does not know any method of the select result.
* Locally on my VSCode.
> Core: fix phpdoc for database connection select()

- src/Forms/FormFactory.php
- src/Forms/FormFactoryInterface.php
- src/Forms/Traits/MultipleOptionsTrait.php
* Add phpdocs to FormFactoryInterface::createSelect.
* Add phpdocs to FormFactory::createSelect
* Properly document the return value of MultipleOptionsTrait::fromResult
* Fix IDE support to developers.
* Locally on VSCode.
Before
After
> Docs: form factory and traits phpdocs fix

- composer.json
- composer.lock
* Add [phpstan](https://phpstan.org/) as development dependency.
* Add `composer test:phpstan` script target.
* Did **NOT** add this to default test target. So will **NOT** be run in CI for now.
* PHPStan scan and catches PHP issues for the corner cases that user would rarely run into. Have a test like this can improve our overall robustness.
* Will gradually fix all the potential errors found by PHPStan in the code base. When all errors are fixed, can add this into regular test target.
* Locally with the `composer test:phpstan` command.
> Composer: add phpstan test

- src/Comms/Drivers/MailDriver.php
* DriverNotConfiguredException is from SMS library namespace. Added
proper use statement to fix it.
* Fix issue found by PHPStan
* Locally with PHPStan
> System: fix Exception reference in MailDriver

- src/Data/UsernameGenerator.php
* fix \InvalidArgumentException reference in Gibbon\Data\UsernameGenerator. The root class reference was without the "\" prefix.
* Found this bug in the middle of other project.
* Locally in VSCode.
> System: fix InvalidArgumentException use in class

- src/Gibbon/Excel.php
* Change the `@return` of Excel::exportWithQuery from `string` to `void`.
* Gibbon\Excel::exportWithQuery does not return anything. The
string result is directly output to STDOUT stream of
cgi / fastcgi server. The phpdocs should reflect that.
* Locally on VSCode.
> System: correct phpdocs in Gibbon\Excel::exportWithQuery

- modules/Markbook/markbook_edit_addMultiProcess.php
- modules/Markbook/markbook_edit_addProcess.php
- modules/Markbook/markbook_edit_dataProcess.php
- modules/Markbook/markbook_edit_deleteProcess.php
- modules/Markbook/markbook_edit_editProcess.php
- modules/Markbook/markbook_edit_targetsProcess.php
- modules/Markbook/weighting_manage_addProcess.php
- modules/Markbook/weighting_manage_deleteProcess.php
- modules/Markbook/weighting_manage_editProcess.php
- modules/Messenger/cannedResponse_manage_addProcess.php
- modules/Messenger/cannedResponse_manage_deleteProcess.php
- modules/Messenger/cannedResponse_manage_editProcess.php
- modules/Messenger/groups_manageProcessBulk.php
- modules/Messenger/groups_manage_addProcess.php
- modules/Messenger/groups_manage_deleteProcess.php
- modules/Messenger/groups_manage_editProcess.php
- modules/Messenger/groups_manage_edit_deleteProcess.php
- modules/Messenger/messenger_manage_deleteProcess.php
- modules/Messenger/messenger_manage_editProcess.php
- modules/Messenger/messenger_manage_report_processBulk.php
- modules/Messenger/messenger_postPreProcess.php
- modules/Messenger/messenger_postQuickWallProcess.php
Second pass of null coalesce in Markbook and Messenger modules, mainly updating URLs.
> Markbook, Messenger - null coalesce second pass

- modules/Finance/expenses_manage_processBulkExportContents.php
- modules/Finance/invoices_manage_processBulkExportContents.php
- modules/Library/report_catalogSummaryExportContents.php
- modules/Markbook/markbook_viewExportAllContents.php
- modules/Markbook/markbook_viewExportContents.php
- src/Gibbon/Excel.php
* Modules: rewrite modules usage of Gibbon\Excel::estimateCellCount  
* follow the estimateCellCount update to retire use of obsoleted
Gibbon\Database\Connection::getResult() method.
* System: update Gibbon\Excel::estimateCellCount  
* Rewrite to accept \Gibbon\Database\Result in addition to the
original \Gibbon\Contracts\Database\Connection.
* Should remove the direct use of Connection::getResult in the
future for it is obsoleted.
* Connection::getResult is deprecated but the old estimateCellCount logic
rely on it.
* Locally.
> Refactor Gibbon\Excel::estimateCellCount to migrate away from Connection::getResult

- src/Data/ImportType.php
- src/Data/Importer.php
- src/Data/UsernameGenerator.php
- src/Domain/DataUpdater/DataUpdaterGateway.php
- src/Forms/DatabaseFormFactory.php
- src/Forms/Input/Select.php
- src/Forms/Traits/MultipleOptionsTrait.php
- src/Gibbon/FileUploader.php
- src/Gibbon/Locale.php
- src/Gibbon/Session.php
- tests/unit/Gibbon/FileUploaderTest.php
* Replace all usage of obsoleted Connection::executeQuery to
Connection::select in the core.
* Update FileUploaderTest to mock select instead of
executeQuery.
* Connection::executeQuery is obsoleted since v16. It's usages should be rewritten with Connection::select.
* Locally.
* CI Environment.
> System: rewrite usage of obsoleted Connection::executeQuery in core

- tests/unit/Gibbon/Locale/MockGibbonTrait.php
- tests/unit/Gibbon/Locale/MockGuidTrait.php
- tests/unit/Gibbon/Locale/TranslateNTest.php
- tests/unit/Gibbon/Locale/TranslateTest.php
- tests/unit/Gibbon/Locale/TranslationTest.php
- tests/unit/Gibbon/Locale/mock/i18n/es_ES/LC_MESSAGES/gibbon.po
- tests/unit/Gibbon/Locale/mock/i18n/gibbon.pot
- tests/unit/Gibbon/Locale/mock/i18n/zh_TW/LC_MESSAGES/gibbon.po
* Mock global $gibbon and $guid locally in the test class and restore original after the test.
* Simplify Locale shortcut test to test only how it uses `$gibbon->locale->translate` and
`$gibbon->locale->translateN`. Not the actual result.
* Remove the dependency on bootstraped global $gibbon for Locale related tests.
* Simplify tests.
* Locally.
> Refactor Locale test

- src/Database/Connection.php
* Migrate `MySqlConnector::configureEncoding` to `Connection::configure`.
* Migrate `MySqlConnector::setModes` to `Connection::setModes`.
* Migrate the usage of the above methods into `Connnection::__construct`.
* Previously, the class `Connection` depends on the convention to use to  `MySqlConnector` the `PDO` object.
* `Connection` do not directly use `MySqlConnector` in anyway. The dependency is not obvious and can cause unexpected behaviour in the future development.
* Migrating the PDO configuration into `Connection` improves that while still preserve the current behaviour.
* Locally.
* CI Environment.
> Refactor database Connection and MySqlConnector

- composer.json
- composer.lock
Remove the unofficial fork from the composer setup.
* Originally, the old fork was used to keep using older tcpdf version without having to fetch so many tags with GitHub API (has API limit issue). After #1209, updating vendor dependencies became much easier. Seems no longer have issue on GitHub API front after upgrade.
* The tcpdf used was so old. Should be upgraded for various reason.
> composer: use latest tcpdf in packagist

- src/Domain/System/DataRetentionGateway.php
* Remove the method \Gibbon\Domain\System\DataRetentionGateway::getAllTables.
* The method seems to be obsoleted artifact in the development
process. It is not used anywhere in the code base. Also the
property it is accessing was not set at all. Should be removed.
* Locally.
> System: remove DataRetentionGateway::getAllTables

- src/Comms/NotificationEvent.php
* Class name session should be Session.
* Fix error found by PHPStan
> System: fix typo in NotificationEvent

- src/Contracts/Database/Result.php
- src/Database/Result.php
* Fix documentation error.
* The return type specified was array while it returns
\Gibbon\Domain\DataSet.
> System: fix incorrect phpdocs for Result::toDataSet

- src/Forms/Input/Select.php
* getLabelContext is documented to return string. It should return
at least an empty string even if the attribute 'multiple' is not
true.
* Fix issue found by PHPStan.
* CI Environment.
> System: fix Select::getLabelContext

- src/Services/BackgroundProcessor.php
* The background command sprintf has more supplied arguments than
placeholder. Should remove unnecessary ones.
* Use "> /dev/null" for Windows background command.
* The original sprintf statement has error.
* Windows CMD equivalent of "> /dev/null" would be "> NUL".
> System: fix BackgroundProcessor sprintf issue

- .editorconfig
- .htaccess
- composer.json
- phpstan.neon
* Use phpstan.neon to config the behaviour instead of using the
CLI arguments. Much cleaner and more readable.
* Define how to format a .neon file in .editorconfig to ensure
consistancy.
* The old way misses all moduleFunctions.php when scanning for functions. Adding all those files to command argument would be a huge pain in the ass. Using a config file is more sensible.
* Locally.
> Test: phpstan to use config file

- CHANGEDB.php
- CHANGELOG.txt
- cli/attendance_dailyIncompleteEmail.php
- cli/attendance_dailyIncompleteEmail_byClass.php
- cli/attendance_weeklySummaryEmail.php
- cli/behaviour_dailySummaryEmail.php
- cli/behaviour_letters.php
- cli/library_overdueNotification.php
- cli/schoolAdmin_parentDailyEmailSummary.php
- cli/schoolAdmin_parentWeeklyEmailSummary.php
- cli/schoolAdmin_tutorDailyEmailSummary.php
- cli/userAdmin_statusCheckAndFix.php
- modules/System Admin/privacySettings.php
- modules/System Admin/privacySettingsProcess.php
Allows administrators to set a key to enable CLI scripts to be run via HTTP/S. Off by default.
Sometimes it is not possible to run CLI scripts locally due to hosting constraints. This allows them to be run remotely with a reason level of security.
Locally
> Remote CLI

- modules/Activities/report_attendance_byDate.php
- modules/Attendance/attendance.php
- modules/Attendance/report_courseClassesNotRegistered_byDate.php
- modules/Attendance/report_formGroupsNotRegistered_byDate.php
- modules/Attendance/report_graph_byType.php
- modules/Attendance/report_studentsNotInClass_byDate.php
- modules/Attendance/report_summary_byDate.php
- modules/Behaviour/behaviour_manage_add.php
- modules/Behaviour/behaviour_manage_addMulti.php
- modules/Behaviour/behaviour_pattern.php
- modules/Individual Needs/investigations_manage_edit.php
- modules/Individual Needs/investigations_submit_detail.php
- modules/Staff/applicationForm.php
- modules/Students/applicationForm.php
- modules/Students/applicationForm_manage_edit.php
- modules/Timetable/spaceBooking_manage_add.php
- publicRegistration.php
Cleaning up some redundant code. The Date class in the Form namespace automatically appends a Format: description with the current system date format, so these instances in the code that manually add the format are unnecessary.
DRY
Locally
> System: remove unnecessary Formats on date fields

- CHANGELOG.txt
- modules/Timetable/report_viewAvailableSpace_view.php
- modules/Timetable/report_viewAvailableSpaces.php
- modules/Timetable/report_viewAvailableTeachers.php
- modules/Timetable/report_viewAvailableTeachers_view.php
- modules/Timetable/spaceBooking_manage_addAjax.php
- modules/Timetable/spaceChange_manage_add.php
- modules/Timetable/spaceChange_manage_addAjax.php
- src/Domain/School/FacilityGateway.php
- src/Domain/Staff/StaffGateway.php
- src/Domain/Timetable/CourseEnrolmentGateway.php
- src/Domain/Timetable/TimetableDayDateGateway.php
Currently, the View Available Facilities and View Available Teachers reports have a hover-over with information. However, there is often too much information to see before the hover-over fades, as well as not enough information about the facility/teacher themselves. This PR adds an on-click option to these reports, with a modal window that displays more information about the selected facilities/teachers.
Also, the Add Facility Change option didn't tell users if the facility was in use or not, so you needed to do lots of manual cross-checking to see what's available. This PR adds an ajax check when you have a time slot and facility selected, and lets you know if its Available or In Use.
This is not a full refactor. I've cleaned up some areas of the View Available Facilities/Teachers …
> Timeable: improve View Available Facilities/Teachers reports and Add Facility Change

- index.php
- indexFindRedirect.php
- passwordResetProcess.php
- resources/templates/index.twig.html
- resources/templates/mail/email.twig.html
- src/Http/Url.php
- src/UI/Dashboard/StaffDashboard.php
- src/UI/Dashboard/StudentDashboard.php
- src/View/Components/Breadcrumbs.php
- tests/unit/Gibbon/UrlTest.php
We were running into bugs related to the fact that Gibbon relies on using absoluteURL in many areas, but the new Url class was returning a relative URL. These affected the breadcrumbs, fast finder, timetable, password reset, etc. 
For example:
- Breadcrumbs with an absoluteURL of `http://localhost:8888/gibbon/` were ending up as `http://localhost:8888/gibbon/gibbon/index.php?q=/modules/System Admin/systemOverview.php` because the url was relative, so browsers were prepending the current url, but the path has also been parsed and added to the url route path.
- The timetable was not working because the ajax load script was expecting an absolute path and was receiving a relative one.
- Preferences links in notification emails were not working because the NotificationSender was putting a …
> System: fix Url class not returning an absolute URL

- .github/workflows/ci.yml
* Modify CI test to treat "Warning: " or "PHP Warning: " in server_log as test failure.
* Detects php issues when they are committed for submit. Much easier to identify the code relevant to the warning message.
* Just cleared all the issues that creates those kind of message. It is a good point in time to do so.
> Improve warning detection in test

- modules/Attendance/attendance_future_byPerson.php
- Added a rule: the "Date End" field has a minimum value of 2 days more than the current day
- Translation support to Type field
If you choose Absence type = full day, the system allows the value of the "End date" previous to current day.
> Added translation support in attendance types and fixed the End date field

- installer/install.php
- tests/install/InstallCept.php
* Fix the "go to Gibbon homepage" link in the message on step 4 of installation.
* Update InstallCept to check if the link goes to the home page.
* See issued reported by [tiekubd](https://ask.gibbonedu.org/profile/tiekubd) on [this Gibbon Support Forum thread](https://ask.gibbonedu.org/discussion/comment/9434)
* Locally.
> Installer: fix homepage link generation

- CHANGELOG.txt
- login.php
- src/Auth/Adapter/AuthenticationAdapter.php
- src/Auth/Adapter/OAuthGenericAdapter.php
- src/Auth/Adapter/OAuthGoogleAdapter.php
- src/Auth/Adapter/OAuthMicrosoftAdapter.php
This PR fixes an issue discovered by Glenn [in the forums](https://ask.gibbonedu.org/discussion/3544/view-logs-works-differently#latest), and improves overall login logging.
- Fixes missing username in the User column in System Admin > View Logs
- Updates the login logs to include the attempted gibbonPersonID, even on failures
- Updates OAuth logins to return the user/email attempted for the login
- Updates all login logs to include the method, regardless of success or failure
Accurate login logs help system admins look for anomalies. It's also helpful to know the method used for login, even on success.
Locally
> System: improve logs for login process, fix login info in View Logs

- CHANGELOG.txt
- modules/System Admin/moduleFunctions.php
- modules/System Admin/systemCheck.php
- modules/System Admin/systemOverview.php
This PR improves the uploads folder check, so it looks at the response body as well as the status code, reducing the chance of false positives.
- Extends the range of the status code check to any 4xx code.
- Checks for positive and negative keywords in the response body.
- Checks the content of Guzzle exception messages, which may include status codes.
- Updates the translation string so that it is not based on the status code.
Some schools were seeing false positives for the uploads check, which can be alarming.
Locally and some specific remote servers, which had reported issues.
> System Admin: improve the reliability of the uploads folder check

- src/UI/Dashboard/ParentDashboard.php
Updates the Planner module with the option to create and link a new Markbook Column when editing an already existing lesson plan.
Added lines to planner_edit and planner_editProcess that allows for the creation and linking of a Markbook Column when submitting a change to an already existing lesson plan.
This helps when planning lessons ahead of time, and a teacher doesn't know whether or not there will be homework. Now, a lesson can be planned ahead, and edited later with the opportunity to add a linked Markbook Column entry to the system.
Tested and verified on a personal installation of Gibbon v22.
> Update Planner Edit

- CHANGEDB.php
- CHANGELOG.txt
- modules/Messenger/messenger_manage.php
- modules/Messenger/messenger_manage_edit.php
- modules/Messenger/messenger_manage_editProcess.php
- modules/Messenger/messenger_post.php
- modules/Messenger/messenger_postPreProcess.php
- modules/Messenger/messenger_postProcess.php
- src/Database/Migrations/2021-03-03-MedicalFields.php
- src/Domain/Messenger/MessengerGateway.php
Generally messages are only viewable by the person who sent them, as the default permission is "Manage Messages_my." However, any admin or other user with "Manage Messages_all" permission can see all messages sent by all users. This PR adds the option to give select users the "New Message_confidential" permission, which enables them to send messages which do not show up for any other user regardless of their permissions.
- Adds a `confidential` field to the gibbonMessenger table.
- Adds a permission `New Message_confidential`, enabled for admin only by default.
- Checks permissions and confidential flag on Manage Messages and Edit Message pages.
- Checks confidential flag when using the BCC messages option.
- Adds a visual `Confidential` tag to messages in Manage Messages.
**Motivation …
> Messenger: add the abiliy to send confidential messages

- resources/assets/js/setup.js
- resources/templates/components/form.twig.html
- resources/templates/index.twig.html
- src/Forms/Form.php
- themes/Default/css/main.css
Updates forms so that long forms, those with more than 10 fields, have a floating submit button. The submit-button-row changes colour when floating, to differentiate it from other fields and make it clearer that it's not the bottom of the form.
Makes it easier for users to save changes when working with long forms, especially users and planners.
Locally.
> Forms: add sticky submit button for long forms

- .github/workflows/ci.yml
- modules/Markbook/src/MarkbookView.php
- src/Data/Validator.php
- src/Database/Migrations/2021-08-01-GoogleSettings.php
* Add PHP 8.2 as a test target of Gibbon.
* Fix all issues that causes deprecation warning in the unit test.
* [PHP 8.2RC1](https://www.php.net/archive/2022.php#2022-09-01-4) has been released. It's perhaps time to include the version for testing.
> PHP 8.2 Compatibility

- gibbon.php
* Remove autoloading support to autoload class like: "Gibbon\SomeModule\MyClass" -> "modules/Some Module/MyClass.php"
* The backward compatibility was introduced in f4fde610be (Nov 2018).
* As the comment stated, it was "Temporary backwards-compatibility for external modules (Query Builder)".
* I've checked the latest version of [Query Builder](https://github.com/GibbonEdu/module-queryBuilder/tree/806de79f3f19564637fae038fb87833b852486a2). The legacy class namespace style doesn't seem to exists anymore.
* Locally
> Remove legacy class namespace compatibility

- tests/phpunit.xml
* Do the phpunit suggested fix to the configuration file format (running `phpunit --migrate-configuration`).
* phpunit was suggesting the change.
* CI environment
* Locally
> Test: migrate phpunit.xml file format

- CHANGELOG.txt
- modules/Markbook/markbook_view_myMarks.php
- src/Domain/School/SchoolYearTermGateway.php
Adds a Term filter to the student view of the Markbook, which defaults to the current term when possible. This is only made available when the Markbook setting *Group Columns by Term* is set to Yes.
Requested by a school whose assessment tends to be oriented to term, and who already uses Group Columns by Term.
Locally, with a limited set of testing data.
> Markbook: added Term filter to student view, when Group Columns by Term enabled

- .github/workflows/ci.yml
- composer.json
- composer.lock
* Upgrade phpstan to the latest version to be compatible with the latest php.
* Make phpstan a part of CI test but allow it to fail.
* The static analysis provided by the tool catches many potential issues in the code base.
* It would be good if the test is run against any changes made to the code base before merging in the future.
* After this is merged, will gradually add fixes to the codebase until all phpstan tests are passed.
* Locally.
> Make phpstan a part of standard tests

- tests/unit/Gibbon/Locale/TranslationTest.php
* translation test should be skipped if the translation files are not installed.
* to remind developer to install i18n files before running some of the tests.
* Locally.
> Tests: translation test to skip if needed

- src/Forms/DatabaseFormFactory.php
Fix phpdocs namespace usage.
* Types in phpdocs should either be short name (refers to type specified in use statement) or starts from root.
* Locally with VSCode and [Intelephence](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client).
> System: improve documentation for DatabaseFormFactory

- modules/Reports/src/Contexts/NullContext.php
- modules/Reports/src/DataContext.php
* Fix the parameter list of NullContext::getIdentifiers().
* Improve documentation to the DataContext interface.
* NullContext::getIdentifiers() has 1 more parameter than the DataContext::getIdentifiers() and hence failed to implement DataContext. Reading the code and see the parameter list is wrong.
* Locally
> Fix Reports NullContext compliance with the DataContext interface

- gibbon.php
* $_SERVER['HTTP_HOST'] would be unset for CLI access (e.g. unit test) and thus should be used with fallback value coercion.
* To suppress warning message in test envrionment.
* Locally with phpunit.
> System: gracefully handle empty HTTP_HOST

- tests/unit/Forms/FormTest.php
- tests/unit/Services/ViewServiceProviderTest.php
* The behaviour of From::create was actually testing the behaviour of container with ViewServiceProvider. Moved the unit test out to its own thing to improve the tests.
* To remove dependency of test that requires gibbon.php setup.
* Locally
> Tests: moved service behaviour away from FormTest

- modules/Students/student_view_details.php
* Minor rewrite to fix issue of IDE type inference.
* Previously written code calls `setCriteria` on a `RendererInterface`, which does not have a `setCriteria` method.
* Causes IDE static analysis warning.
* Locally with VSCode and [Intelephense](https://intelephense.com/)
Before
After
> Students: fix minor code style issue

- .github/workflows/ci.yml
* Check server log for uncaught exceptions in CI.
* Turns out when there are uncaught exception in our test and if it doesn't affect the text / element our acceptance tests are checking, all test would still be passed.
* Checking of "uncaught exception" in logs can catch a new class of issues in our test process even if we don't have test written for them.
> Test: check uncaught exception in test

- functions.php
- modules/Planner/moduleFunctions.php
- modules/Planner/planner_editorAjax.php
- src/Forms/FormFactory.php
- src/Forms/Input/Editor.php
- src/Forms/Traits/InputAttributesTrait.php
* Editor::getElement() is refactored to handle its own rendering instead of relying on getEditor.
* All getEditor calls can then be rewrite to use Editor directly.
* The getEditor() function is marked obsoleted. It is kept for module developers to adapt the change.
The function getEditor can be, and should be, completely replaced by the Editor class itself.
* CI Environment
> Refactor: make getEditor function obsoleted

- functions.php
- src/Gibbon/Locale.php
* If a global $gibbon->locale does not exists, the function __ can fallback on Locale::formatString. Prevent unit test using __ to rely on specific global $gibbon setup.
* Prevent error if the global variable is not setup properly.
* Locally.
> System: translation function fallback

- functions.php
- modules/Data Updater/data_medical_manage_editProcess.php
- modules/Formal Assessment/internalAssessment_write.php
- modules/Markbook/markbook_view.php
- modules/Markbook/markbook_viewExportAllContents.php
- modules/Markbook/markbook_viewExportContents.php
- modules/Students/medicalForm_manage_condition_addProcess.php
- modules/Students/medicalForm_manage_condition_editProcess.php
- modules/Students/student_view_details.php
- src/Domain/System/AlertLevelGateway.php
- src/UI/Dashboard/ParentDashboard.php
* Create AlertLevelGateway class with a getByID() method.
* Mark getAlert() deprecated.
* Rewrite all getAlert() calls with AlertLevelGateway::getByID().
* Replace functions.php function with gateway implementation.
* Locally.
> System: replace getAlert with AlertLevelGateway method

- functions.php
- modules/User Admin/rollover.php
- src/Domain/School/YearGroupGateway.php
* Mark getNextYearGroupID() deprecated.
* Implemented YearGroupGateway::getNextYearGroupID().
* Replace usage of getNextYearGroupID() with YearGroupGateway::getNextYearGroupID().
* Mark getLastYearGroupID() deprecated.
* Implemented YearGroupGateway::getLastYearGroupID().
* Replace usage of getLastYearGroupID() with YearGroupGateway::getLastYearGroupID().
* Replace functions.php functions with gateway methods.
> School: replace functions with YearGroupGateway methods

- cli/attendance_dailyIncompleteEmail.php
- cli/attendance_dailyIncompleteEmail_byClass.php
- cli/attendance_weeklySummaryEmail.php
- cli/behaviour_dailySummaryEmail.php
- cli/behaviour_lettersNegative.php
- cli/behaviour_lettersPositive.php
- cli/library_overdueNotification.php
- cli/schoolAdmin_parentDailyEmailSummary.php
- cli/schoolAdmin_parentWeeklyEmailSummary.php
- cli/schoolAdmin_tutorDailyEmailSummary.php
- cli/system_backgroundProcess.php
- cli/userAdmin_statusCheckAndFix.php
- functions.php
- login.php
- modules/Planner/units.php
- modules/Timetable Admin/course_rollover.php
- modules/User Admin/rollover.php
- preferencesPasswordProcess.php
- preferencesProcess.php
- src/Domain/School/SchoolYearGateway.php
- src/UI/Components/Sidebar.php
* Mark setCurrentSchoolYear() deprecated.
* Add SchoolYearGateway::setCurrentSchoolYear() that provdes the exact feature.
* Rewrite Finance module usage of setCurrentSchoolYear() to SchoolYearGateway::setCurrentSchoolYear().
* Mark getPreviousSchoolYearID() and getNextSchoolYearID() deprecated.
* Replace all getPreviousSchoolYearByID() calls with SchoolYearGateway::getPreviousSchoolYearByID().
* Replace all getNextSchoolYearByID() calls with SchoolYearGateway::getNextSchoolYearByID().
* Replace functions.php functions with relevant SchoolYearGateway method.
> Refactor: SchoolYearGateway methods to replace functions.php relevant functions

- src/Domain/System/ModuleGateway.php
* Fix `@return` of ModuleGateway::selectModuleActionsByRole.
* The method ModuleGateway::selectModuleActionsByRole was documented to have return array. It actually returns Gibbon\Contracts\Database\Result.
* Found out the issue from intelephense error message (attempt to call the Result::fetchGrouped method from, according to phpdocs, an array).
* Locally with VSCode
> System: fix phpdocs for ModuleGateway

- src/Install/Installer.php
* Fix return type in phpdocs for getConnection() and getPDO().
* Incorrect return type documented for getConnection() and getPDO().
* Locally in VSCode.
> Install: fix phpdocs of Installer

- .github/workflows/ci.yml
* Updating [actions/checkout](https://github.com/actions/checkout), [actions/cache](https://github.com/actions/cache) and [actions/upload-artifact](https://github.com/actions/upload-artifact) used in the CI configuration.
* Remove "save-state" warning messages in GitHub actions page.
* Fix node version warning in GitHub workflow process.
* GitHub.
> GitHub Actions: upgrade actions used

- functions.php
- src/Services/Format.php
* Mark daysUntilNextBirthday and is_leap_year deprecated.
* A new Format::daysUntilNextBirthday protected method to replace daysUntilNextBirthday() in functions.php. The new method is re-implemented with PHP core's \DateTime.
* The function daysUntilNextBirthday() is only used by the Format class.
* The function is_leap_year() is only used by daysUntilNextBirthday().
* The logics are based on explicit leap year calculation, which is also done internally with PHP's own DateTime implementation.
* Functions that do not needed to be public should be kept as implementation details within a class.
* Locally.
> System: refactor birthday calculation logics and functions

- cli/attendance_dailyIncompleteEmail.php
- cli/attendance_dailyIncompleteEmail_byClass.php
- cli/attendance_weeklySummaryEmail.php
- cli/behaviour_dailySummaryEmail.php
- cli/behaviour_lettersNegative.php
- cli/behaviour_lettersPositive.php
- cli/library_overdueNotification.php
- cli/schoolAdmin_parentDailyEmailSummary.php
- cli/schoolAdmin_parentWeeklyEmailSummary.php
- cli/schoolAdmin_tutorDailyEmailSummary.php
- cli/system_backgroundProcess.php
- cli/userAdmin_statusCheckAndFix.php
- functions.php
- gibbon.php
- login.php
- preferencesPasswordProcess.php
- preferencesProcess.php
- src/Domain/School/SchoolYearGateway.php
- src/Gibbon/Core.php
- src/Session/SessionFactory.php
- src/UI/Components/Sidebar.php
After merging #1669 I got looking at the code and there appeared to be some school year setup code that ended up scattered throughout CLI scripts and other locations, rather than in one initialization step.
@yookoala I've moved the setCurrentSchoolYear method out of the SchoolYearGateway into the SessionFactory, as this prevents the Gateway class from needing session dependencies, and puts more of the session initialization code in the SessionFactory, which is then called during the Gibbon initializeCore method. This enabled using a single try-catch for exception handling, instead of needing several throughout the system.
This also has fixed an esoteric bug where the current school year wasn't available directly after logging out unless setCurrentSchoolYear was called manually, so I've …
> System: move school year session setup to SessionFactory

- CHANGEDB.php
- CHANGELOG.txt
- modules/Timetable Admin/tt_edit.php
- modules/Timetable Admin/tt_edit_byClass.php
- modules/Timetable Admin/tt_edit_byClassProcess.php
- src/Domain/Timetable/TimetableColumnGateway.php
- src/Domain/Timetable/TimetableDayGateway.php
- src/Domain/Timetable/TimetableGateway.php
This is a very handy timetabling tool that exists in the Course Selection module. I've now added it to the core when editing a timetable in Timetable Admin > Manage Timetables.
Adds an "Edit Timetable by Class" option to the Edit Timetable page in Manage Timetables. Added it here, rather than as a separate action, because it is a logical location for tools related to editing a timetable, and it reduces the complexity of needing to select a timetable and school year first.
Changing the timetable for a class currently requires hunting down the individual entries in each timetable day and period. This makes it easier to add/edit/remove timetabling for a single class. Thanks to Ray Clark for adding the smart-block-style interface.
**How Has This Been …
> Timetable: add an Edit Timetable by Class tool to Manage Timetables

- functions.php
* properly document the function.
* mark getHighestMedicalRisk as deprecated.
* Improve documentation.
* Warn developer from using the deprecated function (since #1667).
* Locally in IDE.
> Students: fix phpdocs for getHighestMedicalRisk

- functions.php
- modules/Behaviour/behaviour_letters.php
- modules/Behaviour/behaviour_manage.php
- modules/Behaviour/moduleFunctions.php
- modules/Individual Needs/investigations_manage.php
- modules/Individual Needs/investigations_manage_edit.php
- modules/Students/firstAidRecord.php
- modules/Students/medicalForm_manage.php
* Replace nl2brr() calls with nl2br().
* Mark nl2brr() as deprecated.
* Changed behaviour: "\r\n" would have been converted to 2 `<br/>` will now be converted to 1 single `<br/>`.
* From the source code, nl2brr turns \r\n, \r and \n into HTML `<br/>` tag. And PHP's native nl2br does that and also converts \n\r.
So it seems nl2brr specifically single out \n\r and not handle it. This doesn't seem to really matter in most cases.
* nl2br() is a C native implementation while nl2brr() is written with preg_replace(), which is much slower.
* Reduce unnecessary function would reduce effort if handling the code base.
* Locally.
> Deprecate nl2brr

- CHANGELOG.txt
- modules/Attendance/attendance_future_byPerson.php
- modules/Attendance/attendance_future_byPersonProcess.php
- modules/Attendance/attendance_take_adHoc.php
- src/Domain/Attendance/AttendanceLogPersonGateway.php
- src/Forms/Input/Checkbox.php
Improves the Set Future Absence tool to enable using ad hoc groups for attendance, and setting partial class attendance for a group of students. When selecting a group of students for a partial absence, a time range is entered, and then a grid of student photos will be displayed with the classes for each student selected for that time range. Prior absences will be listed but disabled so they cannot be checked.
Adds a disabled method to the Checkbox input to enable setting an array of checkbox value-keys that are disabled in the list. This enabled displaying specific values that are not selectable in a single checkbox list.
I've tidied up the code along the way, but this has certainly added some complexity to the future absence scripts. Overall, worth the trade-off given the usability it …
> Attendance: add the option to take future attendance for ad hoc groups

- functions.php
- modules/Staff/applicationForm_manage_accept.php
- modules/Students/applicationForm_manage_accept.php
- src/Services/Format.php
* Add Format::emailBodyConvert to replace emailBodyConvert() in
functions.php.
* Mark emailBodyConvert() deprecated.
* Replace emailBodyConvert() calls with Format::emailBodyToPlain().
* Deprecated global functions in favour of class methods.
* Locally.
> Services: replace emailBodyConvert calls with Format::emailBodyToPlain

- src/Data/ImportType.php
* Use explicit type-cast on ImportType::getField() return values in various methods of ImportType to supress type warning or error when using those variables.
* PHP 8+ deprecates the use of implicit type casting on some core function parameters. Explicit type-casting will solve the potential issues in the future.
* Checks with VSCode IDE.
> Data: explicit type-cast in ImportType

- src/Services/Format.php
* phpstan seems to think IntlDateFormatter constructor to require at least the first 3 parameter (despite documented otherwise in php.net). Update to fix phpstan warning.
* Fix phpstan warning message.
* Locally.
> System: fix dateRangeReadable usage of IntlDateFormatter

- cli/schoolAdmin_parentWeeklyEmailSummary.php
- functions.php
- modules/Activities/activities_paymentProcessBulk.php
- modules/Finance/invoices_manage_addProcess.php
- modules/Messenger/src/MessageTargets.php
- modules/Staff/applicationForm_manage_accept.php
- modules/Students/applicationForm_manage_accept.php
- modules/System Admin/import_history.php
- modules/System Admin/import_manage.php
- passwordResetProcess.php
- src/Data/ImportType.php
- src/Data/PasswordPolicy.php
- src/Forms/Builder/Process/CreateParents.php
- src/Forms/Builder/Process/CreateStudent.php
- src/Gibbon/FileUploader.php
- tests/unit/Data/PasswordPolicyCest.php
* Add a new PasswordPolicy::generate method to generate a random password that's conforming to the rules defined for the instance.
* Rewrite all randomPassword usages with PasswordPolicy::generate().
* Fix issue when randomly generated password doesn't meet site password policy settings.
* Deprecate usage of randomPassword.
* Locally.
> System: deprecate randomPassword

- .github/workflows/ci.yml
* phpstan test will be essential to pass for every CI test.
* That would also make the test essential for all PRs.
* phpstan starts to catch some issue in PRs that format test don't.
* Level 0 is mild and easy to handle for developers. Should be a nice start.
> GitHub Actions: make phpstan (level 0) test essential

- CHANGEDB.php
- CHANGELOG.txt
- modules/Attendance/attendance_take_byCourseClass.php
- modules/Attendance/attendance_take_byCourseClassProcess.php
- modules/Planner/planner_view_full.php
- src/Domain/Timetable/TimetableDayDateGateway.php
- src/Forms/Traits/MultipleOptionsTrait.php
Currently, if a class is timetabled for multiple lessons on the same day, it only has one attendance record, and submitting the attendance again with update the existing attendance. There was also a bug where students with timetable exceptions from one class were also not being listed in other classes on the same day.
This PR adds a gibbonTTDayRowClassID field to the attendance log for class attendance to track exactly which timetable period the attendance was taken for. It is backwards compatible, handling null values in the field by default, and has been prefilled in the background for lesson plan attendance.
When a class is timetabled multiple times, the user will be prompted to select which timetable period they are taking attendance for.
Also updates the fromArray method on input …
> Attendance: fix attendance for classes timetabled multiple times on the same day

- cli/attendance_dailyIncompleteEmail.php
- cli/attendance_dailyIncompleteEmail_byClass.php
- modules/School Admin/schoolYearSpecialDay_manage.php
- modules/School Admin/schoolYearSpecialDay_manage_add.php
- modules/School Admin/schoolYearSpecialDay_manage_edit.php
- modules/Timetable/moduleFunctions.php
Earlier in the dev cycle we added Off Timetable as an option for Special Days, with an option to select year groups. This PR extend that functionality with the option to alternatively set form groups off timetable for the day.
- Enables the selection of Form Groups when adding/editing a special day
- Updates the timetable logic to display full days off timetable to students by form group or year group
- Updates the timetable logic to show classes off timetable to teachers, provided all students in the class are also off timetable
- Updates the attendance CLI scripts to not sent to teachers if their class/form group is off timetable for the day
- Highlights the current day in the Special Days list, making it easier to find
More flexibility for schools to have off …
> School Admin: enable Off Timetable days by form group, update CLI scripts

- src/Forms/Input/Select.php
When a user uses another language some functionalities have a strange behavior. For example, the feature that make form fields hidden while form type is not selected. Because in the code the value should be 'Please select...'
Local
> Selection component bug fix

- composer.json
- composer.lock
* Update php version config in composer to 7.4. We have used 7.4 as the lowest supported version for a while now. We just haven't updated composer.json accordingly.
* Update libraries to their latest version possible according to the new PHP version requirement.
* Added new "php-http/discovery" composer extension as a dependency to the latest "omnipay/common" version (v3.2.1).
* Working on #1752 involves rewriting old code with [Arrow Functions](https://www.php.net/manual/en/functions.arrow.php) syntax, which was introduced in PHP 7.4.
* phpstan reports an error that doesn't make sense:
> ```
> Error: Function getResourcesTagCloud not found.
> ------ --------------------------------------------------------------------- 
> Line …
```
> composer: update php version in config

- functions.php
- modules/Planner/moduleFunctions.php
- modules/Timetable/moduleFunctions.php
* Rewrite all usages of msort in core to usort with documentation.
* Properly document msort with phpdoc and mark it deprecated.
* Part of the effort to retire old functions. See #1689.
* msort is a really old function in Gibbon (First introduced to git repo in 2286c9b0b, which was when Gibbon first migrated to git). I'm not sure if it is used elsewhere in modules (although I've searched all modules to found no reference to it). Might be safer to make it deprecated here.
* Locally.
* CI.
> Refactor: Deprecate msort

- CHANGEDB.php
- CHANGELOG.txt
- modules/Activities/activities_manage_enrolment.php
- modules/Activities/activities_manage_enrolmentProcessBulk.php
- modules/Activities/activities_manage_enrolment_add.php
- modules/Activities/activities_manage_enrolment_addProcess.php
- modules/Activities/activities_manage_enrolment_deleteProcess.php
- modules/Activities/activities_manage_enrolment_edit.php
- modules/Activities/activities_manage_enrolment_editProcess.php
- modules/Students/student_view_details.php
- src/Domain/Activities/ActivityGateway.php
- src/Domain/Activities/ActivityStaffGateway.php
- src/Domain/Activities/ActivityStudentGateway.php
- src/Domain/User/UserGateway.php
This PR improved the activity enrolment process with the following changes:
- Notification events for activity enrolment changes (add, edit, delete)
- Adds a Left status to activity enrolment to track past students in activities
- Refactors several scripts and adds bulk actions to the activity enrolment page
Makes it easier to track changes and historical data in activity enrolment.
> Activities: add a Left status for activity enrolment and notification events for enrolment changes

- CHANGELOG.txt
- modules/Staff/templates/jobOpenings.twig.html
Added anchor links to staff job openings page for individual links to each opening.
Local testing.
> Staff: added anchor links for job openings page

- index_tt_ajax.php
- modules/Activities/activities_manage_delete.php
- modules/Activities/activities_manage_enrolment_add.php
- modules/Activities/activities_my_full.php
- modules/Activities/activities_view.php
- modules/Activities/activities_view_full.php
- modules/Activities/activities_view_register.php
- modules/Activities/report_attendance_byDate.php
- modules/Attendance/attendance_take_byCourseClass.php
- modules/Attendance/attendance_take_byFormGroup.php
- modules/Attendance/attendance_take_byFormGroupProcess.php
- modules/Attendance/attendance_take_byPerson_delete.php
- modules/Attendance/attendance_take_byPerson_edit.php
- modules/Attendance/report_studentHistory.php
- passwordReset.php
Refactoring error messages in activities and attendance modules.
Refactoring echo-ed html `<div class='error'>` into `$page->addError();`.
Local testing.
> System: refactoring error messages in activities and attendance.

- .github/workflows/ci.yml
- .gitlab-ci.yml
* Add PHP 8.3 to CI in both GitHub Workflows and GitLab CI
* Includes change in #1756. Please merge #1756 first.
* PHP 8.3 has released RC.
* The list of [PHP 8.3 changes](https://php.watch/versions/8.3) don't seems to really matter for Gibbon.
* Locally.
> PHP 8.3 compatibility in all CI tests

- .github/workflows/ci.yml
- .gitlab-ci.yml
- tests/unit/Services/FormatTest.php
* Add en_GB and en_US to CI environment.
* Found out that the setlocale was incorrect in testing environment, which makes test results unstable for some of the test I'd want to add (in another PR).
* GitHub Workflows
* GitLab CI
> Fix CI environments language setup

- .github/ISSUE_TEMPLATE/config.yml
* Fix GitHub's issue config to correct "feature request" link.
* The URL pattern of categories seem to have changed. The [old "Feature Request" page URL](https://ask.gibbonedu.org/categories/feature-requests) no longer works.
* That makes the current link in the [New Issue](https://github.com/GibbonEdu/core/issues/new/choose) page unusable.
* On browser.
> github: fix issue link to feature request

- .gitlab-ci.yml
* Use "php-8.3" docker instead of "php-8.3-rc" for GitLab CI testing.
* PHP 8.3 has been released in Nov. Docker hub has the official image tag for php-8.3. The "-rc" suffix is no longer needed.
* GitLab CI pipeline [here](https://gitlab.com/yookoala/gibboneducore/-/pipelines/1122921570)
> gitlab-ci: PHP 8.3 testing update

- CHANGELOG.txt
- modules/Messenger/groups_manage.php
Messenger: Added search form and school year navigator to Manage Groups page for quicker group browsing. 
"modules/Data Updater/data_personal_manage.php" was used as an example for implementing the search form and navigator.
Implementing the search allows for quicker filtering through groups, therefore improving scalability with increasing numbers of groups.
Tested Locally.
> Messenger: added search form and school year nav to Manage Groups Page

- CHANGELOG.txt
- modules/Students/report_students_byFormGroup.php
Fixed view all option in report_students_byFormGroup.php:
The solution involved switching the usage of the `empty()` method to `!isset()` in a line of the form validation to allow for the '*' to still get picked up post-sanitisation.
The bug involved involved selecting the 'All' option in the topmost dropdown in Students, Students by Form Group. After selecting it and clicking 'Go', the data table does not get displayed.
Tested Locally
> Bug Fix: Fixed view all option in Students > Students by Form Group

- CHANGEDB.php
- CHANGELOG.txt
- index_fastFinder_ajax.php
- modules/School Admin/space_manage.php
- modules/School Admin/space_manage_add.php
- modules/School Admin/space_manage_addProcess.php
- modules/School Admin/space_manage_edit.php
- modules/School Admin/space_manage_editProcess.php
- modules/Timetable/report_viewAvailableSpaces.php
- modules/Timetable/spaceBooking_manage_add.php
- modules/Timetable/tt_space.php
- src/Domain/School/FacilityGateway.php
Added 'active' column to gibbonSpace table and changed pages to only show active facilities. This involved changing the FacilityGateway, FastFinder, Manage Facilities (including add and edit pages), Manage Space Booking, and Facilities TimeTable pages.
Important to note the the CHANGEDB file has been updated too to add the 'active' field to the gibbonSpace table.
As new classes get developed and exist in the school, or as old ones close down, it's important to be able to declare them as active or inactive such that no one mistakenly uses the inactive rooms before they are ready.
In all of these cases, the room: "B001" has had its 'active' field set to 'N' (inactive). Leaving "B001A" as …
> Added 'active' column to gibbonSpace table and changed pages to only show active facilities.

- CHANGELOG.txt
- src/Services/Format.php
Updated Format file to remove in-baked styling of Format::photo uses. The styling will now only be used as a default param.
This change allows for more modular usage of the Format::photo method stylistically.
Tested Locally
> Updated Format file to remove in-baked styling

- CHANGELOG.txt
- modules/Staff/report_absences_summary.php
- modules/Staff/report_coverage_summary.php
- src/Domain/Staff/StaffAbsenceGateway.php
Added status filter to Staff Absence and Coverage Summaries to display only 'Full' status staff by default. This was done by implementing a `$status` variable that get's changed by a checkbox form input. The filter then gets applied by the value the checkbox sets the `$status` variable to.
This fix was required to de-clutter the default viewing experience for the tables in each summary page.
Tested Locally
> Added Status Filter to Coverage and Absence Summary Forms

- .github/workflows/ci.yml
* CI to check and output all php "Notice" in server_log generated in test. More hint to improve code with.
* Allow the step to fail at the moment. Only provide verbose hint but not enforcing developer to clear all notices.
Sometimes changes in code would generate notice that are expose incorrect assumption and hence potential problem, for example:
(from: https://github.com/GibbonEdu/core/actions/runs/7955085821)
Extracting and showing verbose log about it can provide vital hints for code improvements.
Tested the base script locally against the log with notice:
> GitHub Actions: CI to check PHP Notice

- .github/workflows/ci.yml
* Always run log checks, even if previous step has failed. Provide better information for debugging and code review.
* Do not run when the job is canceled.
* Provides log analysis even when the test has failed.
* Improve errors visibility to developer on test failure.
On local branch:
https://github.com/yookoala/GibbonEduCore/actions/runs/7955748397/job/21715239643
> GitHub Actions: CI always check server logs

- .github/workflows/ci.yml
* Update workflow actions used to transit to node20.
* See: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
On GitHub:
Before:
(https://github.com/GibbonEdu/core/actions/runs/7956226859)
After:
(https://github.com/yookoala/GibbonEduCore/actions/runs/7956286647)
> GitHub Actions: update workflow actions for node20 transition

- CHANGELOG.txt
- indexFindRedirect.php
- index_fastFinder_ajax.php
Added departments as one of the searchable options with the fast finder by editing the index_fastFinder_ajax.php and indexFindRedirect.php files to be able to navigate to specific department pages from the fast finder.
For streamlining navigation to specific departments from the home page.
Tested Locally.
> Added departments as one of the searchable options with the fast finder

- CHANGELOG.txt
- modules/Behaviour/behaviour_manage_addMultiProcess.php
- modules/Behaviour/behaviour_manage_addProcess.php
Currently, behaviour notifications are only sent for negative records. However, it would be good to draw attention to those times where students receive positive behaviour notes, so this PR enables notifications for both positive and negative records.
Thanks @Fongngtis for contributing these code changes to the core.
Locally
> Behaviour: add notifications for positive behaviour records

- modules/Library/library_browse.php
- src/Domain/Library/LibraryGateway.php
added the functionality to search on basis of age in "Browse the Library" part.
Added a field for age entry in "advanced search" in "Browse the Library" part. On basis of this information only those books are shown as a result of search that are appropriate for a given age.
Interface of "advanced search" in "browse the library section" has one additional field for age entry. If the entered age is not null then only those books that fulfill this criteria: 
- Books that have non-null information in the fields "Reader Age (Youngest)", "Reader Age (Oldest)", AND
- "Reader Age (Youngest)" <= Entered Age <= "Reader Age (Oldest)" 
DB structure is not changed.
(Just a heads up, this is my first try with PHP, so make sure to give it a good look before merging. Cheers!)
**Motivation …
> Search on basis of age in Library

- modules/System Admin/thirdPartySettings_ssoEdit.php
- modules/System Admin/thirdPartySettings_ssoEditProcess.php
- src/Auth/Adapter/OAuthGenericAdapter.php
- src/Services/AuthServiceProvider.php
Some systems require additional parameters for a login request in order to read the user's basic profile.
I needed to do SSO and the institution did not use the email field as a username. With this PR, the user can configure it without changing the code. Now it is more generic and flexible.
Locally and Travis
> Improvement in Generic OAuth

- src/Services/Format.php
- tests/unit/Services/FormatTest.php
* dateIntlReadable to replace dateReadable
* dateTimeIntlReadable to replace dateTimeReadable
* Add test coverage to Format::dateTimeReadable, Format::dateIntlReadable and Format::dateTimeIntlReadable.
* Pave way to refactor away the remaining usages of strftime (see #1643).
* Locally.
> Format: new functions for readable date-time conversion

- CHANGEDB.php
- CHANGELOG.txt
- modules/Staff/absences_manage.php
- modules/Staff/absences_manage_edit.php
- modules/Staff/absences_view_byPerson.php
- modules/Staff/absences_view_cancel.php
- modules/Staff/absences_view_cancelProcess.php
- modules/Staff/coverage_manage_deleteProcess.php
- modules/Staff/coverage_my.php
- modules/Staff/src/AbsenceNotificationProcess.php
- modules/Staff/src/CoverageNotificationProcess.php
- modules/Staff/src/Messages/AbsenceCancelled.php
- modules/Staff/src/Messages/AbsenceWithCoverageCancelled.php
- modules/Staff/src/Tables/AbsenceDates.php
- modules/Staff/src/Tables/AbsenceFormats.php
- modules/Staff/src/Tables/CoverageDates.php
- src/Domain/Staff/StaffAbsenceDateGateway.php
Currently, if staff members submit an absence and something comes up where it's no longer necessary, they would need to contact an admin to delete it for them. However, when this happens first thing in the morning when arranging staff coverage, this can be problematic. This feature adds the ability for staff members to cancel an absence, including any attached coverage requests, as long as it is on or before the date of the absence. Doing so sends a message to all parties involved about the cancelled absence.
The main changes are:
- Adds a new Cancelled status to gibbonStaffAbsence, and implements in existing queries & tables
- Adds a "Cancel" button to the View Absences page for a staff member
- Adds new messages for AbsenceCancelled and AbsenceWithCoverageCancelled
- Also updates the …
> Staff: add the ability for staff members to cancel an absence before it occurs

- modules/Library/library_browse.php
- modules/Library/templates/librarySearch.twig.html
1. By default, library_browse.php statically filters out all books which are not located in the location called "Library". Its not based on country or language. If the locations name is not exactly "Library" (eg Bibliothek in German), the books will get filtered out by default unless the user is attentive enough to not miss the check-box "include books outside of Library". But in that case all the books are included and not only "Library's".  My proposal for fix here is to have the check box checked by default, and the user can actively deselect it if too many unwanted results are shown. The confusion of having too many results seems better than the confusion of having no results at all.
2. The template librarySearch.twig.html silently hides books from the search results …
> Books without cover art are not shown + books outside "library" are not shown by default

- CHANGELOG.txt
- index_tt_ajax.php
- modules/Timetable/moduleFunctions.php
- src/UI/Dashboard/StaffDashboard.php
- src/UI/Dashboard/StudentDashboard.php
Currently, navigating the timetable causes the whole page to reload. This PR implements HTMX to reload only the timetable itself, and improves the function of the navigation buttons. Changing calendar or bookings checkboxes also no longer reloads the whole timetable.
UI Improvements
Locally
> System: update the timetable navigation to use AJAX reloading

- CHANGELOG.txt
- modules/Activities/activities_view.php
The registration button is not shown to the parent. 
there is a variable used before creation.
> Activities: fix bug in activity registration by parent

- resources/templates/components/editor.twig.html
When editing a Freelearning Unit (Home > Free Learning > Manage Units > Edit Unit), if there multiple smartblocks in the unit, the html tab in the tinymce editor does not _always_ work. Upon investigation, it seems that the event listener was not always correctly added for all of the `#{{ id }}edButtonHTML` elements. 
By only adding the eventlistener once, tinymce is set up correctly, and after that the click event listeners is added for each `#{{ id }}edButtonHTML` by loopindirectly, rather than through the `tinymceSetup` event listener.
Tested on the MOS environment and confirmed by users that fix resolved the issue. Each of the smartblocks are not editable consistently.
> Only add tinymcesetup event listener once
